// scenery.js — generated by tools/landscape-gen.js — do not hand-edit
// source: landscape-manifest.json
import * as THREE from 'three';

function _sr(min, max) { return min + Math.random() * (max - min); }
function _neon(pal) { return pal[Math.floor(Math.random() * pal.length)]; }
function _addMesh(g, geo, mat, y) { const m = new THREE.Mesh(geo, mat); m.position.y = y; g.add(m); }
function _basicAdd(col) {
  return new THREE.MeshBasicMaterial({ color: col, blending: THREE.AdditiveBlending, depthWrite: false });
}
function _disposeMesh(obj) {
  obj.traverse(c => { if (c.isMesh) { c.geometry.dispose(); if (Array.isArray(c.material)) c.material.forEach(m => m.dispose()); else c.material.dispose(); } });
}


const _PAL_WALLS = [0x00aaff, 0xaa00ff, 0x00ffcc, 0xff00aa, 0xffaa00, 0x44aaff];

function _build_walls_wall_panel() {
  const H = _sr(22, 38);
  const g = new THREE.Group();
  _addMesh(g, new THREE.BoxGeometry(2, H, 55), new THREE.MeshStandardMaterial({ color: 0x0c0c20, emissive: 0x060612, emissiveIntensity: 0.3, roughness: 0.8 }), H / 2);
  const _cols = 7, _rows = Math.max(3, Math.floor(H / 5));
  for (let r = 0; r < _rows; r++) {
    for (let c = 0; c < _cols; c++) {
      if (Math.random() < 0.25) continue;
      const wm = new THREE.Mesh(
        new THREE.BoxGeometry(2.6, _sr(0.8, 2.0), _sr(1.0, 3.0)),
        new THREE.MeshBasicMaterial({ color: _neon(_PAL_WALLS), blending: THREE.AdditiveBlending, depthWrite: false })
      );
      wm.position.set(0, (r + 0.7) * (H / _rows), -27.5 + (c + 0.5) * 7.86);
      g.add(wm);
    }
  }
  return g;
}

function _buildItem_walls() {
  const builders = [_build_walls_wall_panel];
  return builders[Math.floor(Math.random() * builders.length)]();
}

let _pool_walls = [];

function _init_walls(scene) {
  _pool_walls = [];
  for (let i = 0; i < 14 * 2; i++) {
    const side = i < 14 ? -1 : 1;
    const mesh = _buildItem_walls();
    const x = side * _sr(10, 10);
    const z = -10 - (i % 14) * 50;
    mesh.position.set(x, 0, z);
    scene.add(mesh);
    _pool_walls.push({ mesh, side });
  }
}

function _update_walls(scene, dt, worldSpeed) {
  const spd = worldSpeed * 1;
  for (const s of _pool_walls) {
    s.mesh.position.z += spd * dt;
    if (s.mesh.position.z > 15) {
      scene.remove(s.mesh);
      _disposeMesh(s.mesh);
      s.mesh = _buildItem_walls();
      s.mesh.position.set(s.side * _sr(10, 10), 0, -710);
      scene.add(s.mesh);
    }
  }
}

const _PAL_SKYLINE = [0x0a2040, 0x0c2850, 0x0e1e38, 0x112244];

function _build_skyline_slab() {
  const h = _sr(30, 80), w = _sr(4, 12), d = _sr(4, 10);
  const g = new THREE.Group();
  _addMesh(g, new THREE.BoxGeometry(w, h, d), new THREE.MeshStandardMaterial({ color: _neon(_PAL_SKYLINE), emissive: _neon(_PAL_SKYLINE), emissiveIntensity: 0.5, roughness: 1.0, metalness: 0 }), h / 2);
  return g;
}

function _buildItem_skyline() {
  const builders = [_build_skyline_slab];
  return builders[Math.floor(Math.random() * builders.length)]();
}

let _pool_skyline = [];

function _init_skyline(scene) {
  _pool_skyline = [];
  for (let i = 0; i < 12 * 2; i++) {
    const side = i < 12 ? -1 : 1;
    const mesh = _buildItem_skyline();
    const x = side * _sr(28, 46);
    const z = _sr(-40, -380);
    mesh.position.set(x, 0, z);
    scene.add(mesh);
    _pool_skyline.push({ mesh, side });
  }
}

function _update_skyline(scene, dt, worldSpeed) {
  const spd = worldSpeed * 0.6;
  for (const s of _pool_skyline) {
    s.mesh.position.z += spd * dt;
    if (s.mesh.position.z > 20) {
      s.mesh.position.z = _sr(-40, -380);
      s.mesh.position.x = s.side * _sr(28, 46);
    }
  }
}

export function initScenery(scene) {
  _init_walls(scene);
  _init_skyline(scene);
}

export function updateScenery(scene, dt, worldSpeed) {
  _update_walls(scene, dt, worldSpeed);
  _update_skyline(scene, dt, worldSpeed);
}
