import './style.css';
import * as THREE from 'three';
import { createWorld } from './world.js';
import { createGame, HEROES, ITEMS, SKILLS, ENCOUNTERS, LANDMARKS, SAVE_KEY } from './game.js';
import { createAudio } from './audio.js';

const $ = (s) => document.querySelector(s);
const base = import.meta.env.BASE_URL;
const portrait = id => `${base}art/${id}.svg`;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cap = s => String(s).replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const icons = {food:'✦',ore:'⬡',energy:'ϟ',renown:'✧',attack:'╱',defense:'◇',speed:'»',maxHp:'♥',maxMp:'ϟ'};
const ui = $('#ui'), canvas = $('#world');
const audio = createAudio();
let world, game, menuTab='Map', previousMode='explore', selectedHero='kaida', selectedAction=null, battleCategory='Attack', selectedTarget=null, selectedItem=null;
let dialogue=null, dialogueAfter=null, announcementTimer=0, announceText='', announceSub='', lastMode='', lastHudHash='', lastUiUpdate=0;
let nearby=null, path=[], destination=null, keys=new Set(), joystick={x:0,y:0}, lastTime=performance.now(), elapsed=0, audioMode='', lastStep=0;
let assetsLoading=true, busy=false, initialHint=true, bootError=null, aimRing=null, aimRadius=0, resultRevealAt=0;
const held = k => keys.has(k);
const heroes = () => game.state.party;
const heroDef = id => Array.isArray(HEROES) ? HEROES.find(h=>h.id===id) : HEROES[id];
const hpct = (n,d) => Math.max(0,Math.min(100,n/(d||1)*100));
function toast(message) { const e=document.createElement('div'); e.className='toast'; e.textContent=message; $('#toasts').append(e); setTimeout(()=>e.remove(),4400); }
function announce(title,sub='') { announceText=title; announceSub=sub; announcementTimer=4; const e=$('#announcement'); if(e){e.innerHTML=`<span>${esc(sub)}</span><h2>${esc(title)}</h2>`;e.classList.add('show');} }
function onEvent(e) {
  if(e.type==='effect') {world?.effect(e.effect); if(e.effect?.label)setTimeout(()=>floater(e.effect),({attack:180,tech:300,combo:350,triple:500}[e.effect.type]||0));}
  if(e.type==='sound')setTimeout(()=>audio.play(e.name),({attack:180,tech:300,combo:350,triple:500,hit:180}[e.name]||0));
  if(e.type==='toast') toast(e.message);
  if(e.type==='dialogue') showDialogue([{speaker:e.speaker||'The crew',text:e.text}],()=>{game.state.mode='explore';game.save();render();});
  if(e.type==='battleStart'){ path=[];destination=null;selectedAction=null; battleCategory='Attack'; selectedTarget=null; world?.setBattle(game.state.battle); announce(ENCOUNTERS[game.state.battle.id]?.name||'Contact','ENGAGEMENT');}
  if(e.type==='victory'){selectedAction=null;resultRevealAt=elapsed+1.65;}
  if(e.type==='defeat')resultRevealAt=elapsed+1.1;
  if(e.type==='ending'){world?.setBattle(null);audio.play('build');}
  lastHudHash='';
}
function floater(effect) {if(!world||!effect.target)return;const p=world.project(effect.target.x,effect.target.z,2.7);if(!p.visible)return; const e=document.createElement('div');e.className=`floater ${effect.type==='heal'?'heal':''}`;e.textContent=effect.label;e.style.left=`${p.x}px`;e.style.top=`${p.y}px`;$('#floaters').append(e);setTimeout(()=>e.remove(),1400);}
try { game=createGame(onEvent); world=createWorld(canvas); } catch(error) {bootError=error;console.error(error);ui.innerHTML=`<div class="boot-error panel"><p class="eyebrow">CHRONOFORGE DUSK</p><h1>The valley could not open.</h1><p>This game needs a browser with WebGL 2 enabled. Try a current Chrome, Safari, Firefox, or Edge.</p><pre>${esc(error.message)}</pre><button onclick="location.reload()">Try again</button></div>`;}
if(!bootError) init();
function init(){
  if(innerWidth<760)game.state.settings.quality='medium';
  aimRing=new THREE.Mesh(new THREE.RingGeometry(.95,1,64),new THREE.MeshBasicMaterial({color:0x98ead6,transparent:true,opacity:.55,side:THREE.DoubleSide,depthWrite:false}));aimRing.rotation.x=-Math.PI/2;aimRing.visible=false;world.scene.add(aimRing);
  render();world.setQuality(game.state.settings.quality);Promise.resolve(world.assetsReady).then(()=>{assetsLoading=false;if(game.state.mode==='title')render();});window.addEventListener('resize',()=>world.resize());
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&['explore','battle'].includes(game.state.mode))openMenu('Settings');});
  ui.addEventListener('click',handleClick);ui.addEventListener('input',handleInput);
  window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return; const k=e.key.toLowerCase(); if([' ','arrowup','arrowdown','arrowleft','arrowright','tab'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;
    if(k==='escape'){if(dialogue)advanceDialogue();else if(game.state.mode==='menu')closeMenu();else if(['explore','battle'].includes(game.state.mode))openMenu('Map');}
    if(k==='m'&&game.state.mode==='explore')openMenu('Map');
    if(k==='j'&&game.state.mode==='explore')openMenu('Quests');
    if(k==='i'&&game.state.mode==='explore')openMenu('Inventory');
    if(k==='e'||k===' '||k==='enter'){if(dialogue)advanceDialogue();else if(game.state.mode==='explore')interactNearest();else if(game.state.mode==='battle'&&selectedAction)executeAction();}
    if(['1','2','3'].includes(k)&&game.state.mode==='battle'){selectedHero=heroes()[Number(k)-1].id;selectedAction=null;render();}
    if(k==='tab'&&game.state.mode==='battle'){const i=heroes().findIndex(h=>h.id===selectedHero);selectedHero=heroes()[(i+1)%3].id;selectedAction=null;render();}
  });
  window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();joystick={x:0,y:0};});
  canvas.addEventListener('pointerdown',e=>{audio.start();if(game.state.mode!=='explore')return; const p=world.screenToGround(e.clientX,e.clientY);if(p)setDestination(p);});
  window.addEventListener('pointerup',()=>{joystick={x:0,y:0};const knob=$('#joy-knob');if(knob)knob.style.transform='translate(0,0)';});
  ui.addEventListener('pointerdown',e=>{const joy=e.target.closest('#joystick');if(!joy)return;joy.setPointerCapture(e.pointerId);moveJoy(e,joy);});
  ui.addEventListener('pointermove',e=>{const joy=e.target.closest('#joystick');if(joy?.hasPointerCapture(e.pointerId))moveJoy(e,joy);});
  requestAnimationFrame(frame);
  // Stable read-only inspection surface; state/methods are exposed only with ?test=1 for repeatable QA.
  if(new URLSearchParams(location.search).has('test'))window.__dusk={game,world,audio,openMenu,closeMenu,render,interact:(id)=>{game.interact(id);render();},teleport:(x,z)=>{game.state.player={x,z};path=[];destination=null;},setDestination,showDialogue,advanceDialogue,get navigation(){return{nearby,path,destination}},snapshot:()=>JSON.parse(JSON.stringify(game.state))};
}
function moveJoy(e,joy){const r=joy.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/36,y=(e.clientY-r.top-r.height/2)/36,m=Math.max(1,Math.hypot(x,y));joystick={x:x/m,y:y/m};$('#joy-knob').style.transform=`translate(${joystick.x*30}px,${joystick.y*30}px)`;}
function frame(now){const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;elapsed+=dt;
  const s=game.state; game.update(dt,{paused:!['battle','explore'].includes(s.mode)});
  if(s.mode==='explore')updateMovement(dt);
  world.update(dt,s);updateAim();world.render();
  const musicMode=s.mode==='menu'?previousMode:s.mode==='battle'?(s.battle?.id==='boss'?'boss':'battle'):s.mode;
  if(musicMode!==audioMode){audioMode=musicMode;audio.setMode(musicMode);}
  if(s.mode!==lastMode){lastMode=s.mode;render();}if(resultRevealAt&&elapsed>=resultRevealAt){resultRevealAt=0;render();}
  if(announcementTimer>0){announcementTimer-=dt;if(announcementTimer<=0)$('#announcement')?.classList.remove('show');}
  if(now-lastUiUpdate>110){lastUiUpdate=now;updateHud();}
  requestAnimationFrame(frame);
}
function updateMovement(dt){const s=game.state,p=s.player;let sx=(held('d')||held('arrowright')?1:0)-(held('a')||held('arrowleft')?1:0)+joystick.x;let sy=(held('s')||held('arrowdown')?1:0)-(held('w')||held('arrowup')?1:0)+joystick.y;
  let dx=0,dz=0; if(sx||sy){path=[];destination=null;const center=world.screenToGround(innerWidth*.5,innerHeight*.5);const next=world.screenToGround(innerWidth*.5+sx*50,innerHeight*.5+sy*50);if(center&&next){dx=next.x-center.x;dz=next.z-center.z;}}
  else if(path.length){const target=path[0];dx=target.x-p.x;dz=target.z-p.z;if(Math.hypot(dx,dz)<.25){path.shift();if(!path.length)destination=null;}}
  const len=Math.hypot(dx,dz);if(len>.01){const speed=(held('shift')?7.2:5.2)*dt;dx=dx/len*Math.min(speed,len);dz=dz/len*Math.min(speed,len); if(world.canWalk(p.x+dx,p.z+dz)){p.x+=dx;p.z+=dz;}else{if(world.canWalk(p.x+dx,p.z))p.x+=dx;if(world.canWalk(p.x,p.z+dz))p.z+=dz;} if(elapsed-lastStep>.38){audio.play('step');lastStep=elapsed;}}
  const lm=LANDMARKS.filter(l=>!s.cleared.includes(l.id)&&!(l.id==='cache-west'&&s.flags.cacheWest)&&!(l.id==='cache-east'&&s.flags.cacheEast));
  nearby=lm.map(l=>({...l,d:Math.hypot(l.x-p.x,l.z-p.z)})).sort((a,b)=>a.d-b.d)[0];if(nearby?.d>3)nearby=null;
  if(nearby&&['causeway','garden','wardens'].includes(nearby.id)&&nearby.d<2){game.startBattle(nearby.id,{x:nearby.x,z:nearby.z});return;}
  const zone=zoneAt(p);if($('#area-name')&&$('#area-name').textContent!==zone)$('#area-name').textContent=zone;
}
function zoneAt(p){if(p.z>9)return'Bellwether Settlement';if(p.z<-18)return'Meridian Observatory';if(p.x<-7)return'The Glass Garden';if(p.x>7)return'The Sunken Archive';return'The Broken Causeway';}
function setDestination(p){if(!world.canWalk(p.x,p.z)){toast('Find a clear path through the valley.');return;}destination=p;path=findPath(game.state.player,p);if(!path.length)destination=null;}
function findPath(start,end){const step=1.4,key=(x,z)=>`${x},${z}`;const sx=Math.round(start.x/step),sz=Math.round(start.z/step),ex=Math.round(end.x/step),ez=Math.round(end.z/step);let open=[{x:sx,z:sz,g:0,f:0}],seen=new Map(),found;seen.set(key(sx,sz),open[0]);for(let n=0;n<3500&&open.length;n++){open.sort((a,b)=>a.f-b.f);const node=open.shift();if(node.x===ex&&node.z===ez){found=node;break;}node.closed=true;for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const x=node.x+dx,z=node.z+dz;if(Math.abs(x*step)>24||z*step<-28||z*step>22||!world.canWalk(x*step,z*step))continue;if(dx&&dz&&(!world.canWalk((node.x+dx)*step,node.z*step)||!world.canWalk(node.x*step,(node.z+dz)*step)))continue;const k=key(x,z),g=node.g+Math.hypot(dx,dz),old=seen.get(k);if(old&&(old.closed||old.g<=g))continue;const next={x,z,g,f:g+Math.hypot(ex-x,ez-z),parent:node};if(old)open.splice(open.indexOf(old),1);seen.set(k,next);open.push(next);}}
  if(!found)return[{x:end.x,z:end.z}];const out=[end];while(found.parent){out.unshift({x:found.x*step,z:found.z*step});found=found.parent;}return out;
}
function objective(){const s=game.state;if(s.flags.bossDefeated||s.cleared.includes('boss'))return'Bellwether has a tomorrow.';if(!s.cleared.includes('causeway'))return'Clear the broken causeway';if(!s.flags.relayWest||!s.flags.relayEast)return`Restore the two sun relays · ${Number(!!s.flags.relayWest)+Number(!!s.flags.relayEast)}/2`;return'Awaken the Meridian Observatory';}
function startNew(){audio.start();resultRevealAt=0;game.newGame();world.setBattle(null);selectedHero='kaida';initialHint=true;showDialogue([
  {speaker:'Kaida',text:'That ring on the horizon. Tell me it can still catch the sun.'},
  {speaker:'Rune',text:'The Meridian array? Technically. It has only been broken for three hundred years.'},
  {speaker:'Vex',text:'Then we should hurry. I would hate to make it wait.'},
  {speaker:'Mira',text:'Welcome to Bellwether. Clear the causeway, wake the two sun relays, and we might have light through the winter. Any salvage you find can rebuild our hearth beacon.'}
],()=>{game.state.mode='explore';announce('Bellwether','THE LAST LIGHT · CHAPTER I');toast('WASD to move · Click ground to travel · E to interact · M for map');render();});}
function loadGame(){audio.start();if(game.load()){world.setBattle(game.state.battle||null);applySettings();toast('Your journey continues.');render();}else toast('No valid saved journey found.');}
function showDialogue(lines,after){const mode=game?.state.mode;dialogue=lines.map(l=>({...l,text:Array.isArray(l.text)?l.text.join(' '):l.text}));dialogueAfter=after||(()=>{game.state.mode=mode==='dialogue'?'explore':mode;render();});if(game)game.state.mode='dialogue';path=[];render();}
function advanceDialogue(){if(!dialogue)return;audio.play('click');dialogue.shift();if(!dialogue.length){dialogue=null;const f=dialogueAfter;dialogueAfter=null;f?.();}render();}
function interactNearest(){if(!nearby){toast('Move closer to a person, cache, or relay.');return;}const id=nearby.id;audio.play('interact');if(id==='beacon'){openMenu('Settlement');return;}if(id==='mira'){game.interact(id);return;}game.interact(id);render();}
function openMenu(tab='Map'){if(!['explore','battle','menu'].includes(game.state.mode))return;if(game.state.mode!=='menu')previousMode=game.state.mode;game.state.mode='menu';menuTab=tab;path=[];keys.clear();joystick={x:0,y:0};audio.play('click');render();}
function closeMenu(){game.state.mode=previousMode;audio.play('click');render();}
function getActions(){return game.getActions(selectedHero)||[];}
function actionAvailable(a){return a.available!==false;}
function chooseAction(id){const actions=getActions(),combo=game.getCombos().find(a=>a.id===id);selectedAction=actions.find(a=>a.id===id)||combo;if(!selectedAction)return;if(selectedAction.participants&&!selectedAction.participants.includes(selectedHero))selectedHero=selectedAction.participants[0];if(!actionAvailable(selectedAction)){toast(selectedAction.reason||'The crew needs more ATB or energy.');return;}
 if(['self','all'].includes(selectedAction.target)||id==='defend'){executeAction();return;}const ally=selectedAction.target==='ally';const targets=ally?heroes():game.state.battle.enemies;selectedTarget=targets.find(t=>t.hp>0)?.id;render();}
function executeAction(){if(!selectedAction)return;const result=game.act(selectedHero,selectedAction.id,selectedTarget);if(!result?.ok){toast(result?.message||'That action is not ready.');return;}selectedAction=null;selectedTarget=null;const next=heroes().find(h=>h.hp>0&&h.atb>=100);if(next)selectedHero=next.id;render();}
function handleClick(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;audio.start();if(!['execute','command'].includes(a))audio.play('click');
  if(a==='new')startNew(); if(a==='continue')loadGame(); if(a==='advance')advanceDialogue(); if(a==='menu')openMenu(b.dataset.tab||'Map');if(a==='tab'){menuTab=b.dataset.tab;render();}if(a==='close')closeMenu();
  if(a==='hero'){selectedHero=b.dataset.id;selectedAction=null;render();}if(a==='category'){battleCategory=b.dataset.id;selectedAction=null;render();}if(a==='command')chooseAction(b.dataset.id);
  if(a==='target'){selectedTarget=b.dataset.id;render();}if(a==='execute')executeAction();if(a==='cancel-action'){selectedAction=null;render();}
  if(a==='interact')interactNearest();if(a==='build'){const r=game.build();if(r?.ok)game.save();render();}
  if(a==='item'){selectedItem=b.dataset.id;render();}if(a==='use-item'){game.useItem(selectedItem,b.dataset.hero);render();}if(a==='equip'){const r=game.equip(b.dataset.hero,selectedItem);if(r?.message)toast(r.message);render();}if(a==='learn'){const r=game.learn(b.dataset.hero,b.dataset.id);if(r?.message)toast(r.message);render();}
  if(a==='save'){const r=game.save();toast(r===false?'Save could not be written. Browser storage may be unavailable.':'Journey saved on this device.');audio.play('save');render();}if(a==='load'){loadGame();}
  if(a==='title'){game.save();game.state.mode='title';world.setBattle(null);render();}
  if(a==='victory'){world.setBattle(null);game.state.battle=null;game.state.mode='explore';game.save();if(game.state.cleared.includes('boss')||game.state.flags.bossDefeated){game.interact('boss');game.save();}render();}
  if(a==='retry'){resultRevealAt=0;game.retry();world.setBattle(game.state.battle);selectedAction=null;render();}
  if(a==='waypoint'&&previousMode!=='battle'){const l=LANDMARKS.find(l=>l.id===b.dataset.id);if(l){closeMenu();setDestination(l);toast(`Traveling toward ${l.name}.`);}}
  if(a==='rest'){if(game.state.mode==='menu'&&previousMode==='battle'){toast('Return to Bellwether after the battle to rest.');return;}if(game.state.player.z<9){toast('Return to Bellwether to rest by the hearth.');return;}if(game.state.resources.food<1){toast('A rest costs 1 food.');return;}game.state.resources.food--;heroes().forEach(h=>{const stats=game.getStats(h.id);h.hp=stats.maxHp;h.mp=stats.maxMp;h.statuses=[];});toast('The crew shares a meal. HP and energy restored.');audio.play('heal');render();}
  if(a==='help'){showDialogue([{speaker:'Field guide',text:'Move with WASD or arrow keys, or click a destination. Hold Shift to run. E interacts with nearby landmarks. On touch screens, drag the left stick and tap Interact.'},{speaker:'Field guide',text:'In battle, a full action gauge pauses enemy time. Your other heroes continue charging. Enemy time resumes while actions resolve. Select a hero, then an action and a target. Techniques use energy. Nearby enemies share area damage. The three pair techniques and Aeon Sunder spend every participant’s gauge.'},{speaker:'Field guide',text:'Explore both branches to restore the relays. Spend skill points and equip salvage from your journal. Build the hearth beacon for a lasting crew benefit, then return to the observatory.'}],()=>{game.state.mode=previousMode==='battle'?'battle':'explore';render();});}
  if(a==='ending-explore'){game.state.mode='explore';world.setBattle(null);game.state.battle=null;game.save();render();}
}
function handleInput(e){const key=e.target.dataset.setting;if(!key)return;game.state.settings[key]=['music','sfx','battleSpeed'].includes(key)?Number(e.target.value):e.target.value;applySettings();if(key==='quality')toast(`${cap(e.target.value)} visual quality applied.`);}
function applySettings(){const s=game.state.settings;audio.setVolumes(s.music,s.sfx);world.setQuality(s.quality);}
function render(){if(!game)return;const s=game.state;
  if(s.mode==='title'){ui.innerHTML=titleHTML();return;}
  if(s.mode==='ending'){ui.innerHTML=endingHTML();return;}
  ui.innerHTML=`${hudHTML()}${s.mode==='battle'||(resultRevealAt&&['victory','defeat'].includes(s.mode))?battleHTML():''}${s.mode==='menu'?menuHTML():''}${dialogue?dialogueHTML():''}${s.mode==='victory'&&!resultRevealAt?victoryHTML():''}${s.mode==='defeat'&&!resultRevealAt?defeatHTML():''}`;
  lastHudHash='';updateHud();
}
function titleHTML(){let saved=false;try{saved=!!localStorage.getItem(SAVE_KEY);}catch{}return `<div class="title-screen"><div class="title-top"><span class="wordmark"><img src="${base}art/emblem.svg" alt=""/> A CHRONOFORGE STORY</span><span class="edition">SINGLE CHAPTER / I</span></div><section class="title-copy"><div class="overline"><span></span> AT THE EDGE OF TOMORROW</div><h1>CHRONOFORGE<span>DUSK</span></h1><p class="chapter-title">The Last Light of Bellwether</p><p class="title-desc">The old world left a light behind.<br>Bring it home.</p><div class="title-buttons"><button class="primary large" data-action="${saved?'continue':'new'}" ${assetsLoading?'disabled':''}>${assetsLoading?'Preparing the valley…':saved?'Continue journey':'Begin journey'} <span>${assetsLoading?'◌':'↗'}</span></button>${saved?'<button class="text-button" data-action="new">Start a new chapter</button>':''}</div><div class="title-meta"><span>01 <i>AN UNBROKEN PROMISE</i></span><p>A complete adventure for three unlikely heroes.</p></div></section><div class="title-footer"><span>HEADPHONES RECOMMENDED <span class="sound-lines">▂▅▃▆▂</span></span><span>KEYBOARD + MOUSE / TOUCH</span></div><div class="title-place"><span>THE MERIDIAN VALLEY</span><strong>36° N · 118° W</strong><small>Year 307 after the silence</small></div></div>`;}
function hudHTML(){const s=game.state,b=['battle','victory','defeat'].includes(s.mode)||(s.mode==='menu'&&previousMode==='battle');return `<div class="hud ${s.mode==='menu'||dialogue?'subdued':''}"><header class="topbar"><div class="location"><img src="${base}art/emblem.svg" alt=""/><div><p class="eyebrow">MERIDIAN VALLEY <span>CHAPTER I</span></p><h2 id="area-name">${b?'Tactical engagement':zoneAt(s.player)}</h2></div></div><div class="top-right"><div class="resource-row">${Object.entries(s.resources).map(([k,v])=>`<span title="${cap(k)}"><i class="res-${k}">${icons[k]||'◇'}</i> <b data-resource="${k}">${v}</b><small>${cap(k)}</small></span>`).join('')}</div><button class="journal-button" data-action="menu" aria-label="Open journal">☷ <span>Journal</span><kbd>ESC</kbd></button></div></header><div class="objective"><span class="quest-diamond">◇</span><div><small>THE LAST LIGHT</small><p>${objective()}</p></div></div><div id="announcement" class="announcement ${announcementTimer>0?'show':''}"><span>${esc(announceSub)}</span><h2>${esc(announceText)}</h2></div>${!b?`<div class="explore-party">${heroes().map((h,i)=>heroCard(h,i,false)).join('')}</div><div class="map-corner"><button class="minimap-wrap" data-action="menu" data-tab="Map" aria-label="Open valley map">${mapSVG(true)}<span>MERIDIAN VALLEY <kbd>M</kbd></span></button></div><div class="travel-controls"><span><kbd>W A S D</kbd> Move</span><span><kbd>E</kbd> Interact</span><span><kbd>SHIFT</kbd> Run</span><button data-action="help">? Field guide</button></div><button class="interact-prompt" id="interact-prompt" data-action="interact" hidden><kbd>E</kbd><span></span><i>↗</i></button><div class="touch-controls"><div id="joystick" aria-label="Movement joystick"><div id="joy-knob"></div></div><button data-action="interact">Interact</button></div>`:''}</div>`;}
function heroCard(h,i,battle){const stats=game.getStats(h.id);return `<button class="hero-card ${battle?'combat-hero':''} ${battle&&h.id===selectedHero?'selected':''} ${h.hp<=0?'fallen':''}" data-action="${battle?'hero':'menu'}" data-tab="Party" data-id="${h.id}" style="--hero:${heroDef(h.id)?.color||'#7cd9d6'}"><div class="portrait-small"><img src="${portrait(h.id)}" alt="${h.name}"/></div><div class="hero-vitals"><div class="hero-name"><strong>${h.name}</strong><small>${battle?`<kbd>${i+1}</kbd>`:`LV ${h.level}`}</small></div><div class="vital-label"><span data-hp-text="${h.id}">${Math.ceil(h.hp)} <em>/ ${stats.maxHp}</em></span><small>HP</small></div><div class="bar health"><i data-hp="${h.id}" style="width:${hpct(h.hp,stats.maxHp)}%"></i></div><div class="mp-row"><span data-mp-text="${h.id}">${Math.floor(h.mp)} / ${stats.maxMp}</span><small>EN</small></div>${battle?`<div class="bar atb"><i data-atb="${h.id}" style="width:${h.atb}%"></i></div><span class="ready-label" data-ready="${h.id}">${h.hp<=0?'DOWN':h.atb>=100?'READY':'CHARGING'}</span><small class="hero-statuses" data-hero-status="${h.id}">${h.statuses?.map(x=>x.name).join(' · ')||''}</small>`:''}</div></button>`;}
function updateHud(){const s=game.state;if(['title','ending'].includes(s.mode))return;for(const h of heroes()){const stats=game.getStats(h.id);document.querySelectorAll(`[data-hp="${h.id}"]`).forEach(e=>e.style.width=`${hpct(h.hp,stats.maxHp)}%`);document.querySelectorAll(`[data-hp-text="${h.id}"]`).forEach(e=>e.innerHTML=`${Math.ceil(h.hp)} <em>/ ${stats.maxHp}</em>`);document.querySelectorAll(`[data-mp-text="${h.id}"]`).forEach(e=>e.textContent=`${Math.floor(h.mp)} / ${stats.maxMp}`);document.querySelectorAll(`[data-atb="${h.id}"]`).forEach(e=>e.style.width=`${h.atb}%`);document.querySelectorAll(`[data-ready="${h.id}"]`).forEach(e=>{e.textContent=h.hp<=0?'DOWN':h.atb>=100?'READY':'CHARGING';e.classList.toggle('is-ready',h.atb>=100);});}
  for(const h of heroes()){const e=$(`[data-hero-status="${h.id}"]`);if(e)e.textContent=h.statuses?.map(x=>x.name).join(' · ')||'';}
  for(const [k,v] of Object.entries(s.resources)){const e=$(`[data-resource="${k}"]`);if(e)e.textContent=v;}
  const ip=$('#interact-prompt');if(ip){ip.hidden=!nearby;if(nearby)ip.querySelector('span').textContent=nearby.name||cap(nearby.id);}
  const marker=$('#map-player');if(marker){marker.setAttribute('cx',game.state.player.x+27);marker.setAttribute('cy',game.state.player.z+31);}
  if(['battle','victory','defeat'].includes(s.mode)&&s.battle){const area=$('#area-name');if(area)area.textContent=s.battle.id==='boss'?'The Pale Warden':'Engagement · '+zoneAt(s.battle.origin);const occupiedLabels=[];for(const en of s.battle.enemies){const e=$(`[data-enemy="${en.id}"]`);if(!e)continue;const p=world.project(s.battle.origin.x+en.x,s.battle.origin.z+en.z,en.type==='boss'?4.8:2.7);let lx=p.x,ly=p.y;if(en.hp>0&&p.visible){for(const r of occupiedLabels){if(Math.abs(lx-r.x)<145&&Math.abs(ly-r.y)<85)lx=r.x+150;}lx=Math.max(80,Math.min(innerWidth-80,lx));occupiedLabels.push({x:lx,y:ly});}e.style.transform=`translate(${lx}px,${ly}px) translate(-50%,-100%)`;e.hidden=en.hp<=0||!p.visible;e.querySelector('.health i').style.width=`${hpct(en.hp,en.maxHp)}%`;e.querySelector('.enemy-hp').textContent=`${Math.ceil(en.hp)} / ${en.maxHp}`;e.querySelector('.atb i').style.width=`${en.atb}%`;const intent=e.querySelector('[data-intent]');if(intent)intent.textContent=(en.type==='boss'?`PHASE ${s.battle.phase} · `:'')+(en.intent?.name||'');const status=e.querySelector('[data-status]');if(status)status.textContent=en.statuses?.map(x=>x.name||x.id).join(' · ')||'';}
    const hash=JSON.stringify([heroes().map(h=>[h.hp<=0,h.atb>=100,Math.floor(h.mp),h.statuses]),s.battle.enemies.map(e=>[e.id,e.hp<=0,e.statuses]),s.battle.phase,s.battle.actionDelay>0,s.battle.enemies.map(e=>e.intent),s.battle.log?.slice(0,1)]);if(hash!==lastHudHash){lastHudHash=hash;const cmd=$('#command-panel');if(cmd)cmd.innerHTML=commandHTML();const log=$('#battle-log');if(log)log.innerHTML=(s.battle.log||[]).slice(0,2).map(l=>`<p>${esc(typeof l==='string'?l:l.text||l.message)}</p>`).join('');}
  }
}
function battleHTML(){const b=game.state.battle;if(!b)return'';return `<div class="battle-scene-ui"><div class="battle-top"><span class="eyebrow">${b.id==='boss'?'ANCIENT DEFENSE SYSTEM':'TACTICAL ENGAGEMENT'}</span><h2>${b.id==='boss'?'The Pale Warden':ENCOUNTERS[b.id]?.name||'Echoes of the collapse'}</h2><p class="wait-label"><i></i> WAIT MODE <span>Choose at your pace · Enemies advance during actions</span></p></div><div class="enemy-labels">${b.enemies.map(en=>`<button class="enemy-label ${selectedTarget===en.id?'targeted':''}" data-action="target" data-id="${en.id}" data-enemy="${en.id}"><span>${en.name}</span><div class="bar health"><i></i></div><div class="bar atb"><i></i></div><small class="enemy-hp"></small><small class="enemy-intent" data-intent="${en.id}">${esc(en.intent?.name||'')}</small><small data-status="${en.id}">${en.statuses?.map(x=>x.name||x.id||x).join(' · ')||''}</small></button>`).join('')}</div><div class="battle-log" id="battle-log"></div><div class="battle-bottom"><div class="combat-party">${heroes().map((h,i)=>heroCard(h,i,true)).join('')}</div><section class="command-panel" id="command-panel">${commandHTML()}</section></div></div>`;}
function commandHTML(){const h=heroes().find(h=>h.id===selectedHero)||heroes()[0],actions=getActions(),combos=game.getCombos();const ready=h.hp>0&&h.atb>=100;
 if(selectedAction){const ally=selectedAction.target==='ally',targets=ally?heroes():game.state.battle.enemies;return `<div class="command-heading"><span class="eyebrow">${h.name} / SELECT ${ally?'ALLY':'TARGET'}</span><button class="text-button" data-action="cancel-action">← Back</button></div><div class="target-layout"><div><h3>${selectedAction.name}</h3><p>${esc(selectedAction.description)}</p>${selectedAction.radius?`<small class="cyan">Area radius ${selectedAction.radius}m · nearby enemies are hit together</small>`:''}</div><div class="target-list">${targets.filter(t=>t.hp>0||['item-medkit','rewind'].includes(selectedAction.id)).map(t=>`<button data-action="target" data-id="${t.id}" class="${selectedTarget===t.id?'active':''}">${esc(t.name)} <small>${Math.ceil(t.hp)} HP</small></button>`).join('')}</div><button class="primary execute" data-action="execute" ${!selectedTarget?'disabled':''}>Execute <span>↗</span></button></div>`;}
 const categories=['Attack','Techniques','Combos','Items'];let shown=actions.filter(a=>battleCategory==='Attack'?['attack','defend'].includes(a.id):battleCategory==='Items'?a.id.startsWith('item-'):battleCategory==='Techniques'?!a.id.startsWith('item-')&&!['attack','defend','aeon-sunder'].includes(a.id)&&!a.id.startsWith('combo-'):false);if(battleCategory==='Combos')shown=combos;
 return `<div class="command-heading"><span class="eyebrow">${h.name} <span class="${ready?'cyan':''}">/ ${ready?'READY TO ACT':h.hp<=0?'INCAPACITATED':'GATHERING MOMENTUM'}</span></span><span class="energy-counter">${Math.floor(h.mp)} EN</span></div><div class="command-tabs">${categories.map(c=>`<button data-action="category" data-id="${c}" class="${c===battleCategory?'active':''}">${c}</button>`).join('')}</div><div class="action-grid">${shown.map(a=>`<button class="action-tile ${a.id==='aeon-sunder'?'sunder':''}" data-action="command" data-id="${a.id}" ${!actionAvailable(a)?'disabled':''} title="${esc(a.reason||a.description)}"><div><strong>${esc(a.name)}</strong><span>${typeof a.cost==='object'?Object.values(a.cost).join(' / '):a.cost||0} EN${a.participants?' EACH':''}</span></div><small>${esc(!actionAvailable(a)&&a.reason?a.reason:a.description)}</small></button>`).join('')||'<p class="muted">No techniques available.</p>'}</div>`;
}
function mapSVG(mini=false){const s=game.state;return `<svg class="valley-map ${mini?'mini':''}" viewBox="0 0 54 57" role="img" aria-label="Map of Meridian Valley"><defs><linearGradient id="mapwater" x2="1" y2="1"><stop stop-color="#28474b"/><stop offset="1" stop-color="#182d35"/></linearGradient></defs><path class="map-outline" d="M11 2L39 3 50 11 49 24 52 34 45 51 31 55 12 52 3 36 5 18Z"/><path class="map-water" d="M0 32C9 32 12 34 19 32S29 34 35 34 45 38 54 35L54 39C45 42 38 37 32 37S22 35 17 36 7 35 0 35Z"/><g class="contours"><path d="M8 13Q16 7 20 18T13 40M6 16Q13 9 17 20T9 38M41 7Q47 15 45 22M7 46Q18 40 25 48T44 48M9 48Q17 43 23 50"/></g><path class="map-path" d="M27 54L27 47 27 42 28 36 27 29 28 21 27 13 27 6M27 42L20 41 14 36 13 27 15 21 19 14 27 9M27 41L35 40 41 36 44 32 42 26 39 19 39 14 32 9M13 26L9 23 10 18 12 16M15 38L9 37 6 39"/><circle cx="27" cy="8" r="5.5" class="map-ring"/><path class="map-building" d="M19 46v-4h4v4zM31 49v-5h5v5zM22 53v-3h4v3z"/>${LANDMARKS.filter(l=>!mini||['boss','relay-west','relay-east','beacon'].includes(l.id)).map(l=>{const done=s.cleared.includes(l.id)||(l.id==='relay-west'&&s.flags.relayWest)||(l.id==='relay-east'&&s.flags.relayEast);return`<g class="map-marker ${done?'done':''}" ${mini?'':`data-action="waypoint" data-id="${l.id}" tabindex="0" role="button" aria-label="Travel to ${esc(l.name)}"`}><circle cx="${l.x+27}" cy="${l.z+31}" r="${mini?.8:1.15}"/><title>${esc(l.name)}</title>${!mini?`<text x="${l.x+27}" y="${l.z+34}">${esc(l.name)}</text>`:''}</g>`;}).join('')}<circle class="player-halo" cx="${s.player.x+27}" cy="${s.player.z+31}" r="2"/><circle id="${mini?'map-player':'full-map-player'}" class="player-dot" cx="${s.player.x+27}" cy="${s.player.z+31}" r=".8"/><text class="north" x="48" y="8">N</text></svg>`;}
function menuHTML(){const tabs=['Map','Party','Inventory','Skills','Settlement','Quests','Save','Settings'];return `<div class="modal-backdrop"><section class="journal panel" role="dialog" aria-modal="true" aria-label="Crew journal"><header class="journal-header"><div><p class="eyebrow">CHRONOFORGE / FIELD JOURNAL</p><h2>${menuTab==='Map'?'A world worth saving.':menuTab==='Party'?'Three against the silence.':menuTab==='Skills'?'Become something more.':menuTab==='Settlement'?'A place to begin again.':menuTab==='Inventory'?'What the old world left.':menuTab==='Quests'?'Promises to keep.':menuTab==='Save'?'Keep this moment.':'Make yourself at home.'}</h2></div><button class="close-button" data-action="close" aria-label="Close journal">× <kbd>ESC</kbd></button></header><nav class="journal-tabs">${tabs.map(t=>`<button data-action="tab" data-tab="${t}" class="${t===menuTab?'active':''}">${t}</button>`).join('')}</nav><div class="journal-content">${{Map:mapMenu,Party:partyMenu,Inventory:inventoryMenu,Skills:skillsMenu,Settlement:settlementMenu,Quests:questsMenu,Save:saveMenu,Settings:settingsMenu}[menuTab]()}</div><footer class="journal-footer"><span>BELLWETHER · ${game.state.settlement.beacon?'RECLAIMER':'SURVIVOR'} TIER</span><span>${Math.floor((game.state.playtime||0)/60)} MINUTES INTO TOMORROW</span></footer></section></div>`;}
function mapMenu(){const s=game.state;return `<div class="map-layout"><div class="large-map">${mapSVG()}<div class="map-legend"><span><i class="gold-dot"></i> Landmark</span><span><i class="cyan-dot"></i> Restored</span><span><i class="white-dot"></i> Your crew</span></div></div><div class="map-copy"><p class="eyebrow">REGION 01 / EARTH</p><h3>Meridian Valley</h3><p>A thousand sunsets have passed over these ruins. Tonight, one of them might stay.</p><div class="objective-card"><small>CURRENT OBJECTIVE</small><h4>${objective()}</h4></div><p class="map-note">Select a landmark to travel toward it. You can interrupt travel with movement keys.</p><div class="waypoint-list">${LANDMARKS.filter(l=>['mira','beacon','relay-west','relay-east','boss','memory'].includes(l.id)).map(l=>`<button data-action="waypoint" data-id="${l.id}" ${previousMode==='battle'?'disabled':''}><span>◇ ${esc(l.name)}</span><span>↗</span></button>`).join('')}</div></div></div>`;}
function partyMenu(){return `<div class="party-grid">${heroes().map(h=>{const d=heroDef(h.id),st=game.getStats(h.id);return `<article class="party-sheet" style="--hero:${d?.color}"><div class="party-art"><img src="${portrait(h.id)}" alt="${h.name} portrait"/><span class="party-level">LEVEL ${h.level}</span></div><div class="party-info"><p class="eyebrow">${esc(d?.role||cap(h.id))}</p><h3>${h.name}</h3><p>${esc(d?.description||'A member of the Bellwether crew.')}</p><div class="stat-grid">${['attack','defense','speed','maxHp','maxMp'].map(k=>`<span>${icons[k]} ${k==='maxHp'?'Max HP':k==='maxMp'?'Max EN':cap(k)}<b>${st[k]}</b></span>`).join('')}<span>✧ Skill points<b>${h.sp}</b></span></div><div class="equipment-list">${['weapon','armor','accessory'].map(slot=>`<div><small>${cap(slot)}</small><span>${ITEMS[h.equipment[slot]]?.name||'— Empty —'}</span></div>`).join('')}</div><button class="secondary full" data-action="tab" data-tab="Inventory">Manage equipment ↗</button></div></article>`;}).join('')}</div>`;}
function inventoryMenu(){const s=game.state;const entries=Object.entries(s.inventory).filter(([,v])=>v>0);if(!selectedItem||!s.inventory[selectedItem])selectedItem=entries[0]?.[0];const item=ITEMS[selectedItem];return `<div class="inventory-layout"><div class="inventory-list"><div class="section-label">SALVAGED & CARRIED <span>${entries.length} TYPES</span></div>${entries.map(([id,count])=>{const it=ITEMS[id];return `<button class="inventory-item ${id===selectedItem?'active':''}" data-action="item" data-id="${id}"><span class="item-symbol">${it?.slot==='weapon'?'╱':it?.slot==='armor'?'⬡':it?.slot==='accessory'?'◈':'✚'}</span><span><strong>${esc(it?.name||cap(id))}</strong><small>${cap(it?.slot||'Supply')}</small></span><b>×${count}</b></button>`;}).join('')}</div><div class="item-detail">${item?`<p class="eyebrow">${cap(item.slot||'FIELD SUPPLY')}</p><h3>${item.name}</h3><p>${item.description}</p><div class="item-stats">${Object.entries(item.stats||{}).map(([k,v])=>`<span>${cap(k.replace('max','Max '))} <b>+${v}</b></span>`).join('')}</div>${item.slot&&item.slot!=='consumable'?`<h4>Equip to crew</h4><p class="muted small">The numbers below show the change from current equipment.</p><div class="equip-options">${heroes().map(h=>{const allowed=!item.hero||item.hero===h.id||Array.isArray(item.hero)&&item.hero.includes(h.id);const equipped=h.equipment[item.slot]===selectedItem;const current=ITEMS[h.equipment[item.slot]];const stats=new Set([...Object.keys(item.stats||{}),...Object.keys(current?.stats||{})]);return `<div class="equip-row"><img src="${portrait(h.id)}" alt=""/><div><strong>${h.name}</strong><small>${current?.name||'Empty slot'}</small><div class="comparison">${[...stats].map(k=>{const d=(item.stats?.[k]||0)-(current?.stats?.[k]||0);return `<span class="${d<0?'negative':'positive'}">${cap(k)} ${d>=0?'+':''}${d}</span>`;}).join('')}</div></div><button class="secondary" data-action="equip" data-hero="${h.id}" ${!allowed||equipped||previousMode==='battle'?'disabled':''}>${equipped?'Equipped':!allowed?'Incompatible':'Equip'}</button></div>`;}).join('')}</div>`:`<div class="info-box">Use a supply on a crew member below, or through Items in battle. Medkits can revive a fallen ally.</div><div class="button-row">${heroes().map(h=>`<button class="secondary" data-action="use-item" data-hero="${h.id}" ${previousMode==='battle'?'disabled':''}>Use on ${h.name}</button>`).join('')}</div><button class="secondary" data-action="rest" ${previousMode==='battle'?'disabled':''}>Rest in Bellwether · 1 food</button>`}`:'<h3>A little room for possibility.</h3><p>Explore the valley to find useful equipment and supplies.</p>'}</div></div>`;}
function skillsMenu(){return `<div class="skill-intro"><p>Each level grants skill points. Choose a path; the second skill in each branch builds on the first.</p><span>PASSIVES APPLY IMMEDIATELY</span></div><div class="skill-columns">${heroes().map(h=>`<section class="skill-column" style="--hero:${heroDef(h.id)?.color}"><div class="skill-hero"><img src="${portrait(h.id)}" alt=""/><div><h3>${h.name}</h3><p>${h.sp} SKILL POINT${h.sp===1?'':'S'} AVAILABLE</p></div></div>${(SKILLS[h.id]||[]).map(sk=>{const learned=h.skills.includes(sk.id);const prereqs=Array.isArray(sk.requires)?sk.requires:sk.requires?[sk.requires]:[];const missing=prereqs.some(id=>!h.skills.includes(id));return `<button class="skill-node ${learned?'learned':''} ${missing?'locked':''}" data-action="learn" data-id="${sk.id}" data-hero="${h.id}" ${learned||missing||h.sp<(sk.cost||1)||previousMode==='battle'?'disabled':''}><div class="skill-node-top"><span>${esc(sk.branch||'DISCIPLINE')}</span><b>${learned?'✓ LEARNED':`${sk.cost||1} SP`}</b></div><h4>${sk.name}</h4><p>${sk.description}</p>${missing?`<small>Requires ${prereqs.map(id=>(SKILLS[h.id]||[]).find(x=>x.id===id)?.name||cap(id)).join(', ')}</small>`:''}</button>`;}).join('')}</section>`).join('')}</div>`;}
function settlementMenu(){const s=game.state;return `<div class="settlement-layout"><div class="beacon-art ${s.settlement.beacon?'lit':''}"><div class="beacon-sun"></div><div class="beacon-ring"></div><div class="beacon-tower"></div><div class="beacon-base"></div><span>BELLWETHER / ${s.settlement.beacon?'LIGHT RESTORED':'AWAITING A SPARK'}</span></div><div class="settlement-copy"><p class="eyebrow">${s.settlement.beacon?'RECLAIMER TIER':'SURVIVOR TIER'} / CIVILIZATION BEGINS HERE</p><h3>The hearth beacon</h3><p>${s.settlement.beacon?'For the first time in a generation, Bellwether glows after sunset. The workshop hums. Children stay out a little longer. Tomorrow feels less like a promise.':'A patched-together solar hearth. A little ore, a little stored energy, and the settlement could have more than a campfire to gather around.'}</p><div class="resource-cards">${Object.entries(s.resources).map(([k,v])=>`<div><i>${icons[k]}</i><strong>${v}</strong><small>${cap(k)}</small></div>`).join('')}</div><div class="info-box"><strong>Light that follows you.</strong><p>${s.settlement.beacon?'Stage I: +20 max HP, +8 max energy, and +8 energy each battle. Stage II: +5 attack, +2 defense, and +20 starting ATB. Mira offers a hot meal for 1 food.':'Construction fully restores the crew and grants +20 max HP, +8 max energy, and +8 energy each battle. The second stage grants +5 attack, +2 defense, and +20 starting ATB.'}</p></div><button class="primary full" data-action="build" ${previousMode==='battle'||s.settlement.beacon>=2?'disabled':''}>${s.settlement.beacon>=2?'Beacon fully upgraded':s.settlement.beacon?'Upgrade the hearth beacon':'Construct the hearth beacon'} <span>ϟ</span></button><p class="cost-note" id="build-cost">${game.getBuildCost()?Object.entries(game.getBuildCost()).filter(([,v])=>v).map(([k,v])=>`${v} ${k}`).join(' · '):'Maximum level · Your settlement is thriving.'}</p><button class="text-button" data-action="rest" ${previousMode==='battle'?'disabled':''}>Share a meal · Restore crew · 1 food</button></div></div>`;}
function questsMenu(){const s=game.state;const q=[{title:'The last light',label:'MAIN CHAPTER',text:'Restore the Meridian array and bring dependable power to Bellwether.',steps:[['Clear the broken causeway',s.cleared.includes('causeway')],['Restore the Glass Garden relay',s.flags.relayWest],['Restore the Sunken Archive relay',s.flags.relayEast],['Defeat the Pale Warden',s.cleared.includes('boss')],['Give the valley a tomorrow',s.flags.bossDefeated||s.cleared.includes('boss')]]},{title:'A place to begin again',label:'SETTLEMENT',text:'Salvage enough material to construct the hearth beacon. Bellwether’s future begins with something small.',steps:[['Construct the hearth beacon',s.settlement.beacon>=1],['Upgrade it to a living workshop',s.settlement.beacon>=2]]},{title:'Someone was here',label:'DISCOVERY',text:'A memory waits in the western ruins. Find the old recording and listen to what survived.',steps:[['Discover the memory beyond the Glass Garden',s.flags.memory||s.flags.memoryFound]]}];return `<div class="quest-grid">${q.map((q,i)=>`<article class="quest-card"><span class="quest-number">0${i+1}</span><p class="eyebrow">${q.label}</p><h3>${q.title}</h3><p>${q.text}</p><ul>${q.steps.map(([text,done])=>`<li class="${done?'complete':''}"><span>${done?'✓':'◇'}</span>${text}</li>`).join('')}</ul></article>`).join('')}</div>`;}
function saveMenu(){let saved;try{saved=JSON.parse(localStorage.getItem(SAVE_KEY));}catch{}return `<div class="save-layout"><div><p class="eyebrow">LOCAL JOURNEY / SLOT 01</p><h3>Your place in the dusk.</h3><p>Progress is stored in this browser on this device. Victory and restored landmarks also save your journey.</p><div class="save-slot"><span class="save-icon">◈</span><div><strong>${saved?'The Last Light of Bellwether':'An unwritten tomorrow'}</strong><p>${saved?'A saved journey is available.':'Begin your story, then preserve it here.'}</p></div></div><div class="button-row"><button class="primary" data-action="save" ${previousMode==='battle'?'disabled':''}>Save journey ↓</button><button class="secondary" data-action="load" ${!saved||previousMode==='battle'?'disabled':''}>Load journey ↗</button></div><p class="small muted">Battle retry preserves your setup from before the encounter. Manual saving is available while exploring.</p></div><div class="save-aside"><span>“</span><p>We can’t bring yesterday back.<br>But we can keep a little of it<br>for tomorrow.</p><small>VEX / FIELD NOTES</small><button class="text-button" data-action="title" ${previousMode==='battle'?'disabled':''}>Save & return to title</button></div></div>`;}
function settingsMenu(){const s=game.state.settings;return `<div class="settings-layout"><div><p class="eyebrow">SOUND & PERFORMANCE</p><label class="setting"><span><strong>Music & ambience</strong><small>An original generative score</small></span><input aria-label="Music volume" type="range" min="0" max="1" step=".05" value="${s.music}" data-setting="music"/></label><label class="setting"><span><strong>Sound effects</strong><small>Combat, crew, and the world</small></span><input aria-label="Sound effects volume" type="range" min="0" max="1" step=".05" value="${s.sfx}" data-setting="sfx"/></label><label class="setting"><span><strong>Visual quality</strong><small>Lower settings reduce resolution and shadows</small></span><select aria-label="Visual quality" data-setting="quality">${['high','medium','low'].map(x=>`<option value="${x}" ${s.quality===x?'selected':''}>${cap(x)}</option>`).join('')}</select></label><label class="setting"><span><strong>Battle speed</strong><small>Changes gauge pacing; Wait mode remains active</small></span><select aria-label="Battle speed" data-setting="battleSpeed">${[[.75,'Relaxed'],[1,'Balanced'],[1.4,'Brisk']].map(([v,l])=>`<option value="${v}" ${s.battleSpeed===v?'selected':''}>${l}</option>`).join('')}</select></label></div><div class="controls-sheet"><p class="eyebrow">FIELD CONTROLS</p>${[['W A S D / ↑ ↓ ← →','Move the crew'],['Mouse / Tap','Travel to a destination'],['Shift','Run'],['E / Space','Interact or confirm'],['Esc','Journal / Back'],['M / I / J','Map / Inventory / Quests'],['1 / 2 / 3','Select hero in battle'],['Tab','Cycle battle heroes']].map(([k,t])=>`<div><kbd>${k}</kbd><span>${t}</span></div>`).join('')}<button class="secondary full" data-action="help">Read the field guide ↗</button></div></div>`;}
function dialogueHTML(){const line=dialogue[0],id=line.speaker.toLowerCase();return `<div class="dialogue-wrap"><section class="dialogue panel" role="dialog" aria-label="Conversation">${['kaida','vex','rune'].includes(id)?`<div class="dialogue-portrait"><img src="${portrait(id)}" alt=""/></div>`:'<div class="dialogue-sigil">✧</div>'}<div class="dialogue-copy"><p class="eyebrow">${esc(line.speaker)}</p><p class="dialogue-text">${esc(line.text)}</p><button class="text-button" data-action="advance">${dialogue.length>1?'Continue':'Let’s go'} <kbd>SPACE</kbd> <span>↗</span></button></div></section></div>`;}
function victoryHTML(){const r=game.state.lastReward||{};return `<div class="result-backdrop"><section class="result panel"><p class="eyebrow">THE VALLEY GROWS QUIETER</p><div class="result-sigil">✧</div><h2>Another dawn earned.</h2><p>The crew gathers what can still be useful.</p><div class="reward-row">${r.xp?`<span><strong>+${r.xp}</strong> CREW XP</span>`:''}${Object.entries({food:r.food,ore:r.ore,energy:r.energy,renown:r.renown}).filter(([,v])=>v).map(([k,v])=>`<span><strong>+${v}</strong> ${cap(k)}</span>`).join('')}</div><p class="reward-items">${Array.isArray(r.items)?r.items.map(i=>ITEMS[typeof i==='string'?i:i.id]?.name||cap(i.id||i)).join(' · '):Object.keys(r.items||{}).map(i=>ITEMS[i]?.name||cap(i)).join(' · ')}</p><div class="victory-party">${heroes().map(h=>`<div><img src="${portrait(h.id)}" alt=""/><strong>${h.name}</strong><span>LEVEL ${h.level} · ${h.sp} SP</span></div>`).join('')}</div><button class="primary full" data-action="victory">Continue the journey <span>↗</span></button><p class="small muted">Open the journal to equip salvage and spend skill points.</p></section></div>`;}
function defeatHTML(){return `<div class="result-backdrop"><section class="result panel defeat"><p class="eyebrow">THE LIGHT HAS NOT LEFT YOU</p><div class="result-sigil">◇</div><h2>One more chance.</h2><p>The crew falls. Somewhere, Vex catches a second before it can disappear.</p><blockquote>“We are not finished with this moment.”</blockquote><button class="primary full" data-action="retry">Rewind the encounter <span>↶</span></button><p class="small muted">Your crew and supplies return to their pre-battle state.</p></section></div>`;}
function endingHTML(){const s=game.state;return `<div class="ending-screen"><div class="ending-glow"></div><div class="ending-copy"><p class="eyebrow">CHAPTER I / COMPLETE</p><img class="ending-emblem" src="${base}art/emblem.svg" alt=""/><h1>And the light<br><em>came home.</em></h1><p>Across the valley, windows glow for the first time in three hundred years. Bellwether is small. Its people are few.<br>But tonight, the dark has somewhere to end.</p><div class="ending-quote"><span>KAIDA</span> “Think they saved us dinner?”<br><span>RUNE</span> “I specifically requested it.”<br><span>VEX</span> “Civilization. At last.”</div><div class="ending-stats"><span><strong>${s.cleared.length}</strong> ENCOUNTERS WON</span><span><strong>${s.settlement.beacon>=2?'RECLAIMER':'SURVIVOR'}</strong> SETTLEMENT TIER</span><span><strong>${s.flags.memory||s.flags.memoryFound?'REMEMBERED':'UNDISCOVERED'}</strong> THE OLD WORLD</span></div><button class="primary" data-action="ending-explore">Return to Bellwether <span>↗</span></button><p class="ending-note">Thank you for bringing a little of tomorrow back.</p></div></div>`;}

function updateAim(){if(!aimRing)return;const b=game.state.battle;const action=selectedAction;const target=b?.enemies.find(e=>e.id===selectedTarget);const visible=game.state.mode==='battle'&&action?.target==='enemy'&&target?.hp>0;aimRing.visible=!!visible;if(!visible)return;const radius=action.radius||.8;if(radius!==aimRadius){aimRadius=radius;aimRing.geometry.dispose();aimRing.geometry=new THREE.RingGeometry(Math.max(.2,radius-.065),radius,72);}aimRing.position.set(b.origin.x+target.x,b.id==='causeway'?.415:.16,b.origin.z+target.z);aimRing.material.opacity=.44+Math.sin(elapsed*4)*.12;}
