import { chromium } from 'playwright';
import fs from 'node:fs/promises';
const dir=new URL('./',import.meta.url).pathname;
const prefix=process.env.CRITIC_PASS||'critic';
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});
await page.routeWebSocket('**/*',socket=>{socket.send(JSON.stringify({type:'connected'}));socket.onMessage(()=>{});});
const messages=[];page.on('console',msg=>{if(['error','warning'].includes(msg.type()))messages.push({kind:msg.type(),text:msg.text()});});page.on('pageerror',error=>messages.push({kind:'pageerror',text:String(error)}));
await page.goto('http://127.0.0.1:4321/?test=1',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__ECHO_READY__,{timeout:20000});
const capture=async name=>{name=name.replace(/^critic/,prefix);await page.screenshot({path:dir+name+'.png'});return {name,time:Date.now(),snapshot:await page.evaluate(()=>window.__ECHO__.snapshot())};};
const shots=[];await page.evaluate(()=>window.__ECHO__.preset('world'));await page.waitForTimeout(500);shots.push(await capture('critic-world-initial'));
await page.keyboard.down('ArrowDown');await page.waitForTimeout(180);shots.push(await capture('critic-world-walk-01'));await page.waitForTimeout(100);shots.push(await capture('critic-world-walk-02'));await page.keyboard.up('ArrowDown');
await page.keyboard.press('Escape');shots.push(await capture('critic-atlas-map'));await page.keyboard.press('Escape');
await page.evaluate(()=>window.__ECHO__.preset('battle'));await page.waitForTimeout(300);shots.push(await capture('critic-battle-initial'));
await page.waitForFunction(()=>window.__ECHO__.game.battle?.readyQueue.length>0);
await page.keyboard.press('Space');shots.push(await capture('critic-battle-command'));await page.keyboard.press('Enter');shots.push(await capture('critic-battle-target'));await page.keyboard.press('Enter');
for(let i=0;i<11;i++){await page.waitForTimeout(i===0?20:90);shots.push(await capture('critic-battle-action-'+String(i).padStart(2,'0')));}
await page.waitForTimeout(500);shots.push(await capture('critic-battle-after'));
await fs.writeFile(dir+prefix+'-capture-log.json',JSON.stringify({environment:{viewport:[1920,1080],deviceScaleFactor:1,browser:await browser.version()},messages,shots},null,2));await browser.close();console.log(JSON.stringify({count:shots.length,messages,files:shots.map(s=>s.name)}));
