import * as THREE from 'three';
import { Engine, BUDGET, QUALITY_ORDER } from './core/engine.js';
import { bus } from './core/events.js';
import { installModule, moduleReport } from './core/modules.js';
import { SHOTS, applyShot, shotNames } from './core/shots.js';
import { rng, resetStreams, streamNames } from './core/rng.js';
import { DAWN_HOUR } from './core/const.js';
import { CameraRig } from './render/camera.js';
import { buildMaterials } from './render/materials.js';
import { Environment } from './render/environment.js';
import { textureKeys } from './render/textures.js';
import { installWorld } from './world/index.js';
import { installActors } from './actors/index.js';
import { installTraversal } from './traversal/index.js';
import { installPlaces } from './places/index.js';
import { installBattle } from './battle/index.js';
import { installProgression } from './progression/index.js';
import { installSettlement } from './settlement/index.js';
import { installFx } from './fx/index.js';
import { installUI } from './ui/index.js';
import { installAudio } from './audio/index.js';
import { installDevPanel } from './core/devpanel.js';

// ─────────────────────────────────────────────────────────────────────────────
// Boot and main loop. THE one integration point.
//
// Lanes are installed here through fixed seams and never reach into each other.
// Every install goes through `installModule`, so a lane that throws — at install
// or in its per-frame tick — is quarantined and the rest of the game keeps
// rendering. Eleven lanes work this repo in parallel; a broken module blanking
// the screen would block every one of them from taking a screenshot.
//
// SHARED CORE. If you need a new seam here, put it in your report as a
// core-change request. Do not edit this file.
// ─────────────────────────────────────────────────────────────────────────────

const params = new URLSearchParams(location.search);
const num = (k, d) => { const v = parseFloat(params.get(k)); return Number.isFinite(v) ? v : d; };

// Quality precedence: an explicit ?quality= wins (tools/shot.mjs passes it and
// defaults to ultra for still captures), then whatever the human last set on
// the dev-panel lever, then 'high'. Gameplay probes pass no ?quality, so they
// measure what the human is actually looking at — see CONCEPT.md.
let savedQuality = null;
try { savedQuality = localStorage.getItem('dawn.quality'); } catch { /* private mode */ }
const engine = new Engine({ quality: params.get('quality') || savedQuality || 'high' });
engine.bus = bus;
const rig = new CameraRig();
const materials = buildMaterials(engine);
const env = new Environment(engine);
engine.buildPost();

/** The context handed to every lane. ADD fields; never remove one. */
const ctx = {
  THREE, engine,
  scene: engine.scene,
  camera: engine.camera,
  rig,                     // CameraRig — locked 55° pitch, damped follow
  env,                     // Environment — sky, sun, IBL, fog, setTime(hour)
  materials,               // shared material kit
  bus,                     // the only channel between lanes
  rng,                     // rng('lane.stream') — never Math.random()
  registerShot: (name, fn) => { SHOTS[name] = fn; return name; },
  get time() { return simTime; },
  get dt() { return engine.dt; },
  get hour() { return env.hour; },
  state: {},               // gameplay state the HUD reads; lanes publish onto it
  shotNames,               // for the dev panel's shot picker
  dev: null,               // DevPanel — set just below; lanes register controls onto it
};

/* ── dev panel ───────────────────────────────────────────────────────────────
   For the human, not for agents (agents use tools/*.mjs). Hidden unless ?dev=1
   or backtick, so it never lands in a review screenshot. Lanes add their own
   controls with ctx.dev.register(...) — do not edit devpanel.js to add one. */
ctx.dev = installDevPanel(ctx, { visible: params.get('dev') === '1' });

/* Quality lever — five notches, cheapest first. This is the graphics-cost
   instrument: sweep it against the Frame/Draws readouts already in the panel
   and watch what each look decision actually costs. It is registered from here
   rather than inside devpanel.js because main.js owns the engine.
   The environment re-allocates its shadow map off the same event. */
bus.on('engine:quality', ({ q }) => env?.applyQuality(q));
ctx.dev?.register({
  group: 'quality', label: 'Level', type: 'select',
  options: () => [...QUALITY_ORDER],
  get: () => engine.qualityName,
  set: (v) => engine.setQuality(v),
});
ctx.dev?.register({
  group: 'quality', label: 'Scale', type: 'readout',
  get: () => `${engine.renderScale.toFixed(2)}x  sm${engine.q.shadowMap}`,
});

/* ── lanes ───────────────────────────────────────────────────────────────── */
const modules = {};
function install(name, factory) {
  const m = installModule(name, factory, ctx);
  modules[name] = m;
  ctx[name] = m.api;
  return m;
}

install('world', installWorld);
install('actors', installActors);
install('fx', installFx);
install('audio', installAudio);
install('ui', installUI);
install('traversal', installTraversal);
install('places', installPlaces);
install('battle', installBattle);
install('progression', installProgression);
install('settlement', installSettlement);

const focus = () => ctx.world?.focus || new THREE.Vector3();

/* Where the shadow map should be centred.
   NOT the camera position — the shadow camera covers ±52 m, and a review shot
   sits 130 m back and 60 m up, which puts the whole subject outside the map and
   silently drops every prop shadow while terrain self-shadowing keeps working.
   That combination reads as "props are pasted on" and is exactly defect 3.
   So: cast the camera's view direction onto the ground plane and centre there. */
const _fwd = new THREE.Vector3();
const _sf = new THREE.Vector3();
function shadowFocus() {
  const f = focus();
  if (!shotMode) return rig.target;
  engine.camera.getWorldDirection(_fwd);
  const cam = engine.camera.position;
  const denom = _fwd.y;
  // Looking level or up: nothing to aim at, so keep the world focus.
  if (denom > -0.05) return f;
  const t = THREE.MathUtils.clamp((f.y - cam.y) / denom, 0, 400);
  _sf.copy(cam).addScaledVector(_fwd, t);
  const half = (ctx.world?.size ?? 240) * 0.5;
  _sf.x = THREE.MathUtils.clamp(_sf.x, -half, half);
  _sf.z = THREE.MathUtils.clamp(_sf.z, -half, half);
  _sf.y = ctx.world?.heightAt ? ctx.world.heightAt(_sf.x, _sf.z) : f.y;
  return _sf;
}

/* ── deterministic stepping ──────────────────────────────────────────────────
   The sim is fixed-step at 120 Hz; frames are not. Rendering the raw variable
   step is how a following camera picks up a stutter that no profiler explains.
   Input is sampled per FRAME, outside the step, because input is a poll of
   devices and not a quantity the sim integrates — and because a paused game
   that stops reading the keyboard can never be un-paused.                    */
const FIXED = 1 / 120;
let acc = 0;
let simTime = 0;
let running = true;
let shotMode = null;

function step(dt) {
  for (const k of ['world', 'traversal', 'actors', 'places', 'battle', 'progression', 'settlement']) {
    modules[k].tick(dt, ctx);
  }
  simTime += dt;
}

function updateScene(dt, moveCamera = true) {
  if (moveCamera) rig.follow(engine.camera, focus(), dt);
  env.update(dt, rig.target);
  modules.fx.tick(dt, ctx);
  modules.audio.tick(dt, ctx);
  modules.ui.tick(dt, ctx);
  ctx.dev?.update();
}

/** Fast-forward the sim to an absolute time without rendering. */
function seekTo(t) {
  const target = Math.max(0, t);
  let guard = 0;
  while (simTime < target - FIXED * 0.5 && guard++ < 500000) step(FIXED);
  updateScene(FIXED);
  return simTime;
}

function frame() {
  requestAnimationFrame(frame);
  const dt = engine.tick();

  if (running && !shotMode) {
    acc += dt;
    let guard = 0;
    while (acc >= FIXED && guard++ < 8) { step(FIXED); acc -= FIXED; }
    updateScene(dt, true);
  } else if (shotMode) {
    applyShot(shotMode, ctx);
    env.update(dt, shadowFocus());
    modules.ui.tick(dt, ctx);
  } else {
    modules.ui.tick(dt, ctx);
  }
  engine.render();
}

/* ── the debug API ───────────────────────────────────────────────────────────
   Every tool in tools/ drives the game through this and nothing else. Keep it
   stable: a rename here breaks thirteen probes at once.                      */
const api = {
  ctx, engine, env, rig, THREE,
  ready: false,
  version: '0.1.0-phase0',
  get shots() { return shotNames(); },
  /** Current named shot, or null. The dev panel hides itself while this is set. */
  get shot() { return shotMode; },
  get modules() { return modules; },

  pause() { running = false; },
  resume() { running = true; },

  /** Fast-forward the fixed-step sim to an absolute time, in seconds. */
  seek(t) { return seekTo(t); },

  /** Advance the sim by N fixed steps. The frame-accurate stepping a probe
   *  needs — never `seek(now + n/120)`, which accumulates float error. */
  step(n = 1) {
    for (let i = 0; i < n; i++) step(FIXED);
    updateScene(FIXED, !shotMode);
    return simTime;
  },

  /** Name a review camera, or null to hand control back to the rig. */
  setShot(name) {
    shotMode = name || null;
    if (shotMode && !SHOTS[shotMode]) { console.warn('[shot] unknown', shotMode); }
    if (shotMode) { running = false; applyShot(shotMode, ctx); }
    else { running = true; rig.reset(focus()); }
    return shotMode;
  },

  /** Hour of day, 0–24. Drives sun, sky, IBL, fog and shadow direction. */
  setTime(hour, opts) { env.setTime(hour, opts); bus.emit('time:changed', { hour: env.hour }); return env.hour; },

  /** Live post knobs. `__DAWN__.post({ exposure: 0.8 })`. */
  post(patch = {}) {
    const p = engine.post;
    if (!p) return null;
    if (patch.exposure != null) p.params.exposure = patch.exposure;
    if (patch.contrast != null) p.params.contrast = patch.contrast;
    if (patch.saturation != null) p.params.saturation = patch.saturation;
    if (patch.vignette != null) p.params.vignette = patch.vignette;
    if (patch.grain != null) p.params.grain = patch.grain;
    if (patch.split != null) p.params.split = patch.split;
    if (patch.bloom) Object.assign(p.params.bloom, patch.bloom);
    if (patch.enable) for (const [k, v] of Object.entries(patch.enable)) p.setEnabled(k, v);
    return { ...p.params, enabled: { ...p.enabled } };
  },

  /** Linear-light histogram. Measure the exposure; do not argue about it. */
  probe(opts) { return engine.post ? engine.post.probe(opts) : null; },

  /** Frame cost against the hard budget, plus per-lane health. */
  stats() {
    const info = engine.renderer.info;
    const s = {
      fps: 1000 / engine.avgFrameMs,
      frameMs: engine.avgFrameMs,
      calls: info.render.calls,
      tris: info.render.triangles,
      programs: info.programs?.length ?? 0,
      textures: info.memory.textures,
      geometries: info.memory.geometries,
      megapixels: +engine.megapixels.toFixed(2),
      quality: engine.qualityName,
      hour: +env.hour.toFixed(2),
      sunElevation: +env.elevation.toFixed(1),
      simTime: +simTime.toFixed(3),
      cameraLocked: rig.assertLocked(),
      modules: moduleReport(modules),
    };
    s.budget = {
      frameMs: { value: +s.frameMs.toFixed(2), limit: BUDGET.frameMs, ok: s.frameMs <= BUDGET.frameMs },
      calls: { value: s.calls, limit: BUDGET.drawCalls, ok: s.calls <= BUDGET.drawCalls },
      tris: { value: s.tris, limit: BUDGET.triangles, ok: s.tris <= BUDGET.triangles },
    };
    s.budget.ok = s.budget.frameMs.ok && s.budget.calls.ok && s.budget.tris.ok;
    return s;
  },

  /** Determinism surface — `digest.mjs` hashes these. */
  digest() { return { streams: streamNames(), textures: textureKeys(), seed: 'chronoforge-dawn' }; },
  reseed() { resetStreams(); },

  /* The shared ctx, for tools that must BUILD a scene rather than photograph one.
     The Encounter Framing POC stages primitives on real terrain and measures
     occlusion during the push-in; post/probe/stats cannot do that from outside.
     Read-only by convention: this is a probe seam, not a lane's back door into
     shared core. A lane that mutates through it is violating CONTRACT.md §1. */
  get ctx() { return ctx; },

  /* ── not implemented in Phase 0 ──────────────────────────────────────────
     These THROW rather than returning a plausible-looking nothing. A stub that
     silently succeeds is how a probe reports green against a feature that does
     not exist, and that is worse than no probe at all.                      */
  battle() {
    throw new Error('__DAWN__.battle() is not implemented in Phase 0 — the battle lane lands in Tier 4 (Phase 6). See GAME_PLAN.md.');
  },
  teleport() {
    throw new Error('__DAWN__.teleport() is not implemented in Phase 0 — it needs the traversal lane, Tier 2 (Phase 4). See GAME_PLAN.md.');
  },
};
window.__DAWN__ = api;

/* ── go ──────────────────────────────────────────────────────────────────── */
api.setTime(num('hour', num('t', DAWN_HOUR)));
rig.apply(engine.camera, focus());
env.update(FIXED, focus());

// Compile before the first presented frame, so no capture ever photographs a
// half-compiled pipeline.
engine.renderer.compile(engine.scene, engine.camera);

const simSeek = num('sim', 0);
if (simSeek > 0) seekTo(simSeek);
else updateScene(FIXED);

if (params.get('shot')) api.setShot(params.get('shot'));

frame();

// Readiness is signalled only after several PRESENTED frames. Signalling on the
// first would let the harness screenshot through the boot backdrop.
let readyFrames = 0;
(function readyTick() {
  if (++readyFrames >= 6) {
    const boot = document.getElementById('boot');
    if (boot) { boot.style.opacity = '0'; setTimeout(() => boot.remove(), 400); }
    api.ready = true;
    document.body.dataset.ready = '1';
    bus.emit('ready', { version: api.version });
    return;
  }
  requestAnimationFrame(readyTick);
})();
