extends "res://tests/environment_test.gd"
## Only the room/camera boundary is under test; no character or combat suite.
func run(root: DuskCoast) -> void:
	game = root
	process_mode = Node.PROCESS_MODE_ALWAYS
	started = Time.get_ticks_msec()
	game.set_unfocused(false)
	var saved: String = FileAccess.get_sha256("user://accepted_tuning.json") if FileAccess.file_exists("user://accepted_tuning.json") else "absent"
	await seconds(2)
	check(game.actor.is_on_floor() and game.room == null,"Cold launch keeps the coastal arrival and grounded Kaida")
	check(game.site.workshop.error.is_empty(),"Prepared workshop imports through the existing asset consumer")
	check(is_equal_approx(game.actor.walk_speed,float(game.tuning.values.walk_speed)),"Current accepted movement values retained")
	if "--room-restart" in OS.get_cmdline_user_args():
		finish("room_restart")
		return
	var actor_id: int = game.actor.get_instance_id()
	await walk_to(Vector3(-11,0,17),false)
	await walk_to(Vector3(-22.2,0,17),true)
	check(game.at_workshop_door(),"Walk/run reaches the new workshop apron through its visible opening")
	await capture("workshop-exterior")
	set_keys([KEY_W])
	await key(KEY_E)
	await seconds(1)
	check(game.room != null and game.actor.get_instance_id() == actor_id,"Door loads a separate room scene while retaining the same actor")
	check(game.waiting_for_release and game.actor.position.distance_to(DuskWorkshop.SPAWN)<.04,"Held movement cannot carry through the entry transition")
	set_keys([])
	await seconds(.3)
	check(game.actor.is_on_floor() and game.actor.traversal_enabled,"Releasing movement resumes grounded indoor control")
	check(not game.room.rig.third_person and game.actor.camera.projection == Camera3D.PROJECTION_ORTHOGONAL,"First visit opens the closer elevated camera")
	check(not game.room.shell.roof[0].visible and not game.room.shell.front[0].visible,"Cutaway removes the roof and near wall without removing collision")
	await walk_to(Vector3(-1.8,0,.1),false)
	set_keys([KEY_A])
	await seconds(.6)
	set_keys([])
	check(game.actor.position.x > -2.65 and game.actor.is_on_floor(),"Indoor wall stops Kaida with grounded feet")
	await walk_to(Vector3(1.8,0,.1),false)
	await walk_to(Vector3(0,0,.1),false)
	game.perf.begin("room_cutaway_warmed")
	await seconds(5)
	game.perf.begin("room_capture_readback")
	await capture("workshop-cutaway")
	await key(KEY_C)
	await seconds(1)
	check(game.room.rig.third_person and game.actor.camera.projection == Camera3D.PROJECTION_PERSPECTIVE,"C switches the same room to perspective follow")
	check(game.room.shell.roof[0].visible and game.room.shell.front[0].visible,"Third person restores the complete shell")
	game.perf.begin("room_third_warmed")
	await seconds(5)
	game.perf.begin("room_capture_readback_2")
	await capture("workshop-third-person")
	await walk_to(Vector3(0,0,1.55),false)
	await seconds(.4)
	check(game.room.rig.arm.get_hit_length()<1.2 and game.actor.camera.global_position.z<2.3,"Camera spring retracts at the door and stays inside the wall")
	await walk_to(Vector3(0,0,.1),false)
	set_keys([KEY_J])
	await seconds(.45)
	set_keys([])
	await seconds(.15)
	var direction: Vector3 = -game.actor.camera.global_basis.z
	direction.y = 0
	direction = direction.normalized()
	var before: Vector3 = game.actor.position
	set_keys([KEY_W])
	await seconds(.22)
	set_keys([])
	await seconds(.15)
	check((game.actor.position-before).dot(direction)>.35,"Movement follows the deliberately turned third-person camera")
	await key(KEY_C)
	await seconds(1)
	check(absf(game.actor.camera.global_basis.z.x)<.001,"Returning to cutaway restores coastal keyboard axes")
	await key(KEY_ESCAPE)
	var paused: Vector3 = game.actor.position
	set_keys([KEY_W])
	await seconds(.5)
	set_keys([])
	check(game.actor.position == paused and Engine.max_fps == 30,"Pause still freezes indoor movement")
	await key(KEY_ESCAPE)
	await key(KEY_R)
	await seconds(.3)
	check(game.room != null and game.actor.position.distance_to(DuskWorkshop.SPAWN)<.04,"Indoor reset returns to the room entrance")
	await key(KEY_E)
	await seconds(1)
	check(game.room == null and game.actor.position.distance_to(DuskCoastSite.WORKSHOP_RETURN)<.04,"Exit restores the outdoor doorway rather than the original spawn")
	check(game.actor.camera == game.camera and is_equal_approx(game.coastal_audio.ambience.volume_db,-12),"Exit restores the coastal camera and shore mix")
	var node_count: int = int(Performance.get_monitor(Performance.OBJECT_NODE_COUNT))
	for i: int in range(3):
		await key(KEY_E)
		await seconds(.8)
		await key(KEY_E)
		await seconds(.8)
	check(game.room == null and game.transition_count == 8,"Repeated E entry/exit performs one transition per press")
	check(int(Performance.get_monitor(Performance.OBJECT_NODE_COUNT)) <= node_count+2,"Repeated visits release room nodes instead of accumulating them")
	await walk_to(Vector3(-17,0,17),true)
	await walk_to(Vector3(-11,0,13),false)
	check(game.actor.position.distance_to(DuskCoastSite.SPAWN)<.9,"Normal outdoor traversal works after returning from the room")
	check(saved == (FileAccess.get_sha256("user://accepted_tuning.json") if FileAccess.file_exists("user://accepted_tuning.json") else "absent"),"Room and camera choices leave accepted tuning unchanged")
	observations["scope"] = "Focused native room scene, camera, mapped input, collision and transition checks; no full Kaida regression rerun."
	observations["workshop"] = game.site.workshop.asset.descriptor
	finish("room")
