// ─────────────────────────────────────────────────────────────────────────────
// In-game dev panel — a DOM overlay for the HUMAN.
//
// Not to be confused with `tools/*.mjs`, which are headless Playwright probes
// for agents. This is the thing you open in a browser to poke the build: clear
// the fog, jump to a region, force a drop, skip a battle, scrub time of day.
//
// The prototype's dev panel was the most useful thing in that build. This is
// the same idea, wired so it can grow without becoming a god-file.
//
// LANES REGISTER THEIR OWN CONTROLS. Do not edit this file to add a fog toggle:
//
//   ctx.dev.register({
//     group: 'world', label: 'Fog', type: 'toggle',
//     get: () => fog.enabled, set: v => (fog.enabled = v),
//   });
//
// Registration is the seam. A control whose lane is quarantined simply never
// appears, which is also how you find out a lane is down.
//
// HIDDEN BY DEFAULT. `?dev=1` in the URL, or backtick to toggle. The screenshot
// harness must never capture this overlay — a review PNG with a dev panel in it
// is not a review PNG.
// ─────────────────────────────────────────────────────────────────────────────

const CSS = `
#dawn-dev{position:fixed;right:12px;bottom:12px;z-index:99999;width:236px;
  font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;color:#e7e5ff;
  background:rgba(10,7,20,.93);border:1px solid #2a1f52;border-radius:6px;
  box-shadow:0 8px 32px rgba(0,0,0,.6);user-select:none}
#dawn-dev.hidden{display:none}
#dawn-dev h4{margin:0;padding:6px 9px;font-size:10px;letter-spacing:.14em;
  text-transform:uppercase;color:#8a83b8;border-bottom:1px solid #1d1638}
#dawn-dev .grp{padding:7px 9px;border-bottom:1px solid #16112b}
#dawn-dev .grp:last-child{border-bottom:0}
#dawn-dev .gl{font-size:9px;letter-spacing:.14em;text-transform:uppercase;
  color:#ff2dd4;margin-bottom:5px}
#dawn-dev .row{display:flex;align-items:center;justify-content:space-between;
  gap:8px;margin:3px 0;min-height:19px}
#dawn-dev .row span{color:#8a83b8;white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}
#dawn-dev button{background:#1a1236;color:#22e3ff;border:1px solid #2a1f52;
  border-radius:3px;padding:2px 7px;font:inherit;cursor:pointer}
#dawn-dev button:hover{background:#241945;border-color:#3d2f70}
#dawn-dev button.on{background:#22e3ff;border-color:#22e3ff;color:#07060d}
#dawn-dev select{background:#1a1236;color:#e7e5ff;border:1px solid #2a1f52;
  border-radius:3px;font:inherit;padding:1px 3px;max-width:118px}
#dawn-dev input[type=range]{width:110px;accent-color:#ff2dd4}
#dawn-dev .val{color:#ffd23f;min-width:34px;text-align:right}
#dawn-dev .ro{color:#4af2a1}
#dawn-dev .bad{color:#ff4a5a}
#dawn-dev .hint{padding:5px 9px;color:#5a5480;font-size:9px;border-top:1px solid #16112b}
`;

export function installDevPanel(ctx, { visible = false } = {}) {
  if (typeof document === 'undefined') return null;

  const controls = [];
  let root = null, body = null, dirty = true;
  const readouts = [];

  const style = document.createElement('style');
  style.textContent = CSS;
  document.head.appendChild(style);

  root = document.createElement('div');
  root.id = 'dawn-dev';
  root.className = visible ? '' : 'hidden';
  root.innerHTML = '<h4>Dev</h4>';
  body = document.createElement('div');
  root.appendChild(body);
  const hint = document.createElement('div');
  hint.className = 'hint';
  hint.textContent = '` toggle · ?dev=1 to open';
  root.appendChild(hint);
  document.body.appendChild(root);

  function rebuild() {
    dirty = false;
    readouts.length = 0;
    body.textContent = '';
    const groups = [...new Set(controls.map(c => c.group))];
    for (const g of groups) {
      const wrap = document.createElement('div');
      wrap.className = 'grp';
      const gl = document.createElement('div');
      gl.className = 'gl';
      gl.textContent = g;
      wrap.appendChild(gl);
      for (const c of controls.filter(x => x.group === g)) wrap.appendChild(rowFor(c));
      body.appendChild(wrap);
    }
  }

  function rowFor(c) {
    const row = document.createElement('div');
    row.className = 'row';
    const label = document.createElement('span');
    label.textContent = c.label;
    row.appendChild(label);

    if (c.type === 'button') {
      const b = document.createElement('button');
      b.textContent = c.text || 'Run';
      b.onclick = () => { try { c.action(); } catch (e) { console.warn('[dev]', c.label, e); } };
      row.appendChild(b);

    } else if (c.type === 'toggle') {
      const b = document.createElement('button');
      const sync = () => { const v = !!c.get(); b.textContent = v ? 'ON' : 'OFF'; b.className = v ? 'on' : ''; };
      b.onclick = () => { c.set(!c.get()); sync(); };
      sync();
      row.appendChild(b);

    } else if (c.type === 'select') {
      const s = document.createElement('select');
      for (const o of (typeof c.options === 'function' ? c.options() : c.options)) {
        const opt = document.createElement('option');
        opt.value = String(o); opt.textContent = String(o);
        s.appendChild(opt);
      }
      s.value = String(c.get?.() ?? '');
      s.onchange = () => c.set(s.value);
      row.appendChild(s);

    } else if (c.type === 'range') {
      const i = document.createElement('input');
      i.type = 'range';
      i.min = c.min ?? 0; i.max = c.max ?? 1; i.step = c.step ?? 0.01;
      i.value = c.get();
      const v = document.createElement('span');
      v.className = 'val';
      const fmt = () => (v.textContent = c.format ? c.format(+i.value) : (+i.value).toFixed(1));
      i.oninput = () => { c.set(+i.value); fmt(); };
      fmt();
      row.appendChild(i); row.appendChild(v);

    } else if (c.type === 'readout') {
      const v = document.createElement('span');
      v.className = 'ro';
      readouts.push({ el: v, c });
      row.appendChild(v);
    }
    return row;
  }

  const dev = {
    /** Lanes call this. Group headers appear in registration order. */
    register(c) {
      if (!c || !c.label || !c.group) { console.warn('[dev] control needs group + label'); return; }
      controls.push(c);
      dirty = true;
      return dev;
    },
    show(v = true) { root.className = v ? '' : 'hidden'; return dev; },
    toggle() { root.className = root.className ? '' : 'hidden'; return dev; },
    get visible() { return !root.className; },
    /** Called from the main loop. Cheap: only readouts re-read per tick. */
    update() {
      if (dirty) rebuild();
      if (root.className) return;              // hidden — do no work
      for (const { el, c } of readouts) {
        const r = c.get();
        el.textContent = r?.text ?? String(r);
        el.className = r?.ok === false ? 'bad' : 'ro';
      }
    },
  };

  window.addEventListener('keydown', e => {
    if (e.key === '`' && !e.metaKey && !e.ctrlKey) { e.preventDefault(); dev.toggle(); }
  });

  // ── Core controls. Everything here works in Phase 0.
  // Lane-specific controls (fog, region jump, force drop, skip battle) are
  // registered by their own lanes as those lanes land.
  const api = () => window.__DAWN__;

  dev.register({
    group: 'time', label: 'Hour', type: 'range', min: 0, max: 24, step: 0.1,
    get: () => ctx.env?.hour ?? 12,
    set: v => api()?.setTime(v),
    format: v => v.toFixed(1) + 'h',
  });
  for (const [label, h] of [['Dawn', 6.4], ['Noon', 12], ['Dusk', 18.5], ['Night', 21.5]]) {
    dev.register({ group: 'time', label, type: 'button', text: 'Go', action: () => api()?.setTime(h) });
  }

  dev.register({
    group: 'camera', label: 'Shot', type: 'select',
    options: () => ['(free)', ...(ctx.shotNames?.() ?? [])],
    get: () => '(free)',
    set: v => api()?.setShot(v === '(free)' ? null : v),
  });

  dev.register({ group: 'sim', label: 'Pause', type: 'button', text: '||', action: () => api()?.pause() });
  dev.register({ group: 'sim', label: 'Resume', type: 'button', text: '>', action: () => api()?.resume() });
  dev.register({ group: 'sim', label: 'Step', type: 'button', text: '+1', action: () => api()?.step(1) });

  dev.register({
    group: 'perf', label: 'Frame', type: 'readout',
    get: () => {
      const s = api()?.stats?.(); if (!s) return '—';
      return { text: `${s.frameMs.toFixed(1)}ms ${(1000 / s.frameMs).toFixed(0)}fps`, ok: s.budget.frameMs.ok };
    },
  });
  dev.register({
    group: 'perf', label: 'Draws', type: 'readout',
    get: () => {
      const s = api()?.stats?.(); if (!s) return '—';
      return { text: `${s.calls}/${s.budget.calls.limit}`, ok: s.budget.calls.ok };
    },
  });
  dev.register({
    group: 'perf', label: 'Tris', type: 'readout',
    get: () => {
      const s = api()?.stats?.(); if (!s) return '—';
      return { text: (s.tris / 1000).toFixed(0) + 'k', ok: s.budget.tris.ok };
    },
  });

  return dev;
}
