import * as THREE from 'three';

// ─────────────────────────────────────────────────────────────────────────────
// Named camera setups for the review harness.
//
// A shot is a deterministic framing of the live scene, so a critic can diff the
// same angle across builds and nothing shifts underneath them between runs.
// `tools/shot.mjs --shots hero,ridge` drives these by name.
//
// SHARED CORE — do not edit this file to add your lane's angle. Call
// `registerShot('battle-finisher', ctx => {…})` from your own module instead.
// That seam exists precisely so eleven lanes can add cameras without eleven
// conflicting edits to one file.
// ─────────────────────────────────────────────────────────────────────────────

const _v = new THREE.Vector3();

/**
 * Place `cam` on a sphere around `target`.
 * @param yaw   degrees, 0 = +Z (looking north), increasing clockwise from above
 * @param pitch degrees above the horizon; 90 is straight down
 */
export function orbit(cam, target, { dist, yaw, pitch, fov = 28, lift = 0 }) {
  const y = THREE.MathUtils.degToRad(yaw);
  const p = THREE.MathUtils.degToRad(pitch);
  _v.set(Math.sin(y) * Math.cos(p), Math.sin(p), Math.cos(y) * Math.cos(p)).multiplyScalar(dist);
  cam.position.copy(target).add(_v);
  cam.position.y += lift;
  cam.fov = fov;
  cam.near = Math.max(0.35, dist * 0.02);
  cam.far = Math.max(1200, dist * 30);
  cam.updateProjectionMatrix();
  cam.lookAt(target);
}

/** Where a shot points when nothing else says otherwise. */
function focus(ctx) {
  const f = ctx.world?.focus;
  return f ? f.clone() : new THREE.Vector3(0, 0, 0);
}

export const SHOTS = {
  /** The shipping framing — exactly what the player sees. Every other shot is
   *  diagnostic; this is the one a critic scores. */
  hero(ctx) {
    ctx.rig.apply(ctx.camera, focus(ctx));
  },

  /** Pulled back and lower: reads the landscape, the sun angle and the haze. */
  wide(ctx) {
    orbit(ctx.camera, focus(ctx), { dist: 132, yaw: 214, pitch: 26, fov: 30, lift: 4 });
  },

  /** Along the light, from a ridge. Long shadows and elevation read here or
   *  nowhere — this is the shot that fails if the world is flat (defect 5). */
  ridge(ctx) {
    const t = focus(ctx).add(new THREE.Vector3(-14, 0, -18));
    orbit(ctx.camera, t, { dist: 74, yaw: 128, pitch: 17, fov: 33, lift: 2 });
  },

  /** Near ground level. The only reliable way to see whether things TOUCH the
   *  ground — contact shadow, ambient occlusion, grounding (defect 3).
   *
   *  The camera places itself DOWNHILL of the subject rather than at a fixed
   *  compass bearing. A hand-picked bearing works until the terrain under the
   *  subject changes, and then the shot quietly frames the back of a ridge with
   *  the subject's feet behind it — which looks exactly like a floating-prop bug
   *  and is not one. Reading the slope makes the shot self-correcting. */
  ground(ctx) {
    const t = ctx.world?.propFocus?.clone?.() || focus(ctx);
    const n = ctx.world?.normalAt?.(t.x, t.z) || new THREE.Vector3(0, 1, 0);
    const down = new THREE.Vector3(-n.x, 0, -n.z);
    if (down.lengthSq() < 1e-6) down.set(0, 0, 1);
    down.normalize();
    const cam = ctx.camera;
    const dist = 12;
    cam.position.copy(t).addScaledVector(down, dist);
    // Above the SUBJECT's ground, not the camera's own: standing downhill and
    // eye-height puts the crest between the lens and the thing being checked.
    cam.position.y = Math.max(
      ctx.world?.heightAt?.(cam.position.x, cam.position.z) ?? t.y, t.y) + 3.4;
    cam.fov = 40;
    cam.near = 0.4; cam.far = 6000;
    cam.updateProjectionMatrix();
    cam.lookAt(t.x, t.y + 0.4, t.z);
  },

  /** Straight down. The grid check: if any tile boundary is visible from plan
   *  view, defect 2 has come back. */
  top(ctx) {
    orbit(ctx.camera, focus(ctx), { dist: 96, yaw: 200, pitch: 88, fov: 30 });
  },

  /** Tight on the material study props: metal, rock, painted, emissive. */
  materials(ctx) {
    const t = ctx.world?.propFocus?.clone?.() || focus(ctx);
    orbit(ctx.camera, t, { dist: 15, yaw: 226, pitch: 15, fov: 30, lift: 1.2 });
  },

  /** Into the sun. Tone-curve, bloom and haze stress test — the frame most
   *  likely to blow out, so it is a standing shot rather than an afterthought.
   *
   *  Deliberately composed rather than aimed at the disc: the camera stands
   *  downsun and tilts 6° up, which puts the sun in the upper third and the
   *  horizon at ~60% height. Pointing straight at the sun fills the frame with
   *  sky and measures nothing — the question this shot answers is whether
   *  terrain still SILHOUETTES against a blown sky, and that needs terrain in it. */
  sun(ctx) {
    const cam = ctx.camera;
    const t = focus(ctx);
    const sd = ctx.env?.sunDir || new THREE.Vector3(0, 0.3, -1);
    const back = new THREE.Vector3(-sd.x, 0, -sd.z);
    if (back.lengthSq() < 1e-6) back.set(0, 0, 1);
    back.normalize();
    cam.position.copy(t).addScaledVector(back, 26);
    cam.position.y = (ctx.world?.heightAt?.(cam.position.x, cam.position.z) ?? t.y) + 6.5;
    cam.fov = 46;
    cam.near = 0.5; cam.far = 6000;
    cam.updateProjectionMatrix();
    const tilt = Math.tan(THREE.MathUtils.degToRad(6));
    cam.lookAt(
      cam.position.x - back.x * 300,
      cam.position.y + tilt * 300,
      cam.position.z - back.z * 300,
    );
  },
};

/**
 * Register a review camera from your own module.
 *   registerShot('battle-finisher', (ctx) => { … })
 * Names are namespaced by lane by convention: `battle-*`, `places-*`, `fx-*`.
 */
export function registerShot(name, fn) {
  if (SHOTS[name]) console.warn('[shots] overwriting', name);
  SHOTS[name] = fn;
  return name;
}

export function applyShot(name, ctx) {
  const fn = SHOTS[name];
  if (!fn) { console.warn('[shots] unknown shot', name); return false; }
  try { fn(ctx); }
  catch (e) { console.error(`[shots] "${name}" threw:`, e); return false; }
  return true;
}

export function shotNames() { return Object.keys(SHOTS); }
