/** Stable, serializable base-game catalog. No expansion content is registered. */
export const TIERS = ['Survivor', 'Reclaimer', 'Ascendant', 'Transcendent'];
export const HEROES = {
  kaida: {
    id: 'kaida',
    name: 'Kaida',
    role: 'Wayfarer',
    color: '#cc5775',
    maxHp: 156,
    maxMp: 42,
    str: 20,
    int: 10,
    tec: 13,
    def: 9,
    spd: 16,
    crit: 7,
    growth: {
      maxHp: 17,
      maxMp: 3,
      str: 2.3,
      int: 1.1,
      tec: 1.6,
      def: 1.25,
      spd: 0.15,
      crit: 0.1,
    },
    starters: ['rift_cleave', 'salt_mend'],
    weapon: 'iron_blade',
  },
  vex: {
    id: 'vex',
    name: 'Vex',
    role: 'Signal mage',
    color: '#76bec3',
    maxHp: 120,
    maxMp: 82,
    str: 9,
    int: 23,
    tec: 16,
    def: 7,
    spd: 14,
    crit: 5,
    growth: {
      maxHp: 13,
      maxMp: 5,
      str: 1,
      int: 2.7,
      tec: 1.8,
      def: 1,
      spd: 0.17,
      crit: 0.08,
    },
    starters: ['void_lance', 'lantern_mend'],
    weapon: 'void_shard',
  },
  rune: {
    id: 'rune',
    name: 'Rune',
    role: 'Sentinel',
    color: '#d3ad68',
    maxHp: 198,
    maxMp: 56,
    str: 17,
    int: 12,
    tec: 23,
    def: 16,
    spd: 11,
    crit: 4,
    growth: {
      maxHp: 22,
      maxMp: 4,
      str: 1.9,
      int: 1.2,
      tec: 2.4,
      def: 1.7,
      spd: 0.12,
      crit: 0.07,
    },
    starters: ['aegis_field', 'anchor_blow'],
    weapon: 'rune_gauntlet',
  },
};
const item = (id, name, slot, stats, price, tier, description, extra = {}) => ({
  id,
  name,
  slot,
  stats,
  price,
  tier,
  description,
  ...extra,
});
export const ITEMS = Object.fromEntries(
  [
    item(
      'iron_blade',
      'Iron Blade',
      'weapon',
      { str: 5 },
      24,
      1,
      'A slender edge of salvaged steel.',
    ),
    item(
      'void_shard',
      'Void Shard',
      'weapon',
      { int: 7, maxMp: 10 },
      30,
      1,
      'A tuning fork for a signal nobody hears.',
    ),
    item(
      'rune_gauntlet',
      'Rune Gauntlet',
      'weapon',
      { tec: 7, def: 3 },
      30,
      1,
      'Old sentinel plates; the knuckles remember.',
    ),
    item(
      'scrap_vest',
      'Scrap Vest',
      'armor',
      { def: 4 },
      24,
      1,
      'Overlapping plates stitched to a soft lining.',
    ),
    item(
      'bio_weave',
      'Bio-Weave',
      'armor',
      { maxHp: 30, def: 3 },
      48,
      2,
      'Living fibers close over a wound.',
    ),
    item(
      'data_chip',
      'Data Chip',
      'accessory',
      { spd: 3 },
      30,
      1,
      'A salvaged reflex interpreter.',
    ),
    item(
      'crit_lens',
      'Crit Lens',
      'accessory',
      { crit: 7 },
      44,
      2,
      'An optical beat-marker for precise strikes.',
    ),
    item(
      'bog_fang',
      'Bog Fang',
      'weapon',
      { str: 4, spd: 3 },
      36,
      1,
      'A light hooked edge carved from marsh ivory.',
    ),
    item(
      'swamp_coil',
      'Swamp Coil',
      'accessory',
      { crit: 4, spd: 2 },
      44,
      2,
      'Reed-wrapped copper humming with life.',
    ),
    item(
      'glacial_claw',
      'Glacial Claw',
      'weapon',
      { str: 10, crit: 4 },
      70,
      2,
      'A frozen edge that rewards a steady hand.',
    ),
    item(
      'moss_ward',
      'Moss Ward',
      'accessory',
      { def: 6, maxHp: 25 },
      66,
      2,
      'A small ecosystem protects its bearer.',
    ),
    item(
      'ember_core',
      'Ember Core',
      'weapon',
      { int: 15, str: 4 },
      110,
      3,
      'A portable kiln for a mage’s equations.',
    ),
    item(
      'frost_plate',
      'Frost Plate',
      'armor',
      { def: 11, maxHp: 50, spd: -1 },
      120,
      3,
      'Glacial plates; exceptional protection, heavier steps.',
    ),
    item(
      'void_scepter',
      'Void Scepter',
      'weapon',
      { int: 22, maxMp: 30 },
      150,
      3,
      'A focus that listens before it speaks.',
    ),
    item(
      'magma_blade',
      'Magma Blade',
      'weapon',
      { str: 22, crit: 5 },
      155,
      3,
      'A fine black edge holding a red horizon.',
    ),
    item(
      'titan_shard',
      'Titan Shard',
      'armor',
      { def: 18, maxHp: 85, spd: -2 },
      230,
      4,
      'Shelter forged from the Crown’s living alloy.',
    ),
    item(
      'ember_crown',
      'Ember Crown',
      'accessory',
      { crit: 10, spd: 5 },
      210,
      4,
      'The caldera’s patient, unquenched light.',
    ),
    item(
      'signal_saber',
      'Signal Saber',
      'weapon',
      { str: 12, tec: 5 },
      75,
      2,
      'A balanced resonant blade.',
      { family: 'Resonance' },
    ),
    item(
      'anchor_hammer',
      'Anchor Hammer',
      'weapon',
      { tec: 16, def: 5, spd: -1 },
      98,
      2,
      'Sentinel armament: a movable foundation.',
      { family: 'Anchor' },
    ),
    item(
      'glass_needle',
      'Glass Needle',
      'weapon',
      { int: 11, spd: 3 },
      80,
      2,
      'Fast spellwork through a crystalline prism.',
      { family: 'Prism' },
    ),
    item(
      'horizon_edge',
      'Horizon Edge',
      'weapon',
      { str: 31, tec: 12, crit: 5 },
      260,
      4,
      'Three metals, one shared horizon.',
      { family: 'Concord' },
    ),
    item(
      'concord_staff',
      'Concord Staff',
      'weapon',
      { int: 33, maxMp: 45 },
      260,
      4,
      'Carries a chorus without silencing any voice.',
      { family: 'Concord' },
    ),
    item(
      'harbor_aegis',
      'Harbor Aegis',
      'weapon',
      { tec: 32, def: 9 },
      260,
      4,
      'A shield that can become a door.',
      { family: 'Concord' },
    ),
    item(
      'voyager_coat',
      'Voyager Coat',
      'armor',
      { def: 9, spd: 4, maxMp: 18 },
      105,
      3,
      'Made for a mage who intends to keep walking.',
    ),
    item(
      'witness_prism',
      'Witness Prism',
      'accessory',
      { int: 16, maxMp: 35 },
      0,
      3,
      'Vex chose to preserve the voices, even the painful ones.',
      { unique: true },
    ),
    item(
      'quiet_prism',
      'Quiet Prism',
      'accessory',
      { int: 10, def: 8, maxHp: 50 },
      0,
      3,
      'Vex gave the trapped voices a merciful silence.',
      { unique: true },
    ),
    item(
      'namekeeper',
      'Namekeeper',
      'accessory',
      { tec: 17, maxHp: 70 },
      0,
      4,
      'Rune carries the names, no longer the command.',
      { unique: true },
    ),
    item(
      'open_gate',
      'Open Gate',
      'accessory',
      { def: 13, spd: 4 },
      0,
      4,
      'Rune’s oath belongs to living people.',
      { unique: true },
    ),
    item(
      'mara_compass',
      'Mara’s Compass',
      'accessory',
      { spd: 5, crit: 5, maxHp: 35 },
      0,
      3,
      'A compass that always points toward someone waiting.',
      { unique: true },
    ),
    item(
      'field_tonic',
      'Field Tonic',
      'consumable',
      {},
      8,
      1,
      'Restore 80 HP to one ally.',
      { effect: 'heal', power: 80 },
    ),
    item(
      'ether_cell',
      'Ether Cell',
      'consumable',
      {},
      10,
      1,
      'Restore 30 MP to one ally.',
      { effect: 'restoreMp', power: 30 },
    ),
    item(
      'dawn_seed',
      'Dawn Seed',
      'consumable',
      {},
      24,
      2,
      'Revive one fallen ally with 35% HP.',
      { effect: 'revive', power: 0.35 },
    ),
    item(
      'tide_elixir',
      'Tide Elixir',
      'consumable',
      {},
      22,
      3,
      'Restore 220 HP to one ally.',
      { effect: 'heal', power: 220 },
    ),
    item(
      'star_cell',
      'Star Cell',
      'consumable',
      {},
      30,
      3,
      'Restore 90 MP to one ally.',
      { effect: 'restoreMp', power: 90 },
    ),
  ].map((i) => [i.id, i]),
);
const tech = (
  id,
  name,
  heroes,
  mp,
  power,
  stat,
  target,
  effect,
  cost,
  requires,
  description,
  extra = {},
) => ({
  id,
  name,
  heroes,
  mp,
  power,
  stat,
  target,
  effect,
  cost,
  requires,
  description,
  ...extra,
});
export const TECHS = Object.fromEntries(
  [
    tech(
      'rift_cleave',
      'Rift Cleave',
      ['kaida'],
      7,
      1.25,
      'str',
      'allEnemies',
      'damage',
      0,
      [],
      'Sweep a crescent through the enemy line.',
    ),
    tech(
      'salt_mend',
      'Salt Mend',
      ['kaida'],
      6,
      2.1,
      'int',
      'ally',
      'heal',
      0,
      [],
      'An old coast remedy: steady breath, warm hands.',
    ),
    tech(
      'chrono_strike',
      'Beat Break',
      ['kaida'],
      8,
      1.8,
      'str',
      'enemy',
      'slow',
      1,
      ['rift_cleave'],
      'A precise cut interrupts the enemy’s rhythm.',
    ),
    tech(
      'time_sever',
      'Horizon Sever',
      ['kaida'],
      16,
      3.3,
      'str',
      'enemy',
      'damage',
      3,
      ['chrono_strike'],
      'Three steps and a single decisive edge.',
    ),
    tech(
      'void_lance',
      'Void Lance',
      ['vex'],
      7,
      1.9,
      'int',
      'enemy',
      'damage',
      0,
      [],
      'An amber proof written through the target.',
    ),
    tech(
      'lantern_mend',
      'Lantern Mend',
      ['vex'],
      10,
      2.3,
      'int',
      'allAllies',
      'heal',
      0,
      [],
      'A circle of lantern glyphs restores the crew.',
    ),
    tech(
      'null_field',
      'Null Field',
      ['vex'],
      12,
      1.55,
      'int',
      'allEnemies',
      'damage',
      1,
      ['void_lance'],
      'Fold a ring of silence around the opposing line.',
    ),
    tech(
      'entropy_surge',
      'Entropy Surge',
      ['vex'],
      18,
      1.5,
      'int',
      'allEnemies',
      'drain',
      3,
      ['null_field'],
      'Borrow strength from the collapsing field.',
    ),
    tech(
      'aegis_field',
      'Aegis Field',
      ['rune'],
      9,
      1,
      'tec',
      'allAllies',
      'shield',
      0,
      [],
      'A mobile wall halves the next incoming blows.',
    ),
    tech(
      'anchor_blow',
      'Anchor Blow',
      ['rune'],
      6,
      1.8,
      'tec',
      'enemy',
      'damage',
      0,
      [],
      'Plant your feet. Move the world.',
    ),
    tech(
      'bulwark',
      'Bulwark',
      ['rune'],
      8,
      1.8,
      'tec',
      'self',
      'shield',
      1,
      ['aegis_field'],
      'Brace behind the great shield and weather the assault.',
    ),
    tech(
      'temporal_wall',
      'Hold the Dawn',
      ['rune'],
      18,
      2,
      'tec',
      'allAllies',
      'shield',
      3,
      ['bulwark'],
      'A reinforced party ward for the darkest interval.',
    ),
    tech(
      'prism_cut',
      'Prism Cut',
      ['kaida', 'vex'],
      10,
      2.5,
      'str',
      'allEnemies',
      'damage',
      2,
      ['chrono_strike', 'null_field'],
      'Vex splits the edge into a fan of refracted blades.',
      { level: 8 },
    ),
    tech(
      'harbor_break',
      'Harbor Break',
      ['kaida', 'rune'],
      11,
      3.4,
      'tec',
      'enemy',
      'damage',
      2,
      ['chrono_strike', 'bulwark'],
      'Rune launches Kaida from the shield into a plunging cut.',
      { level: 12 },
    ),
    tech(
      'shelterlight',
      'Shelterlight',
      ['vex', 'rune'],
      12,
      3.4,
      'int',
      'allAllies',
      'heal',
      2,
      ['lantern_mend', 'aegis_field'],
      'A constellation shelters within Rune’s raised shield.',
      { level: 12 },
    ),
    tech(
      'concord_dawn',
      'Concord Dawn',
      ['kaida', 'vex', 'rune'],
      20,
      4.8,
      'tec',
      'allEnemies',
      'damage',
      4,
      ['prism_cut', 'harbor_break', 'shelterlight'],
      'Steel, signal and shelter meet in a single sunrise.',
      { level: 24, tier: 4 },
    ),
    tech(
      'witness_song',
      'Witness Song',
      ['vex'],
      14,
      3.3,
      'int',
      'allAllies',
      'heal',
      0,
      [],
      'Remembered voices lend the living their strength.',
      { flag: 'vex_arc_complete', hidden: true },
    ),
    tech(
      'open_horizon',
      'Open Horizon',
      ['rune'],
      14,
      2.4,
      'tec',
      'allAllies',
      'shield',
      0,
      [],
      'Protection freely given, never commanded.',
      { flag: 'rune_arc_complete', hidden: true },
    ),
  ].map((t) => [t.id, t]),
);
// Fixed strength labels: coast 1–3, regional patrols 6–18, guardians 22–34, final 40.
// Levels are presentation metadata; tier, stats and rewards retain their authored values.
const enemy = (
  id,
  name,
  tier,
  hp,
  str,
  def,
  spd,
  xp,
  drop,
  description,
  extra = {},
) => ({
  id,
  name,
  tier,
  hp,
  str,
  def,
  spd,
  xp,
  drop,
  description,
  int: str,
  crit: 5,
  ...extra,
});
export const ENEMIES = Object.fromEntries(
  [
    enemy(
      'rust_scrapper',
      'Rust Scrapper',
      1,
      76,
      15,
      3,
      10,
      22,
      'iron_blade',
      'A crablike scavenger carrying a broken kettle.',
      { level: 1 },
    ),
    enemy(
      'drone_sentinel',
      'Drone Sentinel',
      1,
      60,
      17,
      2,
      18,
      28,
      'data_chip',
      'A hovering lens trailing three copper vanes.',
      { level: 2 },
    ),
    enemy(
      'bog_stalker',
      'Bog Stalker',
      1,
      100,
      20,
      4,
      14,
      32,
      'bog_fang',
      'A reed-legged ambusher in a floating lily mask.',
      { level: 3 },
    ),
    enemy(
      'slag_rat',
      'Slag Rat',
      1,
      55,
      14,
      2,
      21,
      21,
      'field_tonic',
      'A quick scrap-eater with a furnace-bright whisker.',
      { level: 1 },
    ),
    enemy(
      'mutant_hound',
      'Mutant Hound',
      2,
      215,
      32,
      8,
      18,
      60,
      'bio_weave',
      'A split-maned hunter wrapped in ribbonlike fronds.',
      { level: 6 },
    ),
    enemy(
      'gravbot',
      'Gravbot',
      2,
      320,
      30,
      17,
      8,
      72,
      'rune_gauntlet',
      'An obsidian-armored automaton wielding a concentrated gravity field.',
      { level: 8 },
    ),
    enemy(
      'mire_hulk',
      'Mire Hulk',
      2,
      400,
      39,
      13,
      8,
      90,
      'swamp_coil',
      'A peat-armored toad carrying a dead tree and pale shelf fungi.',
      { level: 10 },
    ),
    enemy(
      'glacier_wolf',
      'Glacier Wolf',
      2,
      255,
      37,
      9,
      21,
      80,
      'glacial_claw',
      'A white, glass-antlered predator with a blue throat.',
      { level: 10 },
    ),
    enemy(
      'neon_cultist',
      'Neon Cultist',
      3,
      400,
      38,
      13,
      17,
      115,
      'void_shard',
      'A signal pilgrim hidden inside a floating scripture cage.',
      {
        level: 12,
        mechanic: 'charge',
        telegraph: 'The scripture cage opens. A burst is coming.',
      },
    ),
    enemy(
      'sandworm',
      'Sandworm Hatchling',
      3,
      650,
      50,
      19,
      10,
      140,
      'crit_lens',
      'A segmented stone auger crowned with golden feelers.',
      {
        level: 15,
        mechanic: 'charge',
        telegraph: 'It coils beneath the sand. Brace for impact.',
      },
    ),
    enemy(
      'ember_golem',
      'Ember Golem',
      3,
      780,
      52,
      28,
      8,
      155,
      'ember_core',
      'A furnace-crab with basalt claws and a vented iron chest.',
      {
        level: 18,
        mechanic: 'charge',
        telegraph: 'The furnace inhales. Its next blow will be heavy.',
      },
    ),
    enemy(
      'frost_revenant',
      'Frost Revenant',
      3,
      620,
      54,
      20,
      17,
      150,
      'frost_plate',
      'A masked burial sail bearing a blue crystal lance and a lantern.',
      {
        level: 18,
        mechanic: 'siphon',
        telegraph: 'Frost gathers along its burial sail.',
      },
    ),
    enemy(
      'wraith_core',
      'Wraith Core',
      4,
      860,
      68,
      23,
      22,
      210,
      'void_scepter',
      'A hollow star of dark bronze fins around a pale, restless core.',
      {
        level: 24,
        mechanic: 'charge',
        telegraph: 'The dark star contracts. Defend the party.',
      },
    ),
    enemy(
      'mire_warden',
      'Mire Warden',
      4,
      1600,
      63,
      27,
      12,
      290,
      'moss_ward',
      'A great heron-shaped archive grown from root and bronze.',
      {
        level: 22,
        mechanic: 'fortress',
        telegraph: 'Its roots draw in light. The canopy will strike.',
      },
    ),
    enemy(
      'magma_behemoth',
      'Magma Behemoth',
      4,
      1450,
      72,
      31,
      8,
      300,
      'magma_blade',
      'A immense plated salamander with a glass chimney spine.',
      {
        level: 26,
        mechanic: 'charge',
        telegraph: 'The chimney glows white. Take cover.',
      },
    ),
    enemy(
      'architect_herald',
      'Architect Herald',
      5,
      4200,
      86,
      35,
      18,
      525,
      'titan_shard',
      'A faceless envoy unfolding like an ivory sextant.',
      {
        level: 34,
        mechanic: 'fortress',
        phaseAt: 0.5,
        telegraph: 'The sextant aligns. A judgment falls on everyone.',
      },
    ),
    enemy(
      'frost_colossus',
      'Frost Colossus',
      5,
      4000,
      80,
      34,
      11,
      500,
      'titan_shard',
      'The frozen elevator’s guardian, shoulders like a bridge.',
      {
        level: 32,
        mechanic: 'fortress',
        phaseAt: 0.5,
        telegraph: 'Its bridge-arms rise. A crushing wave approaches.',
      },
    ),
    enemy(
      'ember_lord',
      'Ember Lord',
      5,
      3800,
      84,
      30,
      15,
      500,
      'ember_crown',
      'A furnace mantis crowned with ivory horns and molten blade-arms.',
      {
        level: 32,
        mechanic: 'charge',
        phaseAt: 0.5,
        telegraph: 'The molten blades draw together. Guard before they strike.',
      },
    ),
    enemy(
      'void_architect',
      'Void Architect',
      5,
      10000,
      99,
      39,
      18,
      900,
      'horizon_edge',
      'A luminous human silhouette inside a vast broken armillary.',
      {
        level: 40,
        mechanic: 'architect',
        phaseAt: 0.55,
        phases: ['The Perfect Shelter', 'The Open Sky'],
        telegraph: 'The armillary closes. Shelter together, then answer.',
      },
    ),
  ].map((e) => [e.id, e]),
);
export const BUILDINGS = {
  town_center: {
    id: 'town_center',
    name: 'Town Center',
    tier: 1,
    cost: { ore: 35, food: 20 },
    description:
      'Shared stores and a beacon. Each level strengthens production and civic recovery.',
  },
  farm: {
    id: 'farm',
    name: 'Farm',
    tier: 1,
    cost: { ore: 18 },
    produces: 'food',
    rate: 0.45,
    description:
      'Terraced salt gardens produce food. Food supports inns, training and growth.',
  },
  mine: {
    id: 'mine',
    name: 'Mine',
    tier: 1,
    cost: { food: 15 },
    produces: 'ore',
    rate: 0.35,
    description:
      'A crew sorts reusable ore from safe ruins. Ore buys equipment and construction.',
  },
  energy_extractor: {
    id: 'energy_extractor',
    name: 'Energy Extractor',
    tier: 1,
    cost: { ore: 22, food: 12 },
    produces: 'energy',
    rate: 0.25,
    description:
      'Tidal vanes collect energy for research and advanced construction.',
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    tier: 2,
    cost: { ore: 45, food: 30 },
    description:
      'Training adds 2 strength and technique per level; unlocks paid field training.',
  },
  forge: {
    id: 'forge',
    name: 'Forge',
    tier: 2,
    cost: { ore: 55, energy: 20 },
    description:
      'Resonance work adds 1 defense per level and unlocks advanced weapon families.',
  },
  research_lab: {
    id: 'research_lab',
    name: 'Research Lab',
    tier: 2,
    cost: { ore: 60, energy: 35 },
    description:
      'Adds 5 maximum MP per level and unlocks research and Transcendence.',
  },
  walls: {
    id: 'walls',
    name: 'Walls',
    tier: 1,
    cost: { ore: 28 },
    description:
      'Signal defenses grant 3 defense per level in every battle and improve safe recovery.',
  },
};
export const SERVICES = {
  provisions: {
    id: 'provisions',
    name: 'Provisions',
    tier: 1,
    level: 1,
    description: 'Tonics, cells, seeds and everyday supplies.',
  },
  smith: {
    id: 'smith',
    name: 'Salvage smith',
    tier: 1,
    level: 1,
    description: 'Trade ore for blades, coats and charms.',
  },
  inn: {
    id: 'inn',
    name: 'Rest house',
    tier: 1,
    level: 1,
    description:
      'Restore the crew using food; shelter never turns away an exhausted traveler.',
  },
  archivist: {
    id: 'archivist',
    name: 'Signal archivist',
    tier: 2,
    level: 6,
    description: 'Research, story records and signal weapons.',
    requires: 'research_lab',
  },
  artificer: {
    id: 'artificer',
    name: 'Concord artificer',
    tier: 3,
    level: 16,
    description: 'Advanced armor and weapon families.',
    requires: 'forge',
  },
  trainer: {
    id: 'trainer',
    name: 'Sentinel trainer',
    tier: 2,
    level: 10,
    description: 'Spend food and energy for practical experience.',
    requires: 'barracks',
  },
};
export const EXPANSION_CONTRACT = Object.freeze({
  namespace: 'future',
  developmentAuthorized: false,
  available: false,
  prerequisites: ['campaignComplete', 'kaidaLevel>=40'],
  era: 'present',
});
