import {AtlasMap,isRevealed,mapPosition} from './maps.js';
import {REGIONS,terrainAt} from './world.js';

// Same regional layout as the production atlas. Geometry, connections, fog,
// landmarks and position all come from the live world; no decorative fake map.
const points={haventide:[0,1],emberline:[1,1],orbital_reach:[2,1],last_crown:[3,1],forest_veil:[1,2],mire_bog:[2,2],crater_ember:[1,0],frost_canyon:[2,0]};
export class ExpeditionMap extends AtlasMap {
 draw(){const canvas=this.canvas;if(!canvas)return;const c=canvas.getContext('2d'),w=680,h=365,s=this.game.state,position=mapPosition(s);canvas.width=w*2;canvas.height=h*2;c.scale(2,2);c.fillStyle='#deca9f';c.fillRect(0,0,w,h);c.strokeStyle='#76634417';c.lineWidth=.6;for(let x=16;x<w;x+=24){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=16;y<h;y+=24){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}c.save();c.translate(w/2+this.panX,h/2+this.panY);c.scale(this.zoom,this.zoom);c.translate(-w/2,-h/2);const bw=126,bh=74,ox=37,oy=34,centers={};for(const[id,p]of Object.entries(points))centers[id]=[ox+p[0]*157+bw/2,oy+p[1]*106+bh/2];
  const edges=new Set();for(const r of Object.values(REGIONS)){if(!s.visited[r.id])continue;for(const p of r.portals){if(!s.visited[p.to]||!centers[p.to])continue;const edge=[r.id,p.to].sort().join(':');if(edges.has(edge))continue;edges.add(edge);c.strokeStyle='#6a563c';c.setLineDash([2,4]);c.beginPath();c.moveTo(...centers[r.id]);c.lineTo(...centers[p.to]);c.stroke();c.setLineDash([]);}}
  for(const[id,p]of Object.entries(points)){const r=REGIONS[id],x=ox+p[0]*157,y=oy+p[1]*106;c.fillStyle=s.visited[id]?'#bdac86':'#d3bd91';c.fillRect(x,y,bw,bh);c.strokeStyle=position?.region===id?'#ad5428':'#96805a66';c.lineWidth=position?.region===id?1.2:.6;c.strokeRect(x-.5,y-.5,bw+1,bh+1);if(s.visited[id]){for(let cy=0;cy<bh;cy+=2)for(let cx=0;cx<bw;cx+=2){const wx=(cx+.5)/bw*r.width,wy=(cy+.5)/bh*r.height;if(!isRevealed(s,id,wx,wy))continue;const t=terrainAt(r,wx,wy);c.fillStyle=t==='water'?'#979b8b':t==='path'?'#ebdcb5':'#b4b18c';c.fillRect(x+cx,y+cy,2,2);}for(const o of [...r.objects,...r.portals]){if(!['town','house','cave','portal','landmark'].includes(o.type)||!isRevealed(s,id,o.x,o.y))continue;const px=x+o.x/r.width*bw,py=y+o.y/r.height*bh;c.fillStyle='#574832';if(o.type==='town'){c.strokeStyle='#574832';c.lineWidth=.8;c.strokeRect(px-2,py-2,4,4);}else{c.beginPath();c.arc(px,py,1.2,0,Math.PI*2);c.fill();}}if(position?.region===id){const px=x+position.x/r.width*bw,py=y+position.y/r.height*bh;c.strokeStyle='#ae4829';c.lineWidth=1.4;c.beginPath();c.moveTo(px-4,py);c.lineTo(px+4,py);c.moveTo(px,py-4);c.lineTo(px,py+4);c.stroke();}c.fillStyle='#53442e';c.font='11px Barlow, sans-serif';c.fillText(r.name.toUpperCase(),x,y+bh+14);}else{c.fillStyle='#8b7857';c.font='italic 12px "EB Garamond", serif';c.textAlign='center';c.fillText('Uncharted',x+bw/2,y+bh/2+4);c.textAlign='left';}}
  c.restore();c.fillStyle='#786344';c.font='10px Barlow,sans-serif';c.fillText('FIELD SURVEY / PRESENT WORLD',12,17);c.textAlign='right';c.fillText('N ↑',w-12,17);c.textAlign='left';
 }
 // AtlasMap uses backing-pixel units for dragging. This map renders at 2×,
 // while its pan coordinates remain in the same logical units as key input.
 mount(canvas){super.mount(canvas);let start=null;canvas.onpointerdown=e=>{start=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const scale=680/canvas.clientWidth;this.panX+=(e.clientX-start[0])*scale;this.panY+=(e.clientY-start[1])*scale;start=[e.clientX,e.clientY];this.draw();};canvas.onpointerup=canvas.onpointercancel=()=>start=null;}
}
