import {HEROES,ITEMS,TECHS,TIERS} from './content.js';
import * as P from './progression.js';
import {REGIONS,ALL_SCENES} from './world.js';
import {questList,mainObjective} from './narrative.js';
import {saveMeta} from './persistence.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.floor(n??0).toLocaleString();
const time=s=>`${Math.floor((s||0)/3600)}h ${Math.floor(((s||0)%3600)/60)}m`;
const btn=(label,action,cl='',attrs='')=>`<button class="${cl}" data-do="${esc(action)}" ${attrs}>${label}</button>`;
const icon=id=>`<canvas class="pixel-icon" data-icon="${esc(id)}" width="128" height="128" aria-hidden="true"></canvas>`;
const names={str:'Strength',int:'Intellect',tec:'Technique',def:'Defense',spd:'Speed',crit:'Critical %',maxHp:'Max HP',maxMp:'Max MP'};
const tabs=['Map','Party','Inventory','Skills','Quests','Save','Settings'];
const heroOf=ui=>ui.game.state.heroes[ui.hero]||ui.game.state.heroes[0];
const header=(title,note)=>`<div class="exp-heading"><h2>${title}</h2><span>${note}</span></div>`;
const statList=(h,s)=>`<dl class="exp-stats">${['str','int','tec','def','spd','crit'].map(k=>`<div><dt>${names[k]}</dt><dd>${P.stats(h,s)[k]}</dd></div>`).join('')}</dl>`;
function heroPicker(ui){return `<div class="exp-crew" role="group" aria-label="Crew member">${ui.game.state.heroes.map((h,i)=>btn(`<span>${h.name}</span><small>LV ${h.level}</small>`,'hero:'+i,'exp-crew-choice',`aria-pressed="${i===ui.hero}"`)).join('')}</div>`;}
function heroArt(h){return `<div class="exp-figure"><span class="exp-figure-rule"></span><canvas width="480" height="640" data-menu-hero="${h.id}" aria-label="${h.name}, ${HEROES[h.id].role}"></canvas><span class="exp-figure-caption">${HEROES[h.id].role} / LEVEL ${h.level}</span></div>`;}
function gear(h,inventory){return `<div class="exp-gear"><div class="exp-kicker">EQUIPPED</div>${Object.entries(h.equip).map(([slot,id])=>btn(`${id?icon(id):'<span class="exp-empty-slot">—</span>'}<span><small>${slot}</small><strong>${id?ITEMS[id].name:'Empty slot'}</strong>${inventory&&id?'<em>Return to pack</em>':''}</span>`,inventory?'unequip:'+slot:'tab:2','exp-gear-slot',!id?'disabled':'')).join('')}</div>`;}
function vitals(h,s){const st=P.stats(h,s);return `<div class="exp-vitals">${[['HP',h.hp,st.maxHp],['MP',h.mp,st.maxMp],['XP',h.xp,P.xpForLevel(h.level)]].map(([label,v,max])=>`<div><span>${label}</span><strong>${fmt(v)} <small>/ ${fmt(max)}</small></strong><i><i style="width:${Math.max(0,Math.min(100,v/max*100))}%"></i></i></div>`).join('')}</div>`;}
function characterPage(ui,inventory){const s=ui.game.state,h=heroOf(ui);const ids=Object.keys(s.inventory).filter(id=>s.inventory[id]>0&&ITEMS[id]).sort((a,b)=>ITEMS[a].slot.localeCompare(ITEMS[b].slot)||ITEMS[a].name.localeCompare(ITEMS[b].name));if(!ids.includes(ui.item))ui.item=ids[0];return `${header(h.name,`${HEROES[h.id].role} · ${inventory?'FIELD EQUIPMENT':'CREW RECORD'} / ${s.heroes.length} COMPANIONS`)}${heroPicker(ui)}<div class="exp-character-layout">${gear(h,inventory)}${heroArt(h)}<aside class="exp-character-notes">${vitals(h,s)}${inventory?`<div class="exp-pack"><div class="exp-kicker">PACK / ${ids.length} KINDS</div><div class="exp-pack-items">${ids.map(id=>btn(`${icon(id)}<span>${ITEMS[id].name}</span><b>×${fmt(s.inventory[id])}</b>`,'item:'+id,'exp-pack-item'+(ui.item===id?' selected':''),`data-item="${id}" aria-pressed="${ui.item===id}"`)).join('')||'<p class="exp-hand">An empty pack. Room for what comes next.</p>'}</div></div>`:statList(h,s)}<div class="exp-skill-count">${h.skillPoints} skill points ${btn('Develop techniques →','tab:3')}</div></aside></div>${inventory?`<section id="item-detail" class="exp-inspection" aria-live="polite">${expeditionItemDetail(ui,ui.item)}</section>`:`<div class="exp-character-footer"><p class="exp-hand">${s.heroes.length===1?'For now, the salt road has only one set of footsteps.':'A different road brought each of us here. We go on together.'}</p>${btn('Inspect equipment →','tab:2','button quiet')}</div>`}`;}

export function expeditionItemDetail(ui,id){const it=ITEMS[id],s=ui.game.state,h=heroOf(ui);if(!it)return '<p class="exp-hand">Your pack is empty.</p>';const current=ITEMS[h.equip[it.slot]],keys=[...new Set([...Object.keys(it.stats),...Object.keys(current?.stats||{})])];return `<div class="exp-inspection-art">${icon(id)}</div><div class="exp-inspection-copy"><div class="exp-kicker">${it.slot} / ${it.unique?'PERSONAL KEEPSAKE':TIERS[it.tier-1]}</div><h3>${it.name}</h3><p>${esc(it.description)}</p>${it.slot!=='consumable'?`<small>Compared with ${current?.name||'an empty slot'} on ${h.name}.</small>`:''}<div class="exp-comparison">${keys.map(k=>{const d=(it.stats[k]||0)-(current?.stats?.[k]||0);return `<span>${names[k]||k} <b>${it.stats[k]||0}</b> <i class="${d<0?'exp-loss':'exp-gain'}">(${d>=0?'+':''}${d})</i></span>`;}).join('')}</div></div><div class="exp-inspection-action">${btn(it.slot==='consumable'?`Use on ${h.name}`:`Equip on ${h.name}`,(it.slot==='consumable'?'use:':'equip:')+id,'button primary')}<small>${it.unique?'Cannot be sold':`Sale value ${Math.max(1,Math.floor(it.price*.45))} ore`}</small></div>`;}
function mapPage(ui){const s=ui.game.state,visited=Object.keys(REGIONS).filter(id=>s.visited[id]).length;return `${header('The known world',`${visited} / ${Object.keys(REGIONS).length} REGIONS SURVEYED`)}<div class="map-layout"><div class="map-frame"><canvas id="atlas-map" class="map-canvas" aria-label="World survey: explored terrain, fog and discovered landmarks"></canvas><div class="map-tools">${btn('−','map-zoom:out','button quiet','aria-label="Zoom out"')}${btn('+','map-zoom:in','button quiet','aria-label="Zoom in"')}${btn('Center','map-reset','button quiet')}</div><div class="map-key">□ Settlement &nbsp; · Shelter / gateway &nbsp; + Crew<br>Only surveyed ground reveals its landmarks.</div></div><aside class="travel-list"><div class="exp-kicker">CARAVAN ROUTES</div><h3>Return to a harbor</h3><p>Liberated settlements keep a road open for the crew.</p><div class="exp-travel-routes">${Object.values(REGIONS).filter(r=>r.town&&s.flags[r.id+'_liberated']).map(r=>btn(`${r.name}<small>${r.town.name} →</small>`,'travel:'+r.id,'button quiet')).join('')||'<p class="exp-hand">Open the gates of Haventide to establish your first safe harbor.</p>'}</div><div class="exp-map-controls">Drag or arrows to pan<br>Scroll or + / − to zoom<br>R to recenter</div></aside></div>`;}
function requirements(t,h,s){const all=s.heroes.flatMap(x=>x.skills),r=[];for(const id of t.heroes)if(!s.heroes.some(x=>x.id===id))r.push(`Recruit ${HEROES[id].name}`);for(const id of t.requires||[])if(!all.includes(id))r.push(`Learn ${TECHS[id].name}`);if(t.level&&h.level<t.level)r.push(`Level ${t.level}`);if(t.tier&&s.tier<t.tier)r.push(TIERS[t.tier-1]);if(t.flag&&!s.flags[t.flag])r.push('Complete personal story');if(h.skillPoints<t.cost)r.push(`${t.cost} skill points`);return r;}
function skillsPage(ui){const s=ui.game.state,h=heroOf(ui);return `${header('A language of our own',`${h.skillPoints} SKILL POINTS AVAILABLE`)}${heroPicker(ui)}<div class="exp-skills-ledger">${Object.values(TECHS).filter(t=>t.heroes.includes(h.id)).map(t=>{const known=s.heroes.some(x=>x.skills.includes(t.id)),req=requirements(t,h,s);return btn(`<span class="exp-skill-sign">${known?'✓':t.heroes.length>1?'＋':'·'}</span><span class="item-name"><strong>${t.name}</strong>${t.heroes.length>1?`<em>${t.heroes.map(id=>HEROES[id].name).join(' + ')}</em>`:''}<span>${esc(t.description)}</span><small>${known?'Learned':req.length?req.join(' · '):'Ready to learn'}</small></span><span class="exp-skill-cost">${t.mp} MP<small>${known?'KNOWN':`${t.cost} SP`}</small></span>`,'learn:'+t.id,'exp-skill-row'+(known?' learned':req.length?' locked':' available'));}).join('')}</div><p class="exp-hand exp-footnote">Coordinated techniques use every participant’s ready gauge and MP. Their strength belongs to the whole crew.</p>`;}
function questRewards(q){return `<div class="exp-quest-rewards" aria-label="Quest rewards">${(q.rewardItems||[]).map(r=>{const name=ITEMS[r.id]?.name||({xp:'XP',food:'Food',ore:'Ore',energy:'Energy',renown:'Renown'}[r.id]||r.id);return `<span class="exp-quest-reward" title="${esc(name)} ×${fmt(r.amount)}" aria-label="${esc(name)} ${fmt(r.amount)}">${icon(r.id)}<b>${fmt(r.amount)}</b></span>`;}).join('')}${(q.rewardNotes||[]).map(note=>`<span class="exp-quest-benefit">${esc(note)}</span>`).join('')}</div>`;}
function questsPage(ui){const qs=questList(ui.game.state);return `${header('The threads we follow',`${qs.filter(q=>q.complete).length} RESOLVED / ${qs.length} RECORDED`)}<div class="exp-current-objective"><span class="exp-kicker">CURRENT OBJECTIVE</span><p>${esc(mainObjective(ui.game.state))}</p></div><div class="exp-quest-ledger">${qs.map(q=>`<article class="quest ${q.complete?'completed':''}" data-quest="${esc(q.id)}"><div class="exp-quest-meta"><div class="exp-kicker">${esc(q.kind||'Field story')}${q.stage!=null?' / '+esc(q.stage):''} · ${q.complete?'RESOLVED':'IN PROGRESS'}</div>${questRewards(q)}</div><div class="exp-quest-copy"><h3>${esc(q.title)}</h3><p>${esc(q.objective)}</p></div></article>`).join('')}</div>`;}

function savePage(){return `${header('Keep a record','LOCAL TO THIS BROWSER')}<p class="exp-hand">Safe checkpoints follow important discoveries. Keep a page for a different road.</p><div class="exp-save-ledger">${[1,2,3].map(slot=>{const m=saveMeta(slot);return `<article class="save-slot"><span class="exp-record-number">0${slot}</span><div><h3>Field record ${String(slot).padStart(2,'0')}</h3><p>${m?.corrupt?'Unreadable record — another slot can still be used.':m?`${esc(m.party)} · LEVEL ${m.level}<br>${esc(ALL_SCENES[m.region]?.name||'An unknown location')} · ${time(m.playTime)}<br><small>${new Date(m.savedAt).toLocaleString()}</small>`:'An unwritten page.'}</p></div><div class="button-group">${btn('Save','save:'+slot,'button primary')}${m&&!m.corrupt?btn('Load','load:'+slot,'button quiet'):''}${m?btn('Erase','delete:'+slot,'button quiet'):''}</div></article>`;}).join('')}</div><div class="exp-save-footer">${saveMeta('checkpoint')?btn('Resume checkpoint','load:checkpoint','button quiet'):''}${btn('New expedition','restart','button quiet')}</div>`;}
function settingsPage(ui){return ui.settingsBody();}
export function renderExpedition(ui){const s=ui.game.state;ui.hero=Math.min(ui.hero,s.heroes.length-1);const bodies=[mapPage,u=>characterPage(u,false),u=>characterPage(u,true),skillsPage,questsPage,savePage,settingsPage];return `<div class="scrim"></div><section class="atlas expedition" role="dialog" aria-modal="true" aria-label="Expedition menu"><header class="exp-shell"><div class="exp-brand"><strong>CHRONFORGE <span>ECHO</span></strong><small>THE ${esc((REGIONS[s.region]?.name||ALL_SCENES[s.region]?.townId||'HAVENTIDE').toUpperCase())} EXPEDITION</small></div><div class="exp-resources">${['food','ore','energy','renown'].map(id=>`<span aria-label="${fmt(s.resources[id])} ${id}">${icon(id)}${fmt(s.resources[id])}</span>`).join('')}</div>${btn('<kbd>Esc</kbd> Return','menu-close','close')}</header><nav class="tabs" role="tablist" aria-label="Expedition pages">${tabs.map((t,i)=>btn(`<small>${i+1}</small>${t}`,'tab:'+i,i===ui.tab?'active':'',`role="tab" aria-selected="${i===ui.tab}" aria-controls="exp-page" id="exp-tab-${i}"`)).join('')}</nav><div id="exp-page" class="atlas-body scroll exp-page exp-page-${ui.tab}" role="tabpanel" aria-labelledby="exp-tab-${ui.tab}">${ui.notice?`<div class="notice" role="status">${esc(ui.notice)}</div>`:''}${bodies[ui.tab](ui)}</div><footer class="atlas-footer"><span><kbd>1–7</kbd> Pages <kbd>Q</kbd><kbd>E</kbd> Tabs <kbd>↑↓</kbd> Navigate <kbd>PgUp/Dn</kbd> Scroll <kbd>Enter</kbd> Confirm</span><span>${TIERS[s.tier-1]} / ${time(s.playTime)}</span></footer></section>`;}
