import {dialogueLine,npcIdentity,npcPresent} from './npc-identities.js';
import {Application,Sprite,Texture} from 'pixi.js';
import './style.css';
import {REGIONS,ALL_SCENES,getScene,isWalkable,nearby,safeArrival} from './world.js';
import * as Art from './art.js';
import {ENEMIES,ITEMS,HEROES,TECHS} from './content.js';
import {encounterInteractionLabel,enemyNameWithLevel} from './enemy-levels.js';
import {drawEncounterLevels} from './enemy-labels.js';
import * as P from './progression.js';
import {SCENES,interactStory,onEvent} from './narrative.js';
import * as Narrative from './narrative.js';
import {createBattle,updateBattle,battleKey,battleClick,battleView,drawBattle} from './combat.js';
import {EchoAudio} from './audio.js';
import {UI} from './ui.js';
import {BattleUI} from './battle-ui.js';
import {saveState,loadState,latestSave} from './persistence.js';
import {reveal} from './maps.js';
import {prepareRecruitment,recruitmentActor,advanceRecruitment,completeRecruitment} from './recruitment.js';
import {loadAssets,assetDiagnostics} from './assets.js';
import {createContentRegistry,validateWorld} from './registry.js';
import {VIEW_WIDTH,VIEW_HEIGHT,RENDER_SCALE,artContext} from './rendering.js';
import {localDevHost} from './dev-access.js';
import {mountUpgradeTour} from './upgrade-tour.js';
const W=VIEW_WIDTH,H=VIEW_HEIGHT,copy=v=>JSON.parse(JSON.stringify(v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const errors=[];window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
const state=P.createState();
class Game{
 constructor(){this.state=state;this.mode='title';this.keys=new Set();this.audio=new EchoAudio();this.camera={x:0,y:0};this.followPath=[];this.followers=[];this.near=null;this.movePath=[];this.time=0;this.visualTime=0;this.frameTimes=[];this.logs=[];this.ui=new UI(this);this.battleUI=new BattleUI(this);this.rewardQueue=[];this.rewardClock=0;this.lastHud=0;this.transition=null;this.battle=null;this.battleResultTime=0;this.soundLog=0;this.moving=false;this.encounterCooldown=0;this.updateCamera(true);}
 get scene(){return getScene(this.state.region);}
 get visualState(){return this.devTools?.visualState(this.state)??this.state;}
 log(type,data={}){this.logs.push({time:+this.state.playTime.toFixed(2),type,...data});if(this.logs.length>400)this.logs.shift();}
 resetSession(){this.upgradeTour?.close();this.devTools?.reset();this.keys.clear();this.transition=null;this.near=null;this.movePath=[];this.moving=false;this.encounterCooldown=1;this.battleResultTime=0;this.soundLog=0;this.rewardQueue=[];this.rewardClock=0;this.time=0;this.visualTime=0;this.lastHud=0;document.querySelector('#rewards').replaceChildren();document.querySelector('.recruit-announcement')?.remove();this.ui.panel=null;this.ui.menu=false;this.ui.hero=0;this.ui.item=null;this.ui.qty=1;this.ui.sellMode=false;this.ui.notice='';this.ui.bindCapture=null;document.querySelector('#game').classList.toggle('reduced',!!this.state.settings.reducedMotion);}
 startNew(){this.state=P.createState();this.resetSession();this.mode='world';this.battle=null;this.audio.set(this.state.settings);this.resetFollowers();this.updateCamera(true);reveal(this.state,this.scene);this.ui.showDialogue(SCENES.opening||[{speaker:'Kaida',text:'The sea kept your signal, Mother. I will find someone who remembers how to answer.'},{speaker:'Kaida',text:'One road. One pair of boots. Haventide must still be out there.'}]);this.checkpoint();this.ui.render();this.log('new_game');}
 load(slot){try{const next=loadState(slot);Object.assign(next,this.safePoint(getScene(next.region),next.x,next.y));this.state=next;this.resetSession();this.battle=this.state.suspendedBattle||null;delete this.state.suspendedBattle;this.mode=this.battle?'battle':'world';this.audio.set(this.state.settings);this.resetFollowers();this.updateCamera(true);this.ui.render();if(this.state.flags.pendingEnding)this.presentEnding();this.log('load',{slot});}catch(e){this.ui.feedback({ok:false,message:e.message});}}
 saveSnapshot(){const {state,battle}=this.devTools?.saveSource()??this;const out=copy(state);if(battle)out.suspendedBattle=copy(battle);return out;}
 save(slot){try{saveState(this.saveSnapshot(),slot);this.audio.sound('confirm');this.log('save',{slot});return true;}catch(e){this.ui.feedback({ok:false,message:'Could not save: '+e.message});return false;}}
 presentEnding(){if(!this.state.flags.pendingEnding||this.mode!=='world'||this.transition)return;const p=this.state.endingProgress??={index:0,panel:'dialogue'};if(p.panel==='ending'){this.ui.panel={type:'ending'};this.ui.render();return;}this.ui.showDialogue(SCENES.ending,[],()=>{this.state.endingProgress={index:SCENES.ending.length,panel:'ending'};this.ui.panel={type:'ending'};this.ui.render();this.checkpoint();},{ending:true,index:clamp(p.index,0,SCENES.ending.length-1)});}
 completeEnding(){const result=Narrative.finishEnding(this.state);if(!result.ok){this.ui.feedback(result);return;}delete this.state.endingProgress;this.ui.panel=null;this.travelHub('haventide');this.checkpoint();this.ui.render();}
 checkpoint(){if(this.mode==='title'||this.battle)return;try{saveState(this.saveSnapshot());}catch(e){this.log('save_error',{message:e.message});}}
 resetFollowers(){const s=this.state,[dx,dy]={right:[-1,0],left:[1,0],up:[0,1],down:[0,-1]}[s.facing]||[-1,0];let p={x:s.x,y:s.y,facing:s.facing};this.followPath=Array.from({length:160},(_,i)=>{if(i&&isWalkable(this.scene,p.x+dx*3,p.y+dy*3))p={...p,x:p.x+dx*3,y:p.y+dy*3};return {...p};});this.followers=s.heroes.slice(1).map((h,i)=>({id:h.id,...this.followPath[(i+1)*24]}));}
 updateCamera(immediate=false){const r=this.scene,tx=clamp(this.state.x-W*.46,0,Math.max(0,r.width-W)),ty=clamp(this.state.y-H*.53,0,Math.max(0,r.height-H));if(immediate||this.state.settings.reducedMotion){this.camera.x=tx;this.camera.y=ty;}else{this.camera.x+=(tx-this.camera.x)*.14;this.camera.y+=(ty-this.camera.y)*.14;}}
 condition(req){if(!req)return true;if(typeof req==='string')return !!this.state.flags[req];return (!req.tier||this.state.tier>=req.tier)&&(!req.flag||this.state.flags[req.flag]);}
 requirement(req){const labels={beacon_restored:'Restore Haventide’s listening beacon.',vex_recruited:'Invite Vex to join the expedition.',rune_recruited:'Find Rune at Anchor Nine.',forest_seal:'Restore Forest Veil’s Heartwood Relay.',final_ready:'Restore all four living seals, hear the Crown’s memory, and reach Transcendent civilization.'};if(typeof req==='string')return labels[req]||'Open this settlement’s guarded gate first.';return [req?.tier?'Civilization required: '+['','Survivor','Reclaimer','Ascendant','Transcendent'][req.tier]+'.':'',req?.flag?labels[req.flag]||req.flag:''].filter(Boolean).join(' ');}
 interactionLabel(o){if(o.type==='encounter')return encounterInteractionLabel(o,this.state.cleared[o.id]);if(o.type==='pickup')return 'Recover '+(ITEMS[o.item]?.name||o.item);if(o.type==='sign')return 'Read '+(o.name||'sign');if(o.service==='construction')return 'Settlement works';if(o.type==='town')return this.condition(o.requires)?`Enter ${o.name}`:`${o.name} · entrance blocked`;if(o.type==='portal')return o.name;return o.name||'Inspect';}
 interact(obj=this.near){if(!obj||!npcPresent(obj,this.state)||this.ui.blocked||this.transition||this.state.recruitmentWalk)return;const s=this.state;this.keys.clear();this.movePath=[];
  if(obj.type==='sign'){this.ui.showReading(obj);return;}
  if(obj.type==='pickup'){if(s.pickups[obj.id])return;s.pickups[obj.id]=true;this.resolveResult(P.applyRewards(s,ITEMS[obj.item]?{items:{[obj.item]:obj.amount||1}}:{[obj.item]:obj.amount||1},'pickup:'+obj.id));this.audio.sound('pickup');this.checkpoint();this.ui.updateHUD();return;}
  if(obj.type==='encounter'){if(!this.condition(obj.requires)){this.ui.showDialogue([{speaker:'Field notes',text:this.requirement(obj.requires)}]);return;}this.beginBattle(obj);return;}
  if(['town','house','cave','portal'].includes(obj.type)){if(!this.condition(obj.requires)){if(obj.guard){const guard=this.scene.objects.find(o=>o.id===obj.guard);if(guard&&!s.cleared[guard.id]){const enemies=guard.enemies.map(enemyNameWithLevel).join(' + ');this.ui.confirm(`${obj.name} is blockaded`,`${enemies} ${guard.enemies.length===1?'holds':'hold'} the steps in front of the entrance. Defeat the gate sentry to enter the settlement.`,()=>this.beginBattle(guard),{eyebrow:'GUARDED ENTRANCE',confirmLabel:encounterInteractionLabel(guard),cancelLabel:'Step back'});return;}}this.ui.showDialogue([{speaker:'Field notes',text:this.requirement(obj.requires)}]);return;}this.travel(obj.to,obj.spawn);return;}
  if(obj.service==='construction'){this.ui.showBuild();return;}if(obj.service){this.ui.showVendor(obj);return;}
  const partyCount=s.heroes.length,result=interactStory(s,obj.id);this.log('interact',{id:obj.id});if(partyCount!==s.heroes.length)this.resetFollowers();if(result?.recruitment){const id=result.recruitment.id,target=this.followers.find(h=>h.id===id)||s,source=this.safePoint(this.scene,obj.x+(obj.hero===id?0:44),obj.y+(obj.hero===id?0:38));prepareRecruitment(s,id,this.scene,source,target,{sourceId:obj.id});this.moving=false;this.near=null;}if(result?.lines?.length||result?.rewards?.length||result?.choices?.length)this.resolveResult(result);else this.ui.showDialogue([dialogueLine(obj.name||'Field notes',obj.dialogue||'A fragment of the old world. Someone thought this place was worth remembering.',obj.type==='npc'?npcIdentity(obj):null)]);this.checkpoint();this.ui.updateHUD();
 }
 resolveResult(r,done){if(!r){done?.();return;}this.rewards(r.rewards||[]);if(r.lines?.length)this.ui.showDialogue(r.lines,r.choices||[],done);else done?.();if(r.ok===false&&r.message)this.rewards([{id:'notice',label:r.message,amount:1}]);}
 rewards(items){for(const r of items||[])this.rewardQueue.push(r);}
 finishRecruitment(){const reward=completeRecruitment(this.state);this.resetFollowers();this.moving=false;this.keys.clear();this.encounterCooldown=1;this.ui.updateHUD();this.checkpoint();if(reward){this.ui.rewards([reward]);this.audio.sound('confirm');this.log('companion_joined',{id:reward.id});}}
 travel(to,spawn){if(this.transition)return;if(this.state.recruitmentWalk)this.finishRecruitment();const next=getScene(to);const p=spawn||next.spawn;let dest=this.safePoint(next,p.x,p.y);const facing=this.state.facing;this.transition={time:0,duration:.55,swapped:false,to,spawn:dest,facing};this.keys.clear();this.movePath=[];this.audio.sound('door');}
 safePoint(scene,x,y){return safeArrival(scene,x,y);}
 travelHub(id){if(!this.state.flags[id+'_liberated'])return;const scene=getScene(id+'_town');this.travel(scene.id,scene.spawn);}
 beginBattle(encounter){if(this.mode==='battle')return;const start=()=>{this.battle=createBattle(this.state,{...encounter,biome:this.scene.biome});this.mode='battle';this.battleResultTime=0;this.soundLog=0;this.ui.panel=null;this.ui.render();this.keys.clear();this.log('battle_start',{id:encounter.id,count:encounter.enemies.length});};
  this.movePath=[];if(!this.state.flags.battle_taught){this.state.flags.battle_taught=true;this.ui.showDialogue([{speaker:'Kaida',text:encounter.enemies[0]==='rust_scrapper'?'A rust scrapper. Small enough to handle. Wait for the action gauge, then choose Attack.':`${ENEMIES[encounter.enemies[0]].name}. ${encounter.guard?'That is the sentry blocking the entrance.':'It has seen us.'} Wait for the action gauge, then choose Attack.`},{speaker:'Field notes',text:'Choose a ready companion, then an action and target. Up/Down selects; Right, Space or Enter confirms. A fresh Space or Enter when the white marker crosses the orange window raises critical chance. Incoming attacks open the same timing slot: catch the orange window to guard, then return to your selection. Left or Backspace goes back; Esc pauses everything.'}],[],start);}else start();
 }
 finishBattle(){const b=this.battle,id=b.encounter.id,first=!this.state.cleared[id];this.mode='world';this.battle=null;this.encounterCooldown=2;this.keys.clear();this.ui.render();
  if(b.result==='victory'){const reward=P.battleReward(b.encounter,first,()=>this.random());
   this.rewards(P.applyRewards(this.state,reward).rewards);const ending=id==='void_architect'&&!this.state.flags.ending_seen,result=onEvent(this.state,'victory',id);if(ending){this.rewards(result?.rewards||[]);this.state.endingProgress={index:0,panel:'dialogue'};this.presentEnding();}else this.resolveResult(result);this.audio.sound('victory');this.log('battle_won',{id,first,xp:reward.xp});
  }else if(b.result==='defeat'){P.rest(this.state);this.state.x=Math.max(32,this.state.x-90);const safe=this.safePoint(this.scene,this.state.x,this.state.y);this.state.x=safe.x;this.state.y=safe.y;this.ui.showDialogue([{speaker:'Kaida',text:'Not here. Not yet. We can retreat, mend what broke, and try a different approach.'},{speaker:'Field notes',text:'The crew has recovered. No equipment, quest progress, or settlement upgrades were lost. Learn techniques, improve defenses, or try the path around.'}]);this.log('battle_lost',{id});}else{this.state.x-=70;const safe=this.safePoint(this.scene,this.state.x,this.state.y);Object.assign(this.state,safe);this.log('battle_retreat',{id});}this.resetFollowers();this.updateCamera(true);this.checkpoint();}
 random(){let n=this.state.rng>>>0;n^=n<<13;n^=n>>>17;n^=n<<5;this.state.rng=n>>>0;return this.state.rng/4294967296;}
 walkTo(x,y){
  const r=this.scene,step=24,clearEdge=(a,b)=>{const samples=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])*step/3));for(let i=0;i<=samples;i++){const t=i/samples;if(!isWalkable(r,(a[0]+(b[0]-a[0])*t)*step,(a[1]+(b[1]-a[1])*t)*step))return false;}return true;},start=[Math.round(this.state.x/step),Math.round(this.state.y/step)],end=[Math.round(x/step),Math.round(y/step)],key=p=>p.join(',');
  const open=[{p:start,g:0,f:0}],seen=new Map([[key(start),{g:0,parent:null,p:start}]]);let found=null,iterations=0;
  while(open.length&&iterations++<18000){const n=(open.sort((a,b)=>a.f-b.f),open.shift());if(Math.hypot(n.p[0]-end[0],n.p[1]-end[1])<1.5){found=n.p;break;}for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const p=[n.p[0]+dx,n.p[1]+dy],k=key(p),g=n.g+1;if(seen.has(k)&&seen.get(k).g<=g||!clearEdge(n.p,p))continue;seen.set(k,{g,parent:n.p,p});open.push({p,g,f:g+Math.abs(p[0]-end[0])+Math.abs(p[1]-end[1])});}}
  if(found){const out=[];let n=seen.get(key(found));while(n?.parent){out.push({x:n.p[0]*step,y:n.p[1]*step});n=seen.get(key(n.parent));}this.movePath=out.reverse();
   // Grid proximity is only a search tolerance. Finish on reachable floor so a
   // rounded endpoint cannot leave a click just outside interaction distance.
   const tail=this.movePath.at(-1)||this.state;if(clearEdge([tail.x/step,tail.y/step],[x/step,y/step]))this.movePath.push({x,y});
  }else this.rewards([{id:'notice',label:'The route is blocked. Try a nearer point on the path.',amount:1}]);
 }
 update(dt){this.devTools?.update();this.time+=dt;if(this.rewardQueue.length){this.rewardClock-=dt;if(this.rewardClock<=0&&document.querySelector('#rewards').children.length<3){this.ui.rewards(this.rewardQueue.splice(0,Math.min(2,3-document.querySelector('#rewards').children.length,this.rewardQueue.length)));this.rewardClock=.85;}}this.audio.update(this.state.region,this.mode==='battle',this.ui.blocked);
  if(this.mode==='title'){this.visualTime+=dt;this.updateCamera(true);return;}if(this.ui.blocked||this.devTools?.open||this.upgradeTour?.open)return;this.visualTime+=dt;this.state.playTime+=dt;
  if(this.transition){const tr=this.transition;tr.time+=dt;if(tr.time>=tr.duration/2&&!tr.swapped){tr.swapped=true;this.state.region=tr.to;this.state.x=tr.spawn.x;this.state.y=tr.spawn.y;this.state.facing=tr.facing;this.resetFollowers();this.updateCamera(true);reveal(this.state,this.scene);this.log('transition',{to:tr.to,x:tr.spawn.x,y:tr.spawn.y});}if(tr.time>=tr.duration){this.transition=null;this.resolveResult(onEvent(this.state,'visit',this.state.region));this.checkpoint();this.ui.updateHUD();}return;}
  if(this.mode==='battle'){if(this.battle.result){updateBattle(this.battle,this.state,dt);this.battleResultTime+=dt;if(this.battleResultTime>1.35)this.finishBattle();return;}updateBattle(this.battle,this.state,dt);const logs=this.battle.logs.filter(l=>l.seq>this.soundLog);for(const l of logs){if(l.kind==='timing')this.audio.sound('timing');else if(l.kind==='crit')this.audio.sound('crit');else if(l.kind==='damage')this.audio.sound('hit');else if(l.kind==='heal')this.audio.sound('heal');}this.soundLog=this.battle.logSerial;return;}
  if(this.state.recruitmentWalk){this.keys.clear();this.movePath=[];this.moving=false;this.near=null;if(advanceRecruitment(this.state,dt))this.finishRecruitment();else this.moving=!!this.state.recruitmentWalk.leaderPath&&this.state.recruitmentWalk.elapsed<this.state.recruitmentWalk.leaderDuration;this.updateCamera();this.ui.positionInteraction();return;}
  P.production(this.state,dt);this.encounterCooldown=Math.max(0,this.encounterCooldown-dt);const s=this.state,r=this.scene,k=s.settings.keys||{};let dx=(this.keys.has('ArrowRight')||this.keys.has(k.right||'d')?1:0)-(this.keys.has('ArrowLeft')||this.keys.has(k.left||'a')?1:0),dy=(this.keys.has('ArrowDown')||this.keys.has(k.down||'s')?1:0)-(this.keys.has('ArrowUp')||this.keys.has(k.up||'w')?1:0);
  if(dx||dy)this.movePath=[];else if(this.movePath.length){const p=this.movePath[0],len=Math.hypot(p.x-s.x,p.y-s.y);if(len<5)this.movePath.shift();else{dx=(p.x-s.x)/len;dy=(p.y-s.y)/len;}}
  const len=Math.hypot(dx,dy),speed=this.keys.has('Shift')?245:165;this.moving=len>0;if(len){dx/=len;dy/=len;const oldX=s.x,oldY=s.y;if(isWalkable(r,s.x+dx*speed*dt,s.y))s.x+=dx*speed*dt;if(isWalkable(r,s.x,s.y+dy*speed*dt))s.y+=dy*speed*dt;if(s.x===oldX&&s.y===oldY)this.movePath=[];else{if(Math.abs(dx)>Math.abs(dy))s.facing=dx>0?'right':'left';else s.facing=dy>0?'down':'up';if(!this.followPath.length)this.followPath.push({x:oldX,y:oldY,facing:s.facing});let head=this.followPath[0],distance=Math.hypot(s.x-head.x,s.y-head.y);while(distance>=3){head={x:head.x+(s.x-head.x)*3/distance,y:head.y+(s.y-head.y)*3/distance,facing:s.facing};this.followPath.unshift(head);distance=Math.hypot(s.x-head.x,s.y-head.y);}if(this.followPath.length>180)this.followPath.length=180;this.followers=s.heroes.slice(1).map((h,i)=>({id:h.id,...(this.followPath[(i+1)*24]||this.followPath.at(-1))}));reveal(s,r);}}
  this.updateCamera();const near=nearby(r,s.x,s.y,s);this.near=near[0]||null;this.ui.positionInteraction();const encounter=near.find(o=>o.type==='encounter'&&!o.guard&&!s.cleared[o.id]&&this.condition(o.requires)&&Math.hypot(o.x-s.x,o.y-s.y)<25);if(encounter&&this.encounterCooldown===0){this.beginBattle(encounter);return;}const portal=near.find(o=>o.type==='portal'&&Math.hypot(o.x-s.x,o.y-s.y)<19);if(portal&&this.condition(portal.requires)){this.travel(portal.to,portal.spawn);return;}if(this.time-this.lastHud>.16){this.lastHud=this.time;this.ui.updateHUD();}}
 draw(ctx){ctx.clearRect(0,0,W,H);if(this.mode==='battle'){drawBattle(ctx,this.battle,this.state,this.visualTime);}else{Art.drawWorld(ctx,this.scene,this.camera,this.visualTime,this.visualState);const arriving=recruitmentActor(this.state),actors=[{id:'kaida',x:this.state.x,y:this.state.y,facing:this.state.facing},...this.followers.filter(a=>a.id!==arriving?.id),...(arriving?[arriving]:[])].sort((a,b)=>a.y-b.y);for(const a of actors){ctx.save();ctx.globalAlpha=a.opacity??1;Art.drawHero(ctx,a.id,Math.round(a.x-this.camera.x),Math.round(a.y-this.camera.y),{time:a.animationTime??this.visualTime,moving:(a.moving??this.moving)&&this.mode!=='title',facing:a.facing});ctx.restore();}if(Art.drawForeground)Art.drawForeground(ctx,this.scene,this.camera,this.visualTime,this.visualState,actors);drawEncounterLevels(ctx,this.scene,this.camera,this.visualState);if(this.movePath.length){const p=this.movePath.at(-1);ctx.strokeStyle='#e8e1c788';ctx.strokeRect(Math.round(p.x-this.camera.x)-5,Math.round(p.y-this.camera.y)-3,10,6);}}
  if(this.transition){const t=this.transition.time/this.transition.duration;ctx.fillStyle=`rgba(10,24,29,${Math.sin(t*Math.PI)})`;ctx.fillRect(0,0,W,H);}}
}
async function boot(){const content=createContentRegistry('base',{scenes:ALL_SCENES,enemies:ENEMIES,items:ITEMS,heroes:HEROES,techs:TECHS});validateWorld(content);await loadAssets(Art);const g=new Game(),canvas=document.createElement('canvas');canvas.width=W*RENDER_SCALE;canvas.height=H*RENDER_SCALE;const ctx=artContext(canvas.getContext('2d',{alpha:false}));ctx.setTransform(RENDER_SCALE,0,0,RENDER_SCALE,0,0);const app=new Application();await app.init({width:W,height:H,antialias:false,resolution:RENDER_SCALE,background:'#101e23',preference:'webgl',autoStart:false});document.querySelector('#stage').append(app.canvas);const texture=Texture.from(canvas);texture.source.scaleMode='linear';const sprite=new Sprite(texture);sprite.width=W;sprite.height=H;app.stage.addChild(sprite);
 document.querySelector('#loading').remove();g.resetFollowers();g.ui.render();g.audio.set(g.state.settings);g.log('ready',{native:[W,H]});
 g.upgradeTour=mountUpgradeTour(g);
 if(import.meta.hot)import.meta.hot.dispose(()=>g.upgradeTour.dispose());
 if(import.meta.env.DEV&&localDevHost(location)){const {mountDevTools}=await import('./dev-tools.js');g.devTools=mountDevTools(g);}
 window.__ECHO_READY__=true;
 window.addEventListener('keydown',e=>{if(g.upgradeTour?.handleKey(e)||g.devTools?.handleKey(e))return;const key=e.key.length===1?e.key.toLowerCase():e.key;g.audio.unlock();if([' ','Enter','Escape','Tab','Backspace','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(key))e.preventDefault();if(e.repeat)return;if(g.keys.has(key))return;g.keys.add(key);if(key==='Escape'){g.ui.handleEscape();return;}if(g.ui.handleKey(key))return;if(g.state.recruitmentWalk){if(key===' '||key==='Enter')g.finishRecruitment();return;}if(g.mode==='battle'){battleKey(g.battle,g.state,key);return;}if(key===' '||key==='Enter'||key===(g.state.settings.keys?.interact||'f')){e.preventDefault();g.interact();}});
 window.addEventListener('keyup',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;g.keys.delete(key);if(g.battle)battleKey(g.battle,g.state,{key,type:'keyup'});});window.addEventListener('blur',()=>g.keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.mode!=='title'&&!g.ui.menu&&!g.upgradeTour?.open){g.ui.menu=true;g.keys.clear();g.ui.render();}});
 app.canvas.addEventListener('pointerdown',e=>{g.audio.unlock();if(g.ui.blocked||g.devTools?.open||g.state.recruitmentWalk)return;const r=app.canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(g.mode==='battle'){if(battleClick(g.battle,g.state,x,y)==='pause')g.ui.toggleMenu();return;}if(g.near&&Math.hypot(x+g.camera.x-g.near.x,y+g.camera.y-g.near.y)<80){g.interact();return;}g.walkTo(x+g.camera.x,y+g.camera.y);});
 let prev=performance.now();function frame(now){const interval=now-prev;prev=now;g.frameTimes.push(interval);if(g.frameTimes.length>3600)g.frameTimes.shift();try{g.update(Math.min(.05,interval/1000));g.draw(ctx);g.battleUI.render();texture.source.update();app.renderer.render(app.stage);}catch(e){fatal(e);return;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
 if(import.meta.env.DEV&&new URLSearchParams(location.search).has('test')){window.__ECHO__={get game(){return g;},drawHero:Art.drawHero,actorBounds:Art.actorBounds,snapshot:()=>({state:copy(g.state),scene:g.scene.id,mode:g.mode,battle:g.battle?battleView(g.battle,g.state):null,panel:g.ui.panel?.type,paused:g.ui.menu,errors:[...errors],assets:copy(assetDiagnostics),artMetrics:Art.artMetrics(),frameTimes:g.frameTimes.slice(-600),logs:copy(g.logs)}),preset(name){g.state=P.createState();g.ui.panel=null;g.ui.menu=false;g.mode='world';g.battle=null;if(name==='party'||name==='battle-four'||name==='final'){P.recruit(g.state,'vex');P.recruit(g.state,'rune');P.awardXp(g.state,name==='final'?17000:2500);g.state.heroes.forEach(h=>h.skills=Object.values(TECHS).filter(t=>t.heroes.includes(h.id)).map(t=>t.id));}if(name==='settlement'){g.state.flags.haventide_liberated=true;g.state.region='haventide_town';Object.assign(g.state,g.scene.spawn);g.state.resources={food:500,ore:500,energy:500,renown:500};}if(name==='battle'||name==='battle-four'||name==='final'){g.state.flags.battle_taught=true;g.battle=createBattle(g.state,{id:'test_'+name,biome:'coast',enemies:name==='battle'?['rust_scrapper']:name==='final'?['void_architect']:['rust_scrapper','drone_sentinel','mutant_hound','gravbot'],boss:name==='final'});g.mode='battle';}g.resetFollowers();g.updateCamera(true);reveal(g.state,g.scene);g.ui.render();return this.snapshot();},interact(id){const obj=[...g.scene.objects,...g.scene.portals].find(o=>o.id===id);if(!obj)throw Error('Unknown object '+id);const pt=g.safePoint(g.scene,obj.x,obj.y+25);Object.assign(g.state,pt);g.near=obj;g.interact(obj);},goto(id){const r=getScene(id);g.state.region=id;Object.assign(g.state,r.spawn);g.ui.panel=null;g.ui.menu=false;g.mode='world';g.battle=null;g.resetFollowers();g.updateCamera(true);reveal(g.state,r);g.ui.render();},step(seconds){for(let i=0;i<seconds*60;i++)g.update(1/60);},key(k){if(!g.ui.handleKey(k)&&g.battle)battleKey(g.battle,g.state,k);},allScenes:Object.keys(ALL_SCENES)};}
}
function fatal(e){console.error(e);const load=document.querySelector('#loading');if(load)load.remove();document.querySelector('#overlay').innerHTML=`<div class="fatal"><h2>The field instrument needs attention.</h2><p>Required content failed to load. Reload after correcting the error.</p><pre></pre></div>`;document.querySelector('.fatal pre').textContent=e.stack||String(e);window.__ECHO_READY__=false;}
boot().catch(fatal);
