import { REGIONS,terrainAt } from './world.js';
export const FOG_CELL=120;
const points={haventide:[0,1],emberline:[1,1],orbital_reach:[2,1],last_crown:[3,1],forest_veil:[1,2],mire_bog:[2,2],crater_ember:[1,0],frost_canyon:[2,0]};
const colors={coast:['#47664e','#ab9670','#24555c'],grassland:['#47664e','#ab9670','#24555c'],desert:['#91714f','#b49a68','#486167'],forest:['#294e40','#827758','#214846'],mire:['#4e6550','#938459','#284b49'],volcanic:['#504d47','#927256','#a9553a'],snow:['#8faaa8','#697f7f','#355765'],ice:['#93b1b5','#738c95','#345363'],alien:['#687d70','#b4b9a1','#42656b']};
export function reveal(state,scene){const fog=state.fog[scene.id]??={};const cx=Math.floor(state.x/FOG_CELL),cy=Math.floor(state.y/FOG_CELL);for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++)if(dx*dx+dy*dy<11)fog[`${cx+dx},${cy+dy}`]=1;state.visited[scene.id]=true;}
export function isRevealed(state,id,x,y){return !!state.fog[id]?.[`${Math.floor(x/FOG_CELL)},${Math.floor(y/FOG_CELL)}`];}
export function drawMinimap(canvas,scene,state){const ctx=canvas.getContext('2d'),w=canvas.width=102,h=canvas.height=84;const pal=colors[scene.biome]||colors.coast;for(let y=0;y<h;y+=3)for(let x=0;x<w;x+=3){const wx=state.x+(x-w/2)*4,wy=state.y+(y-h/2)*4;const t=terrainAt(scene,wx,wy);ctx.fillStyle=wx<0||wy<0||wx>scene.width||wy>scene.height?'#12262b':t==='water'?pal[2]:t==='path'?pal[1]:scene.interior?'#637065':pal[0];ctx.fillRect(x,y,3,3);}for(const o of scene.objects){if(!['tree','rock','ruin','town','house','cave'].includes(o.type))continue;const x=(o.x-state.x)/4+w/2,y=(o.y-state.y)/4+h/2;ctx.fillStyle=o.type==='tree'?'#243e35':'#839385';ctx.fillRect(x-2,y-3,o.type==='tree'?4:7,o.type==='tree'?4:5);}if(scene.walkAreas){ctx.fillStyle='#16282c';for(let y=0;y<h;y+=3)for(let x=0;x<w;x+=3){const wx=state.x+(x-w/2)*4,wy=state.y+(y-h/2)*4;if(!scene.walkAreas.some(a=>wx>=a.x&&wy>=a.y&&wx<a.x+a.w&&wy<a.y+a.h))ctx.fillRect(x,y,3,3);}}ctx.fillStyle='#eee8cf';ctx.fillRect(w/2-1,h/2-1,3,3);ctx.fillStyle='#cc5775';const d={up:[0,-4],down:[0,4],right:[4,0],left:[-4,0]}[state.facing]||[0,0];ctx.fillRect(w/2+d[0],h/2+d[1],2,2);}
// Interior positions remain anchored to their discovered outdoor doorway.
export function mapPosition(state){if(REGIONS[state.region])return{region:state.region,x:state.x,y:state.y};for(const r of Object.values(REGIONS)){const door=r.objects.find(o=>o.to===state.region);if(door)return{region:r.id,x:door.x,y:door.y};}return null;}
export class AtlasMap{
 constructor(game){this.game=game;this.zoom=1;this.panX=0;this.panY=0;this.detail=false;}
 key(k){if(['+','=','-','_'].includes(k)){this.zoom=Math.max(.55,Math.min(4,this.zoom*(k==='-'||k==='_'?.85:1.15)));return true;}const d={ArrowLeft:[28,0],ArrowRight:[-28,0],ArrowUp:[0,28],ArrowDown:[0,-28],a:[28,0],d:[-28,0],w:[0,28],s:[0,-28]}[k];if(d){this.panX+=d[0];this.panY+=d[1];return true;}if(k==='r'){this.zoom=1;this.panX=this.panY=0;return true;}return false;}
 mount(canvas){this.canvas=canvas;canvas.onwheel=e=>{e.preventDefault();this.zoom=Math.max(.55,Math.min(4,this.zoom*(e.deltaY>0?.9:1.1)));this.draw();};let start=null;canvas.onpointerdown=e=>{start=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const scale=canvas.width/canvas.clientWidth;this.panX+=(e.clientX-start[0])*scale;this.panY+=(e.clientY-start[1])*scale;start=[e.clientX,e.clientY];this.draw();};canvas.onpointerup=()=>start=null;this.draw();}
 draw(){const canvas=this.canvas;if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width=680,h=canvas.height=365,s=this.game.state,position=mapPosition(s);ctx.fillStyle='#102028';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#263c40';ctx.lineWidth=1;for(let x=0;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.save();ctx.translate(w/2+this.panX,h/2+this.panY);ctx.scale(this.zoom,this.zoom);ctx.translate(-w/2,-h/2);const bw=126,bh=74,ox=37,oy=34;const centers={};for(const[id,p]of Object.entries(points))centers[id]=[ox+p[0]*157+bw/2,oy+p[1]*106+bh/2];
 for(const r of Object.values(REGIONS)){if(!s.visited[r.id])continue;for(const p of r.portals){if(!s.visited[p.to]||!centers[p.to])continue;const a=centers[r.id],b=centers[p.to];ctx.strokeStyle='#55796c';ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();ctx.setLineDash([]);}}
 for(const[id,p]of Object.entries(points)){const r=REGIONS[id],x=ox+p[0]*157,y=oy+p[1]*106;ctx.fillStyle=s.visited[id]?'#213b3d':'#172c33';ctx.fillRect(x,y,bw,bh);ctx.strokeStyle=position?.region===id?'#d3ad68':'#344e50';ctx.strokeRect(x-.5,y-.5,bw+1,bh+1);if(s.visited[id]){const pal=colors[r.biome]||colors.coast;for(let cy=0;cy<bh;cy+=3)for(let cx=0;cx<bw;cx+=3){const wx=(cx+.5)/bw*r.width,wy=(cy+.5)/bh*r.height;if(!isRevealed(s,id,wx,wy))continue;const terrain=terrainAt(r,wx,wy);ctx.fillStyle=terrain==='water'?pal[2]:terrain==='path'?pal[1]:pal[0];ctx.fillRect(x+cx,y+cy,3,3);}for(const o of [...r.objects,...r.portals]){if(!['town','house','cave','portal','landmark'].includes(o.type)||!isRevealed(s,id,o.x,o.y))continue;const px=x+o.x/r.width*bw,py=y+o.y/r.height*bh;ctx.fillStyle=o.type==='town'?'#d3ad68':'#b0bfa7';ctx.fillRect(px-1,py-1,o.type==='town'?3:2,2);}if(position?.region===id){ctx.fillStyle='#eab3b4';ctx.fillRect(x+position.x/r.width*bw-2,y+position.y/r.height*bh-2,4,4);}ctx.fillStyle='#d8dfc7';ctx.font='9px monospace';ctx.fillText(r.name.toUpperCase(),x,y+bh+13);}else{ctx.fillStyle='#56686a';ctx.font='8px monospace';ctx.fillText('UNCHARTED',x+34,y+bh/2+3);}}
 ctx.restore();ctx.fillStyle='#7e9990';ctx.font='8px monospace';ctx.fillText('FIELD SURVEY / PRESENT WORLD',12,17);ctx.textAlign='right';ctx.fillText('N ↑',w-12,17);ctx.textAlign='left';}
}
