// Selected assets whose runtime neutral-background extraction has been baked.
const ids = new Set([
  'kaida_victory',
  'mutant_hound_walk',
  'gravbot_walk',
  'rust_scrapper_walk',
  'slag_rat_walk',
  'bog_stalker_walk',
  'glacier_wolf_walk',
  'mire_hulk_walk',
  'sandworm_walk',
  'ember_golem_walk',
  'mire_warden_walk',
  'haventide_town_center',
  'emberline_town_center',
  'orbital_reach_town_center',
  'last_crown_town_center',
  'forest_veil_town_center',
  'mire_bog_town_center',
  'crater_ember_town_center',
  'frost_canyon_town_center',
  'kaida_walk',
  'kaida_showcase',
  'emberline_props',
  'civic_production',
  'civic_culture',
  'haventide_interior',
  'haventide_civilians',
  'npc_haventide',
  'npc_emberline',
  'npc_orbital_reach',
  'npc_last_crown',
  'npc_house_keepers',
  'npc_road_towns',
  'forest_arch',
  'crater_gate',
  'orbital_arch',
  'coastal_world_details',
  'emberline_world_details',
  'whale_of_iron',
  'glasswood_elder',
  'second_sunrise',
  'orbital_tether',
  'seven_listeners',
  'first_gardener',
  'unmade_palace',
  'caves_coast_desert',
  'caves_forest_mire',
  'caves_orbital_frost',
  'caves_crater_crown',
  'rune_walk',
  'rune',
  'bog_stalker',
  'slag_rat',
]);

export function preparedAlpha(entry) {
  if (!ids.has(entry.id)) return entry;
  return {
    ...entry,
    authoring: {
      url: entry.url.replace('assets/', 'art/sources/'),
      key: entry.key,
      keyMin: entry.keyMin,
      backgroundSeeds: entry.backgroundSeeds,
      keyZones: entry.keyZones,
    },
    key: undefined,
  };
}
