import {HEROES,ITEMS,TECHS,BUILDINGS,TIERS,SERVICES} from './content.js';
import * as P from './progression.js';
import {mainObjective,questList,onEvent,interactStory} from './narrative.js';
import {drawPortrait,drawIcon,npcPortrait} from './art.js';
import {REGIONS,ALL_SCENES} from './world.js';
import {saveMeta,latestSave,deleteSave} from './persistence.js';
import {AtlasMap,drawMinimap} from './maps.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(id,cl='pixel-icon')=>`<canvas class="${cl}" data-icon="${esc(id)}" width="32" height="32"></canvas>`;
const portrait=(id,cl='portrait-large')=>`<canvas class="${cl}" data-portrait="${esc(id)}" width="192" height="192"></canvas>`;
const speakerPortrait=speaker=>{const hero=Object.keys(HEROES).find(id=>id===speaker?.toLowerCase());if(hero)return hero;if(/Field notes|relay|archive voice|sun-forge|command|Architect/i.test(speaker||''))return 'instrument';const first=(speaker||'').split(/[ •,’]/)[0],person=Object.values(ALL_SCENES).flatMap(s=>s.objects).find(o=>o.type==='npc'&&o.name?.split(/[ •,’]/)[0]===first);return npcPortrait(person||{name:speaker||'Field notes',id:speaker||'notes'});};
const button=(label,action,cl='button',extra='')=>`<button class="${cl}" data-do="${esc(action)}" ${extra}>${label}</button>`;
const mark=`<svg class="insignia-svg" viewBox="0 0 40 40" aria-hidden="true"><path d="M28 7A15 15 0 1 0 28 33M9 14H31M4 20H28M9 26H31" stroke="currentColor" stroke-width="1.4" fill="none"/><path d="m32 17 3 3-3 3" fill="currentColor"/></svg>`;
const fmt=n=>Math.floor(n??0).toLocaleString();
const duration=s=>`${Math.floor((s||0)/3600)}h ${Math.floor(((s||0)%3600)/60)}m`;
const costText=o=>Object.entries(o||{}).map(([k,v])=>`${fmt(v)} ${k}`).join(' · ');
const labels={str:'Strength',int:'Intellect',tec:'Technique',def:'Defense',spd:'Speed',crit:'Critical %',maxHp:'Max HP',maxMp:'Max MP'};
export class UI{
 constructor(game){this.game=game;this.root=document.querySelector('#overlay');this.hud=document.querySelector('#hud');this.panel=null;this.menu=false;this.tab=0;this.hero=0;this.item=null;this.qty=1;this.sellMode=false;this.map=new AtlasMap(game);this.notice='';this.bindCapture=null;this.root.addEventListener('click',e=>{const b=e.target.closest('[data-do]');if(b){this.game.audio.unlock();this.action(b.dataset.do);}});this.root.addEventListener('input',e=>{if(e.target.dataset.setting){game.state.settings[e.target.dataset.setting]=+e.target.value;game.audio.set(game.state.settings);}});this.root.addEventListener('focusin',e=>{const id=e.target.dataset.item;if(id){this.item=id;const d=this.root.querySelector('#item-detail');if(d){d.innerHTML=this.itemDetail(id);this.paint(d);}}});this.hud.addEventListener('click',e=>{if(e.target.closest('[data-atlas]'))this.toggleMenu();if(e.target.closest('[data-interact]'))game.interact();});}
 get blocked(){return this.menu||!!this.panel||this.game.mode==='title';}
 paint(root=this.root){root.querySelectorAll('[data-icon]').forEach(c=>drawIcon(c.getContext('2d'),c.dataset.icon,0,0,32));root.querySelectorAll('[data-portrait]').forEach(c=>drawPortrait(c.getContext('2d'),c.dataset.portrait,0,0,192));}
 focus(index=0){const list=this.focusables();if(list.length)list[(index+list.length)%list.length].focus({preventScroll:true});}
 focusables(){return [...this.root.querySelectorAll('button:not(:disabled),input')].filter(b=>b.offsetWidth>0);}
 handleKey(k){if(k==='Escape')return this.handleEscape();if(k==='Backspace'&&this.blocked){this.dismissTopLayer();return true;}if(this.bindCapture){if(!['Escape','Tab','Enter',' ','Backspace','q','e','1','2','3','4','5','6','7'].includes(k)){this.game.state.settings.keys??={};this.game.state.settings.keys[this.bindCapture]=k.toLowerCase();this.notice=`${this.bindCapture} is now ${k.toUpperCase()}.`;this.bindCapture=null;this.render();}return true;}
  if(this.menu&&this.panel?.type!=='confirm'){if(/^[1-7]$/.test(k)){this.tab=+k-1;this.notice='';this.render();return true;}if(k.toLowerCase()==='q'||k.toLowerCase()==='e'){this.tab=(this.tab+(k.toLowerCase()==='q'?6:1))%7;this.notice='';this.render();return true;}if(this.tab===0&&this.map.key(k)){this.map.draw();return true;}}
  if(!this.blocked)return false;
  const body=this.root.querySelector('.atlas-body');if(body&&['PageUp','PageDown','Home','End'].includes(k)){body.scrollTop=k==='Home'?0:k==='End'?body.scrollHeight:body.scrollTop+(k==='PageDown'?1:-1)*body.clientHeight*.85;return true;}
  if(body&&this.menu&&[1,4].includes(this.tab)&&['ArrowUp','ArrowDown'].includes(k)){body.scrollTop+=(k==='ArrowDown'?1:-1)*Math.max(64,body.clientHeight*.18);return true;}
  if(k==='Enter'||k===' '){if(this.panel?.type==='dialogue'&&!this.menu&&!this.atChoice()){this.nextDialogue();return true;}const el=document.activeElement;if(this.root.contains(el)&&el.tagName==='BUTTON')el.click();else this.focus();return true;}
  if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(k)){if(document.activeElement?.type==='range'&&['ArrowLeft','ArrowRight'].includes(k)){const e=document.activeElement;e.value=Math.max(0,Math.min(1,+e.value+(k==='ArrowRight'?.1:-.1)));e.dispatchEvent(new Event('input',{bubbles:true}));return true;}const list=this.focusables(),i=list.indexOf(document.activeElement);this.focus(i+(k==='ArrowUp'||k==='ArrowLeft'?-1:1));document.activeElement?.scrollIntoView({block:'nearest'});return true;}return true;
 }
 // Confirmations sit above the atlas; the atlas can in turn cover a service or
 // a conversation. Dismiss only the visible layer, never a story callback.
 dismissTopLayer(){if(this.bindCapture)this.bindCapture=null;else if(this.panel?.type==='confirm'){this.panel=this.confirmReturn||null;this.confirmReturn=null;}else if(this.menu)this.menu=false;else if(['vendor','build','help'].includes(this.panel?.type))this.panel=null;else return false;this.notice='';this.game.keys.clear();this.game.audio.sound('back');this.render();return true;}
 handleEscape(){if(!this.dismissTopLayer())this.toggleMenu();return true;}
 toggleMenu(){if(this.game.mode==='title')return;this.menu=!this.menu;this.notice='';this.bindCapture=null;this.game.keys.clear();this.game.audio.sound(this.menu?'confirm':'back');this.render();}
 close(){this.panel=null;this.notice='';this.game.keys.clear();this.render();}
 showDialogue(lines,choices=[],done){if(!lines?.length){done?.();return;}this.panel={type:'dialogue',lines:lines.map(l=>typeof l==='string'?{speaker:'Kaida',text:l}:l),index:0,choices,done};this.render();}
 atChoice(){const p=this.panel;return p?.type==='dialogue'&&p.index===p.lines.length-1&&p.choices?.length;}
 nextDialogue(){const p=this.panel;if(p?.type!=='dialogue'||this.menu)return;if(this.atChoice())return;if(++p.index>=p.lines.length){const done=p.done;this.panel=null;this.render();done?.();}else this.render();if(this.game.state.flags.pendingEnding){if(this.panel?.type==='dialogue')this.game.state.endingProgress={index:this.panel.index,panel:'dialogue'};this.game.checkpoint();}this.game.audio.sound('select');}
 feedback(r){if(!r)return;this.notice=r.message||'';this.game.rewards(r.rewards||[]);this.game.audio.sound(r.ok===false?'error':'confirm');this.render();}
 showVendor(obj){this.qty=1;this.sellMode=false;this.notice='';this.panel={type:'vendor',object:obj};this.render();}
 showBuild(){this.panel={type:'build'};this.notice='';this.render();}
 confirm(title,text,run){this.confirmReturn=this.panel;this.panel={type:'confirm',title,text,run};this.render();}
 action(a){const [act,arg,arg2]=a.split(':');const g=this.game,s=g.state,h=s.heroes[this.hero]||s.heroes[0];g.audio.sound('select');switch(act){
  case 'new':if(latestSave()!==null)this.confirm('Begin a new expedition?','Your manual save slots remain available. The automatic checkpoint will follow the new expedition.',()=>g.startNew());else g.startNew();break;
  case 'continue':g.load(latestSave());break;case 'title-controls':this.panel={type:'help'};this.render();break;case 'close':this.close();break;
  case 'open-atlas':this.toggleMenu();break;case 'menu-close':this.toggleMenu();break;case 'tab':this.tab=+arg;this.notice='';this.render();break;case 'hero':this.hero=+arg;this.render();break;
  case 'item':this.item=arg;this.render();this.root.querySelector('#item-detail button')?.focus();break;
  case 'equip':this.feedback(P.equip(s,h.id,arg));break;case 'unequip':this.feedback(P.unequip(s,h.id,arg));break;case 'use':if(g.mode==='battle'){this.feedback({ok:false,message:'Use the battle Item command to choose a field supply and ally.'});break;}this.feedback(P.useItem(s,arg,h.id));break;
  case 'learn':this.feedback(P.learn(s,h.id,arg));break;
  case 'save':g.save(arg);this.notice='Expedition recorded.';this.render();break;case 'load':this.confirm('Resume this expedition?','Unsaved progress will be replaced by this record.',()=>g.load(arg));break;
  case 'delete':this.confirm('Erase this record?','This permanently erases this save slot. Other records are preserved.',()=>{deleteSave(arg);this.panel=this.confirmReturn;this.notice='Record erased.';this.render();});break;
  case 'restart':this.confirm('Start over?','The current expedition returns to the solitary opening. Manual save slots remain available.',()=>g.startNew());break;
  case 'confirm-no':this.dismissTopLayer();break;case 'confirm-yes':{const f=this.panel.run;this.panel=null;f();this.confirmReturn=null;break;}
  case 'setting':s.settings[arg]=!s.settings[arg];document.querySelector('#game').classList.toggle('reduced',!!s.settings.reducedMotion);this.render();break;
  case 'rebind':this.bindCapture=arg;this.notice=`Press a new key for ${arg}. Menu and confirmation keys remain reserved.`;this.render();break;
  case 'map-zoom':this.map.key(arg==='in'?'+':'-');this.map.draw();break;case 'map-reset':this.map.key('r');this.map.draw();break;
  case 'travel':if(s.flags.pendingEnding){this.feedback({ok:false,message:'Close the atlas to finish the crew’s ending.'});break;}if(g.mode==='battle'){this.feedback({ok:false,message:'Finish or retreat from this encounter before traveling.'});break;}this.menu=false;this.panel=null;g.travelHub(arg);this.render();break;
  case 'dialogue-next':this.nextDialogue();break;case 'choice':{const p=this.panel,c=p.choices[+arg];s.flags[c.flag]=true;this.panel=null;this.render();g.resolveResult(onEvent(s,'choice',c.flag),p.done);g.checkpoint();break;}
  case 'story':{const vendor=this.panel.object;this.panel=null;g.resolveResult(interactStory(s,arg),()=>this.showVendor(vendor));g.checkpoint();break;}
  case 'qty':this.qty=Math.max(1,Math.min(10,this.qty+(arg==='up'?1:-1)));this.render();break;
  case 'trade-mode':this.sellMode=!this.sellMode;this.render();break;
  case 'buy':this.feedback(P.buy(s,arg,this.qty));break;case 'sell':this.feedback(P.sell(s,arg,Math.min(this.qty,s.inventory[arg]||0)));break;
  case 'rest':this.feedback(P.rest(s));g.checkpoint();break;case 'train':this.feedback(P.train(s));break;case 'research':this.feedback(P.research(s));break;
  case 'build':{const r=P.build(s,arg);this.feedback(r);if(r.ok)g.resolveResult(onEvent(s,'build',arg));g.checkpoint();break;}
  case 'tier':this.feedback(P.advanceTier(s));g.checkpoint();break;case 'ending-continue':g.completeEnding();break;
 }}
 shell(title,body,footer='↑ ↓ Navigate &nbsp; <kbd>PgUp/Dn</kbd> Scroll &nbsp; <kbd>Space</kbd>/<kbd>Enter</kbd> Confirm &nbsp; <kbd>Esc</kbd>/<kbd>Backspace</kbd> Return',tabs=false){return `<div class="scrim"></div><section class="atlas" role="dialog" aria-label="${esc(title)}"><header class="atlas-header"><div class="atlas-title">${mark}<div><div class="eyebrow">THE CREW’S FIELD ATLAS</div><h3>${title}</h3></div></div>${button(tabs?'<kbd>Esc</kbd> Return':'Atlas',tabs?'menu-close':'open-atlas','close')}</header>${tabs?`<nav class="tabs">${['Map','Party','Inventory','Skills','Quests','Save','Settings'].map((t,i)=>button(`<small>${i+1}</small>${t}`,'tab:'+i,i===this.tab?'active':'')).join('')}</nav>`:''}<div class="atlas-body scroll">${this.notice?`<div class="notice" role="status">${esc(this.notice)}</div>`:''}${body}</div><footer class="atlas-footer"><span>${footer}</span><span>${TIERS[this.game.state.tier-1]} / ${duration(this.game.state.playTime)}</span></footer></section>`;}
 render(){const g=this.game,s=g.state;const prev=document.activeElement?.dataset?.do;this.hud.style.display=(g.mode==='title'||this.menu||g.mode==='battle')?'none':'';let html='';
  if(this.panel?.type==='confirm'){const p=this.panel;html=`<div class="scrim"></div><section class="modal"><div class="eyebrow">FIELD RECORD</div><h2>${esc(p.title)}</h2><p>${esc(p.text)}</p><div class="button-group">${button('Keep exploring','confirm-no')}${button('Confirm','confirm-yes','button danger')}</div></section>`;}
  else if(this.menu)html=this.renderMenu();
  else if(this.panel?.type==='dialogue'){const p=this.panel,l=p.lines[p.index],id=speakerPortrait(l.speaker);html=`<section class="dialogue" role="dialog" aria-label="Conversation">${portrait(id,'dialogue-portrait')}<div><div class="dialogue-name">${esc(l.speaker||'Field notes')}</div><p class="dialogue-text">${esc(l.text)}</p>${this.atChoice()?`<div class="choices">${p.choices.map((c,i)=>button(esc(c.text),'choice:'+i)).join('')}</div>`:`<div class="dialogue-next">${button(`${p.index+1} / ${p.lines.length} &nbsp; <kbd>Space</kbd> Continue`,'dialogue-next','')}</div>`}</div></section>`;}
  else if(this.panel?.type==='vendor')html=this.renderVendor();else if(this.panel?.type==='build')html=this.renderBuild();else if(this.panel?.type==='help')html=this.shell('Your first steps',this.controls()+`<div class="rule"></div><p>Follow the salt road to the guarded settlement. Speak with residents, restore its beacon, and give the broken world a reason to answer.</p><div class="button-group">${button('Return','close')}</div>`);
  else if(this.panel?.type==='ending')html=this.renderEnding();else if(g.mode==='title')html=this.renderTitle();this.root.innerHTML=html;this.paint();if(this.menu&&this.tab===0){const c=this.root.querySelector('#atlas-map');if(c)this.map.mount(c);}const old=[...this.root.querySelectorAll('[data-do]')].find(b=>b.dataset.do===prev);if(old)old.focus({preventScroll:true});else if(html)this.focus(this.menu?8:0);this.updateHUD();}
 renderTitle(){return `<div class="title-vignette"></div><div class="title-top">${mark}<div class="edition">A CHRONICLE OF THE WORLD AFTER</div></div><section class="title-content"><div class="eyebrow">A SIGNAL. A SHORE. A SECOND BEGINNING.</div><h1>CHRONFORGE<span>ECHO</span></h1><div class="title-line"></div><p class="title-description">The world remembers what we lost.<br>Let’s give it something new to remember.</p><div class="title-actions">${latestSave()!==null?button('Continue the journey <span>↗</span>','continue',''):''}${button('Begin your expedition <span>→</span>','new','')}${button('Field guide <span>?</span>','title-controls','secondary')}</div></section><div class="title-coordinates"><b>HAVENTIDE</b>The salt road, first light<br>36° 07′ N &nbsp; / &nbsp; 14° 22′ E</div><div class="title-foot"><span>✦ &nbsp; AN ORIGINAL PIXEL-ART ADVENTURE</span><span><kbd>↑</kbd><kbd>↓</kbd> Choose &nbsp; <kbd>Enter</kbd> Begin &nbsp; / &nbsp; Headphones welcome</span></div>`;}
 updateHUD(){const g=this.game,s=g.state;if(g.mode==='title'||this.menu||g.mode==='battle')return;const scene=g.scene,o=g.near;this.hud.innerHTML=`<div class="hud-top"><div class="location-plaque"><div class="eyebrow">${esc(scene.subtitle)}</div><h3>${esc(scene.name)}</h3></div><div class="hud-right"><div class="resources">${['food','ore','energy','renown'].map(id=>`<span class="resource" title="${id}">${icon(id)}${fmt(s.resources[id])}</span>`).join('')}</div><button class="atlas-button" data-atlas><kbd>Esc</kbd> ATLAS</button></div></div><div class="objective"><div class="label">FIELD OBJECTIVE</div><p>${esc(mainObjective(s))}</p></div>${s.settings.minimap?'<div class="minimap-wrap"><canvas id="minimap"></canvas></div>':''}<div class="hud-bottom"><div class="party-strip">${s.heroes.map(h=>{const st=P.stats(h,s);return `<div class="hero-compact">${portrait(h.id,'compact-portrait')}<div><strong>${h.name}</strong> <small>LV ${h.level}</small><div class="meter"><i style="width:${h.hp/st.maxHp*100}%"></i></div><div class="meter mp"><i style="width:${h.mp/st.maxMp*100}%"></i></div></div></div>`;}).join('')}</div><div class="controls"><kbd>WASD</kbd> / <kbd>↑↓←→</kbd> Walk &nbsp; <kbd>Shift</kbd> Run<br><kbd>${esc((s.settings.keys?.interact||'F').toUpperCase())}</kbd> / <kbd>Space</kbd> Interact &nbsp; <kbd>Esc</kbd> Atlas</div></div>${o&&!this.panel?`<button class="interaction" data-interact><kbd>${esc((s.settings.keys?.interact||'F').toUpperCase())}</kbd> ${esc(g.interactionLabel(o))}</button>`:''}`;this.paint(this.hud);const mm=this.hud.querySelector('#minimap');if(mm)drawMinimap(mm,scene,s);}
 heroButtons(){return `<div class="button-group">${this.game.state.heroes.map((h,i)=>button(h.name,'hero:'+i,'button quiet'+(this.hero===i?' active':''))).join('')}</div>`;}
 renderMenu(){const bodies=[()=>this.mapBody(),()=>this.partyBody(),()=>this.inventoryBody(),()=>this.skillsBody(),()=>this.questsBody(),()=>this.saveBody(),()=>this.settingsBody()];return this.shell('Expedition record',bodies[this.tab](),'<kbd>1–7</kbd> Jump &nbsp; <kbd>Q</kbd>/<kbd>E</kbd> Tabs &nbsp; ↑ ↓ Navigate / read &nbsp; <kbd>PgUp/Dn</kbd> Scroll &nbsp; <kbd>Enter</kbd> Confirm &nbsp; <kbd>Esc</kbd> Resume',true);}
 mapBody(){const s=this.game.state;return `<div class="map-layout"><div class="map-frame"><canvas id="atlas-map" class="map-canvas" aria-label="Explored terrain atlas"></canvas><div class="map-tools">${button('−','map-zoom:out','button quiet')}${button('+','map-zoom:in','button quiet')}${button('Center','map-reset','button quiet')}</div><div class="map-key">□ Settlement &nbsp; · Shelter / gateway &nbsp; ◆ Crew<br>Unsurveyed ground remains in ink.</div></div><aside class="travel-list"><div class="eyebrow">ROADS WE HAVE OPENED</div><h3>Return to a harbor</h3><p class="small muted">Liberated settlements share a caravan network.</p><div class="rule"></div>${Object.values(REGIONS).filter(r=>r.town&&s.flags[r.id+'_liberated']).map(r=>button(esc(r.name)+'<small>Travel to '+esc(r.town.name)+'</small>','travel:'+r.id)).join('')||'<p class="small muted">Open the gates of Haventide to establish your first safe harbor.</p>'}<div class="rule"></div><p class="small muted">Drag or arrows to pan.<br>Scroll or + / − to zoom.<br>R to recenter.</p></aside></div>`;}
 partyBody(){const s=this.game.state;return `<div class="section-heading"><h2>The people beside you</h2><span class="label">${s.heroes.length} / 3 companions</span></div>${s.heroes.map(h=>{const st=P.stats(h,s);return `<article class="party-panel">${portrait(h.id)}<div class="party-info"><div class="row spread"><h3>${h.name} <span class="small muted">${HEROES[h.id].role}</span></h3><span class="amber">LV ${h.level}</span></div><div class="small muted">HP ${fmt(h.hp)} / ${st.maxHp} &nbsp; MP ${fmt(h.mp)} / ${st.maxMp} &nbsp; XP ${h.xp} / ${P.xpForLevel(h.level)} &nbsp; SP ${h.skillPoints}</div><div class="stats">${['str','int','tec','def','spd','crit'].map(k=>`<div class="stat"><span class="muted">${labels[k]}</span><span>${st[k]}</span></div>`).join('')}</div><div class="equipment-line">${Object.entries(h.equip).map(([slot,id])=>`<span>${slot.toUpperCase()} / ${id?ITEMS[id].name:'—'}</span>`).join('')}</div></div></article>`;}).join('')}${s.heroes.length===1?'<p class="small muted" style="margin-top:1.4cqw">For now, the salt road has only one set of footsteps.</p>':''}`;}
 inventoryBody(){const s=this.game.state,ids=Object.keys(s.inventory).filter(id=>s.inventory[id]>0).sort((a,b)=>ITEMS[a].slot.localeCompare(ITEMS[b].slot)||ITEMS[a].name.localeCompare(ITEMS[b].name));if(!ids.includes(this.item))this.item=ids[0];const h=s.heroes[this.hero]||s.heroes[0];return `<div class="section-heading"><h2>What we carry</h2><span class="label">${ids.length} kinds / EQUIPPED GEAR IS SEPARATE</span></div>${this.heroButtons()}<div class="columns wide-left"><div><div class="list">${ids.map(id=>{const it=ITEMS[id];return button(`${icon(id)}<span class="item-name">${esc(it.name)}<small>${it.slot.toUpperCase()} · ${TIERS[it.tier-1]}</small></span><span class="price">×${s.inventory[id]}</span>`,'item:'+id,'list-button',`data-item="${id}"`);}).join('')}</div><div class="rule"></div><div class="label">${h.name} / EQUIPPED</div><div class="button-group">${Object.entries(h.equip).map(([slot,id])=>button(`${slot}<small>${id?ITEMS[id].name:'Empty'}${id?' · Unequip':''}</small>`,'unequip:'+slot,'button quiet')).join('')}</div></div><aside id="item-detail" class="detail">${this.itemDetail(this.item)}</aside></div>`;}
 itemDetail(id){const it=ITEMS[id],s=this.game.state,h=s.heroes[this.hero]||s.heroes[0];if(!it)return '<p class="muted">Your pack is empty.</p>';const current=ITEMS[h.equip[it.slot]],keys=new Set([...Object.keys(it.stats),...Object.keys(current?.stats||{})]);return `${icon(id,'big-icon')}<div class="eyebrow">${it.slot} / ${it.unique?'Keepsake':TIERS[it.tier-1]}</div><h3>${esc(it.name)}</h3><p class="small muted">${esc(it.description)}</p><div class="stats">${[...keys].map(k=>{const diff=(it.stats[k]||0)-(current?.stats?.[k]||0);return `<div class="stat"><span>${labels[k]||k}</span><span>${it.stats[k]||0} <i class="diff" style="color:${diff<0?'#d9919c':'#84bda2'}">(${diff>=0?'+':''}${diff})</i></span></div>`;}).join('')}</div>${it.slot!=='consumable'?`<p class="small muted">Compared with ${current?.name||'an empty slot'} on ${h.name}.</p>`:''}<div class="button-group">${button(it.slot==='consumable'?`Use on ${h.name}`:`Equip on ${h.name}`,(it.slot==='consumable'?'use:':'equip:')+id,'button primary')}</div><p class="small muted">${it.unique?'A personal keepsake. Cannot be sold.':`Sale value ${Math.max(1,Math.floor(it.price*.45))} ore each.`}</p>`;}
 skillsBody(){const s=this.game.state,h=s.heroes[this.hero]||s.heroes[0];return `<div class="section-heading"><h2>A language of our own</h2><span class="amber">${h.skillPoints} skill points</span></div>${this.heroButtons()}<div class="list">${Object.values(TECHS).filter(t=>t.heroes.includes(h.id)).map(t=>{const known=s.heroes.some(x=>x.skills.includes(t.id)),req=[t.requires?.length?'First: '+t.requires.map(id=>TECHS[id]?.name||id).join(', '):'',t.level?'Lv '+t.level:'',t.tier?TIERS[t.tier-1]:'',t.flag?'Personal story':''].filter(Boolean).join(' · ');return button(`<span class="item-name">${known?'✓ ':''}${t.name} <span class="small teal">${t.heroes.length>1?t.heroes.map(id=>HEROES[id].name).join(' + '):''}</span><small>${esc(t.description)}<br>${known?'Learned':esc(req||'No prerequisite')}</small></span><span class="price">${t.mp} MP${known?'':`<br>${t.cost} SP`}</span>`,'learn:'+t.id,'list-button');}).join('')}</div><p class="small muted" style="margin-top:1cqw">Coordinated techniques use every participant’s ready gauge and MP. Their portraits join the same action.</p>`;}
 questsBody(){const qs=questList(this.game.state);return `<div class="section-heading"><h2>The threads we follow</h2><span class="label">${qs.filter(q=>q.complete).length} resolved / ${qs.length} recorded</span></div>${qs.map(q=>`<article class="quest ${q.complete?'completed':''}"><div class="eyebrow">${esc(q.kind||'Field story')} ${q.stage!=null?' / '+esc(q.stage):''}</div><h3>${esc(q.title)}</h3><p>${esc(q.objective)}</p><p class="small muted">${q.reward?esc(typeof q.reward==='string'?q.reward:costText(q.reward)):''}</p></article>`).join('')}`;}
 saveBody(){return `<div class="section-heading"><h2>Keep a record</h2><span class="label">LOCAL TO THIS BROWSER</span></div><p class="small muted">Safe checkpoints follow important discoveries. Manual records let you keep different choices.</p>${[1,2,3].map(slot=>{const m=saveMeta(slot);return `<article class="save-slot"><div><h3>Field record 0${slot}</h3><p class="small muted">${m?.corrupt?'Unreadable record — another slot can still be used.':m?`${esc(m.party)} · LV ${m.level}<br>${esc(ALL_SCENES[m.region]?.name||'An unknown location')} · ${duration(m.playTime)} · ${new Date(m.savedAt).toLocaleString()}`:'An unwritten page.'}</p></div><div class="button-group">${button('Save','save:'+slot)}${m&&!m.corrupt?button('Load','load:'+slot,'button quiet'):''}${m?button('Erase','delete:'+slot,'button quiet'):''}</div></article>`;}).join('')}<div class="button-group">${saveMeta('checkpoint')?button('Resume checkpoint','load:checkpoint','button quiet'):''}${button('New expedition','restart','button quiet')}</div>`;}
 controls(){return `<div class="controls-grid">${[['WASD / arrows','Walk; Shift to run'],['F / Space','Interact with the world'],['Esc','Pause / open field atlas'],['1–7 / Q E','Atlas tabs'],['PgUp / PgDn','Scroll atlas pages'],['Space / Enter','Confirm / execute'],['Backspace','Battle back / close service'],['Tab','Choose another ready hero'],['Mouse','Click commands; click ground to walk']].map(([k,t])=>`<div><kbd>${k}</kbd> ${t}</div>`).join('')}</div><div class="rule"></div><h3>The bright beat</h3><p class="small muted">During an attack, a white marker crosses the amber signal. Make one fresh Space or Enter press while it crosses to raise the chance of a critical hit. A clean timing cue confirms your input; a critical is a separate result. Normal attacks remain effective without it.</p>`;}
 settingsBody(){const s=this.game.state.settings;return `<div class="section-heading"><h2>Make room for yourself</h2><span class="label">PRESENTATION & CONTROLS</span></div><div class="columns"><div>${['music','sfx'].map(id=>`<label class="setting"><span>${id==='music'?'Music':'Sound effects'}<p>Original synthesized ${id==='music'?'regional score':'field and battle cues'}.</p></span><input aria-label="${id} volume" type="range" min="0" max="1" step="0.1" value="${s[id]}" data-setting="${id}"></label>`).join('')}${[['timingAssist','Timing assist','A modestly wider critical input opportunity.'],['reducedMotion','Restrained motion','Reduces camera motion and flashes.'],['minimap','Local survey','Show a small preview of immediate surroundings.']].map(([id,name,desc])=>`<div class="setting"><div>${name}<p>${desc}</p></div>${button(s[id]?'On':'Off','setting:'+id,'button quiet')}</div>`).join('')}<div class="label">FIELD KEY BINDINGS</div><div class="button-group">${[['up','w'],['left','a'],['down','s'],['right','d'],['interact','f']].map(([id,key])=>button(`${id}<small>${esc((s.keys?.[id]||key).toUpperCase())}</small>`,'rebind:'+id,'button quiet')).join('')}</div></div><div>${this.controls()}</div></div>`;}
 renderVendor(){const s=this.game.state,o=this.panel.object,service=o.service||'provisions',def=SERVICES[service],available=service==='rest'||P.serviceAvailable(s,service);let body=`<div class="merchant-heading">${portrait(npcPortrait(o),'merchant-portrait')}<div><div class="eyebrow">${esc(def?.name||'A warm welcome')}</div><h2>${esc(o.name)}</h2><p>${esc(def?.description||'There is always room by the lamp.')}</p></div></div><div class="rule"></div>`;if(o.id==='haventide_smith')body+=`<div class="button-group">${button(s.flags.smith_calibration_complete?'Ask about the restored tools':'A word about the forge','story:smith_calibration','button quiet')}</div>`;if(!available)body+=`<p>This service opens at ${TIERS[(def?.tier||1)-1]}, Kaida level ${def?.level||1}${def?.requires?' with a '+BUILDINGS[def.requires]?.name:''}.</p>`;else if(service==='inn'||service==='rest')body+=`<h3>Leave the road outside.</h3><p class="small muted">Recover the whole crew’s HP and MP. Share up to ${Math.max(0,8-(s.buildings.walls||0)*2)} food; a traveler with empty pockets is still welcome.</p><div class="button-group">${button('Rest by the lantern','rest','button primary')}</div>`;else if(service==='trainer')body+=`<p>Practice together: gain ${300+s.tier*100} XP for each hero.</p><div class="button-group">${button('Train · 30 food / 20 energy','train','button primary')}</div>`;else{if(service==='archivist')body+=`<div class="button-group">${button('Research Concord · 80 ore / 70 energy','research')}</div>`;const ids=this.sellMode?Object.keys(s.inventory).filter(id=>s.inventory[id]>0):P.serviceStock(s,service,s.region);body+=`<div class="row spread"><div class="button-group">${button(this.sellMode?'Sell from pack':'Buy supplies','trade-mode','button quiet')}${button('−','qty:down','button quiet')}<span style="padding:.7cqw">Quantity ${this.qty}</span>${button('+','qty:up','button quiet')}</div><span class="amber">${fmt(s.resources.ore)} ore available</span></div>${!this.sellMode?this.heroButtons():''}<div class="list">${ids.map(id=>{const it=ITEMS[id];const price=this.sellMode?Math.max(1,Math.floor(it.price*.45)):Math.ceil(it.price*(s.flags.mara_trade_route?.85:1));const old=ITEMS[(s.heroes[this.hero]||s.heroes[0]).equip[it.slot]];const statKeys=new Set([...Object.keys(it.stats),...Object.keys(old?.stats||{})]);const diff=[...statKeys].map(k=>{const n=(it.stats[k]||0)-(old?.stats?.[k]||0);return `${labels[k]||k} ${n>=0?'+':''}${n}`;}).join(', ');return button(`${icon(id)}<span class="item-name">${esc(it.name)} <small>${esc(it.description)} ${diff?'<br>vs '+esc((s.heroes[this.hero]||s.heroes[0]).name)+': '+esc(diff):''}</small></span><span class="price">${price} ore each<br>Own ${s.inventory[id]||0}</span>`,(this.sellMode?'sell:':'buy:')+id,'list-button',this.sellMode&&it.unique?'disabled':'');}).join('')}</div>`;}body+=`<div class="rule"></div>${button('Return to the settlement','close','button quiet')}`;return this.shell('A place in the community',body);}
 renderBuild(){const s=this.game.state;return this.shell('Settlement works',`<div class="section-heading"><h2>Give tomorrow a foundation</h2><span class="label">SHARED STORES / ALL HARBORS</span></div><div class="row spread"><div class="small amber">${costText(Object.fromEntries(Object.entries(s.resources).map(([k,v])=>[k,Math.floor(v)])))}</div>${button('Return to town','close','button quiet')}</div><div class="tier-heading"><div class="eyebrow">CIVILIZATION ${s.tier} / 4</div><h3>${TIERS[s.tier-1]}</h3><p class="small muted">${esc(P.tierRequirements(s))}</p>${s.tier<4?`<div class="button-group">${button('Advance to '+TIERS[s.tier],'tier','button primary')}</div>`:''}</div><div class="build-grid">${Object.values(BUILDINGS).map(b=>{const n=s.buildings[b.id]||0;return button(`${icon(b.id)}<span class="item-name">${b.name} <span class="teal">${n?'LV '+n:'Unbuilt'}</span><small>${esc(b.description||b.benefit||'')}<br>${n>=4?'Fully developed':costText(P.buildingCost(s,b.id))}</small></span><span class="price">${n>=4?'Complete':n?'Upgrade':'Build'}</span>`,'build:'+b.id,'list-button',n>=4?'disabled':'');}).join('')}</div><p class="small muted" style="margin-top:1cqw">Farms, mines, and extractors produce while you explore. Walls protect the whole crew. Training, forging, and research open new services. All eight structures can reach level four.</p>`);}
 renderEnding(){return `<section class="ending"><div class="ending-content">${mark}<div class="eyebrow">THE WORLD, UNFINISHED</div><h1>Another morning.</h1><p>The Architect’s silence breaks into a thousand ordinary sounds.<br>Hammers on a roof. Rain in new leaves. Someone calling a name.</p><p>Kaida leaves her sword beside the evening bell.<br>Vex opens a school with more questions than answers.<br>Rune builds a gate that opens from both sides.</p><p>No one promises that the world will never hurt again.<br>They promise that no one will have to rebuild it alone.</p><div class="rule"></div><div class="eyebrow">CHRONFORGE ECHO / THE SIGNAL CONTINUES</div>${button('Return to a living world','ending-continue','button primary')}</div></section>`;}
 rewards(items){for(const r of items){const el=document.createElement('div');el.className='reward';el.innerHTML=`${icon(r.id)}<div>${esc(r.label)} <b>${r.amount>1?'×'+fmt(r.amount):''}</b><small>${r.id==='xp'?'A little further along the road':'ADDED TO THE EXPEDITION'}</small></div>`;document.querySelector('#rewards').append(el);this.paint(el);setTimeout(()=>el.remove(),4900);}}
}
