import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=new URL('../',import.meta.url).pathname, campaign=JSON.parse(await fs.readFile(base+'evidence/campaign-browser.json','utf8'));
assert.equal(campaign.report.completed,true);assert.ok(campaign.snapshot.state.inventory.data_chip>0);
const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[],report={fixture:'Unmodified earned full-campaign snapshot, loaded through production save/load. Existing recovered Data Chips; no XP, item, flag, HP or location grants.',started:Date.now()};
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const read=()=>page.evaluate(()=>structuredClone(window.__ECHO__.game.state));
const xp=h=>{let n=h.xp;for(let lv=1;lv<h.level;lv++)n+=80+20*lv;return n;};
async function dialogue(){const lines=[];for(let i=0;i<40;i++){const p=await page.evaluate(()=>{const ui=window.__ECHO__.game.ui;return ui.panel?.type==='dialogue'?{line:ui.panel.lines[ui.panel.index],choice:ui.atChoice()}:null;});if(!p)return lines;lines.push(p.line);if(p.choice)return lines;await page.keyboard.press('Space');}throw Error('Dialogue did not finish');}
async function choose(flag){const i=await page.evaluate(flag=>window.__ECHO__.game.ui.panel.choices.findIndex(c=>c.flag===flag),flag);assert.ok(i>=0);await page.locator(`[data-do="choice:${i}"]`).focus();await page.keyboard.press('Enter');return dialogue();}
try{
 await page.routeWebSocket('**/*',socket=>{socket.send(JSON.stringify({type:'connected'}));socket.onMessage(()=>{});});await page.goto('http://127.0.0.1:4321/?test=1',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__ECHO_READY__);
 await page.evaluate(async state=>{const {saveState}=await import('/src/persistence.js');saveState(state,1);window.__ECHO__.game.load(1);},campaign.snapshot.state);
 report.approach=await page.evaluate(()=>{const g=window.__ECHO__.game,o=g.scene.objects.find(o=>o.id==='haventide_smith');g.walkTo(o.x,o.y+48);let steps=0;while(g.movePath.length&&steps++<6000)g.update(1/60);return {steps,from:{x:g.state.x,y:g.state.y},object:{x:o.x,y:o.y},remaining:g.movePath.length};});
 await page.keyboard.down('ArrowUp');await page.waitForTimeout(180);await page.keyboard.up('ArrowUp');await page.waitForFunction(()=>window.__ECHO__.game.near?.id==='haventide_smith');await page.keyboard.press('f');
 await page.locator('[data-do="story:smith_calibration"]').click();report.offer=await dialogue();report.accept=await choose('smith_calibration_accept');assert.equal(await page.evaluate(()=>window.__ECHO__.game.ui.panel?.type),'vendor','Accept result must finish before returning to vendor');
 const before=await read();assert.equal(before.flags.smith_calibration_started,true);await page.locator('[data-do="story:smith_calibration"]').click();report.handoffOffer=await dialogue();report.handoff=await choose('smith_calibration_handoff');assert.equal(await page.evaluate(()=>window.__ECHO__.game.ui.panel?.type),'vendor','Handoff result must finish before returning to vendor');
 const after=await read();assert.equal(after.inventory.data_chip,before.inventory.data_chip-1);assert.equal(after.inventory.ether_cell,before.inventory.ether_cell+2);assert.equal(after.resources.ore,before.resources.ore+35);assert.equal(after.flags.smith_calibration_complete,true);assert.equal(after.flags.rewardLedger.smith_calibration,true);for(const h of after.heroes)assert.equal(xp(h)-xp(before.heroes.find(v=>v.id===h.id)),150);
 await page.keyboard.press('Backspace');await page.keyboard.press('Escape');await page.keyboard.press('5');await page.screenshot({path:base+'evidence/vendor-browser-complete.png'});await page.keyboard.press('6');await page.locator('[data-do="save:2"]').click();await page.locator('[data-do="load:2"]').click();await page.locator('[data-do="confirm-yes"]').click();await page.waitForFunction(()=>window.__ECHO__.game.near?.id==='haventide_smith');await page.keyboard.press('f');await page.locator('[data-do="story:smith_calibration"]').click();report.revisit=await dialogue();const loaded=await read();assert.equal(await page.evaluate(()=>window.__ECHO__.game.ui.panel?.type),'vendor');assert.equal(loaded.flags.smith_calibration_complete,true);assert.deepEqual(loaded.inventory,after.inventory);assert.deepEqual(loaded.heroes.map(xp),after.heroes.map(xp));assert.equal(errors.length,0);
 report.result='pass';report.exactRewards={xpPerHero:150,ore:35,etherCells:2,dataChipConsumed:1};report.inventoryBefore=before.inventory;report.inventoryAfter=after.inventory;report.completedFlags=loaded.flags;report.persistedAndIdempotent=true;
}catch(e){report.result='fail';report.failure=String(e);process.exitCode=1;}finally{report.wallSeconds=(Date.now()-report.started)/1000;report.errors=errors;await fs.writeFile(base+'evidence/vendor-browser.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({result:report.result,failure:report.failure,errors,wallSeconds:report.wallSeconds}));}
