import {reviewRoot} from '../scripts/review-output.mjs';
import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=new URL('../',import.meta.url).pathname,folder=reviewRoot + 'vex-refresh/';
const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});
const report={method:'Explicit NPC/party/encounter fixtures. Production Game.update, actual keyboard movement and battle selection render the real NPC, followers, portraits and timed actions. No screenshot pixels, pose overrides or battle damage are assigned. The separate pose/gait inspection uses main’s installed drawHero DEV hook.',errors:[],captures:[]};
page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
await page.routeWebSocket('**/*',s=>{s.send('{"type":"connected"}');s.onMessage(()=>{});});
const snap=()=>page.evaluate(()=>__ECHO__.snapshot());
async function step(seconds){await page.evaluate(seconds=>{for(let t=0;t<seconds;t+=1/60)window.vexUpdate.call(__ECHO__.game,Math.min(1/60,seconds-t));},seconds);}
async function capture(name){await page.evaluate(()=>__ECHO__.game.ui.render());await page.waitForTimeout(35);await page.screenshot({path:folder+name+'.png'});const s=await snap();report.captures.push({file:name+'.png',scene:s.scene,mode:s.mode,panel:s.panel,battle:s.battle});}
async function battle(){await page.evaluate(async()=>{__ECHO__.preset('party');const g=__ECHO__.game,{createBattle}=await import('/src/combat.js');g.resetSession();g.state.flags.battle_taught=true;g.battle=createBattle(g.state,{id:'vex_art_fixture',name:'Vex art review',biome:'desert',enemies:['gravbot']});g.mode='battle';g.ui.render();});}
async function ready(){await page.evaluate(()=>{const g=__ECHO__.game;for(let n=0;n<10000;n++){if(g.battle.heroes.find(h=>h.id==='vex').atb===100&&!g.battle.action)return;window.vexUpdate.call(g,.02);}throw Error('Vex never became ready');});for(let i=0;i<4&&(await snap()).battle.selectedHero!=='vex';i++)await page.keyboard.press('Tab');assert.equal((await snap()).battle.selectedHero,'vex');await page.keyboard.press('Enter');}
async function action(tech){await ready();if(tech){await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const ts=(await snap()).battle.techs,i=ts.findIndex(t=>t.id===tech);assert.ok(i>=0);assert.equal(ts[i].unavailable,'');for(let n=0;n<i;n++)await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.keyboard.press('Enter');}else{await page.keyboard.press('Enter');await page.keyboard.press('Enter');}assert.equal((await snap()).battle.action.participants[0],'vex');}
try{
 await page.goto('http://127.0.0.1:4321/?test=1',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__ECHO_READY__);await page.evaluate(()=>{window.vexUpdate=__ECHO__.game.update;__ECHO__.game.update=()=>{};__ECHO__.preset('solo');__ECHO__.goto('emberline_town');const g=__ECHO__.game,o=g.scene.objects.find(o=>o.id==='vex');Object.assign(g.state,g.safePoint(g.scene,o.x,o.y+40));g.near=o;g.resetFollowers();g.updateCamera(true);g.ui.render();});
 await capture('npc-emberline');await page.keyboard.press('f');await capture('npc-dialogue-portrait');await page.keyboard.press('Escape');
 await page.evaluate(()=>{__ECHO__.preset('party');__ECHO__.goto('emberline');const g=__ECHO__.game;Object.assign(g.state,g.safePoint(g.scene,2150,1450));g.near=null;g.keys.clear();g.state.facing='right';g.resetFollowers();g.updateCamera(true);});await capture('crew-idle');
 for(const key of ['ArrowRight','ArrowDown','ArrowLeft','ArrowUp']){await page.keyboard.down(key);for(let i=0;i<2;i++){await step(.36);await capture('walk-'+key+'-'+i);}await page.keyboard.up(key);}
 await page.keyboard.press('Escape');await page.keyboard.press('2');await page.locator('[data-do="hero:1"]').click();await capture('party-portrait');await page.keyboard.press('Escape');
 for(const [label,tech] of [['attack',null],['void-lance','void_lance'],['heal','lantern_mend']]){await battle();await action(tech);let last=0;for(const t of [.16,.38,.65,.75,1.1]){await step(t-last);await capture('battle-'+label+'-'+String(t).replace('.','_'));last=t;}}
 report.assets=await page.evaluate(()=>__ECHO__.snapshot().assets);assert.deepEqual(report.assets.errors,[]);
 await page.evaluate(()=>{const cv=document.createElement('canvas');cv.id='pose-review';cv.width=1440;cv.height=840;Object.assign(cv.style,{position:'fixed',inset:0,zIndex:99999,width:'1440px',height:'840px'});document.body.append(cv);const c=cv.getContext('2d');c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.fillStyle='#192129';c.fillRect(0,0,1440,420);c.fillStyle='#e4d8c4';c.fillRect(0,420,1440,420);const poses=['idle','move','anticipate','attack','cast','hurt','guard','down','victory','front','back'];for(let row=0;row<2;row++){poses.forEach((pose,i)=>{const x=(i%6)*240+120,y=row*420+170+Math.floor(i/6)*195;__ECHO__.drawHero(c,'vex',x,y,{pose,scale:1.25,time:0,facing:pose==='front'?'down':pose==='back'?'up':'right'});c.fillStyle=row?'#151515':'#eee6d8';c.font='13px monospace';c.fillText(pose,x-80,y+28);});}});
 await page.locator('#pose-review').screenshot({path:folder+'poses-dark-pale.png'});
 await page.evaluate(()=>{const cv=document.querySelector('#pose-review'),c=cv.getContext('2d');c.fillStyle='#d9d8c9';c.fillRect(0,0,1440,840);for(const [row,facing] of ['right','down','up'].entries())for(let i=0;i<4;i++){__ECHO__.drawHero(c,'vex',i*300+160,row*270+200,{pose:'move',moving:true,facing,time:(i+.1)/9,scale:1.5});c.fillStyle='#151515';c.font='14px monospace';c.fillText(facing+' / '+i,i*300+100,row*270+240);}});
 await page.locator('#pose-review').screenshot({path:folder+'directional-gait.png'});assert.deepEqual(report.errors,[]);report.result='pass';
}catch(e){report.result='fail';report.failure=String(e);process.exitCode=1;}
finally{await fs.writeFile(folder+'results.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({result:report.result,failure:report.failure,captures:report.captures.length,errors:report.errors}));}
